### ISSUE TITLE
Don't fail with broken profiler file

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#1027]
Sometimes when one of our automated tests fails, the AVM just writes a partial profiler file.
I havent found the exact cause or steps to reproduce it but i suspect the AVM just quits for some reason, maybe a stop condition somewhere or just a bug.

Anyway, currently the analysis fails if one of these broken profiler files is encountered.

The coverage data is nice to have but i rather have all the issues in sonar and ignore the broken profiler file.
An option to not error out here and just print a warning would be a nice addition.

```
02:48:14 [sonar:sonar] XML XREF filter activated
02:48:16 [sonar:sonar] Coverage plugin version: 2.19.0-43454ca
02:48:16 [sonar:sonar] Checking directory E:\CodeCoverageData for *.out files: 325 file(s)
02:48:34 [sonar:sonar] line 2577:96 token recognition error at: '"'
02:48:34 [sonar:sonar] line 2577:97 mismatched input '<EOF>' expecting STRING
02:48:36 [sonar:sonar] line 2660:5 token recognition error at: '"Activ'
02:48:36 [sonar:sonar] line 2660:11 mismatched input '<EOF>' expecting STRING
02:48:36 
02:48:36 BUILD FAILED
02:48:36 E:\Build.xml:171: The following error occurred while executing this line:
02:48:36 E:\Build.xml:593: java.lang.NullPointerException
02:48:36 	at eu.rssw.antlr.profiler.ProfilerSessionVisitor.visitModuleDataLine(ProfilerSessionVisitor.java:71)
02:48:36 	at eu.rssw.antlr.profiler.ProfilerSessionVisitor.visitModuleDataLine(ProfilerSessionVisitor.java:39)
02:48:36 	at eu.rssw.antlr.profiler.ProfilerGrammarParser$ModuleDataLineContext.accept(ProfilerGrammarParser.java:441)
02:48:36 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
02:48:36 	at eu.rssw.antlr.profiler.ProfilerGrammarBaseVisitor.visitModuleData(ProfilerGrammarBaseVisitor.java:42)
02:48:36 	at eu.rssw.antlr.profiler.ProfilerGrammarParser$ModuleDataContext.accept(ProfilerGrammarParser.java:377)
02:48:36 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
02:48:36 	at eu.rssw.antlr.profiler.ProfilerGrammarBaseVisitor.visitProfiler(ProfilerGrammarBaseVisitor.java:21)
02:48:36 	at eu.rssw.antlr.profiler.ProfilerGrammarParser$ProfilerContext.accept(ProfilerGrammarParser.java:144)
02:48:36 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
02:48:36 	at eu.rssw.antlr.profiler.ProfilerUtils.getProfilerSession(ProfilerUtils.java:52)
02:48:36 	at eu.rssw.antlr.profiler.ProfilerUtils.getProfilerSession(ProfilerUtils.java:41)
02:48:36 	at org.sonar.plugins.openedge.ProfilerCoverageSensor.a(SourceFile:172)
02:48:36 	at org.sonar.plugins.openedge.ProfilerCoverageSensor.execute(SourceFile:145)
02:48:36 	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
02:48:36 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
02:48:36 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
02:48:36 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
02:48:36 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
02:48:36 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
02:48:36 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
02:48:36 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
02:48:36 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:392)
02:48:36 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:388)
02:48:36 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:357)
02:48:36 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
02:48:36 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
02:48:36 	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:150)
02:48:36 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
02:48:36 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
02:48:36 	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
02:48:36 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
02:48:36 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
02:48:36 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:48:36 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
02:48:36 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:48:36 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
02:48:36 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
02:48:36 	at com.sun.proxy.$Proxy3.execute(Unknown Source)
02:48:36 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
02:48:36 	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
02:48:36 	at org.sonarsource.scanner.ant.SonarQubeTask.launchAnalysis(SonarQubeTask.java:107)
02:48:36 	at org.sonarsource.scanner.ant.SonarQubeTask.execute(SonarQubeTask.java:88)
02:48:36 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
02:48:36 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
02:48:36 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:48:36 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
02:48:36 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
02:48:36 	at org.apache.tools.ant.Task.perform(Task.java:348)
02:48:36 	at org.apache.tools.ant.Target.execute(Target.java:435)
02:48:36 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
02:48:36 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
02:48:36 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
02:48:36 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
02:48:36 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
02:48:36 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
02:48:36 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
02:48:36 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
02:48:36 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:48:36 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
02:48:36 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
02:48:36 	at org.apache.tools.ant.Task.perform(Task.java:348)
02:48:36 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
02:48:36 	at net.sf.antcontrib.logic.IfTask$ElseIf.execute(IfTask.java:144)
02:48:36 	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:211)
02:48:36 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:48:36 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
02:48:36 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:48:36 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
02:48:36 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
02:48:36 	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:154)
02:48:36 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
02:48:36 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
02:48:36 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:48:36 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
02:48:36 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
02:48:36 	at org.apache.tools.ant.Task.perform(Task.java:348)
02:48:36 	at org.apache.tools.ant.Target.execute(Target.java:435)
02:48:36 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
02:48:36 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
02:48:36 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
02:48:36 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
02:48:36 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
02:48:36 	at org.apache.tools.ant.Main.runBuild(Main.java:851)
02:48:36 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
02:48:36 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
02:48:36 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
```

**Comment by gquerret** [comment]
I agree that this kind of error shouldn't fail the build. A warning can be reported.

**Comment by gquerret** [comment]
Fixed
