### ISSUE TITLE
LinesTooLong - NPE Error during rule execution

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/sonar-openedge#1036]
Hello,

I have error for rule LinesTooLong.

See the class and stack trace below.

If I remove the anotation `@InitializeComponent.`, it works fine.  
If I add some code in `InitializeComponent` method, it works fine.  

The error came in sonalint and sonar-scanner.

# Versions 
Sonarqube : 8.9
CABL : 2.2.0
Openedge : 12.4.1

```openedge
BLOCK-LEVEL ON ERROR UNDO, THROW.

CLASS Erp.Toto 
    INHERITS System.Windows.Forms.UserControl :
        
        
    /*------------------------------------------------------------------------------
     Purpose:
     Notes:
    ------------------------------------------------------------------------------*/

    CONSTRUCTOR PUBLIC Toto (  ):
        SUPER ().
        InitializeComponent().
    END CONSTRUCTOR.
 
    @InitializeComponent.
    METHOD PRIVATE VOID InitializeComponent ( ):

    END METHOD. /* InitializeComponent */    

END CLASS.
```

Stack Trace : 
```
ActiveRule - Internal key eu.rssw.antlr.proparse.checks.LinesTooLong - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.LinesTooLong
Error during rule execution for [uri=file:/D:/Openedge/workspace-oe12-tests/archi-erp/Src/Erp/Toto.cls]
java.lang.NullPointerException
	at eu.rssw.antlr.proparse.checks.LinesTooLong.execute(SourceFile:1078)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.sensorExecute(OpenEdgeProparseCheck.java:57)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:401)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:176)
	at org.sonarsource.sonarlint.core.analysis.container.analysis.sensor.SensorsExecutor.executeSensor(SensorsExecutor.java:75)
	at org.sonarsource.sonarlint.core.analysis.container.analysis.sensor.SensorsExecutor.execute(SensorsExecutor.java:66)
	at org.sonarsource.sonarlint.core.analysis.container.analysis.AnalysisContainer.doAfterStart(AnalysisContainer.java:122)
	at org.sonarsource.sonarlint.core.plugin.commons.container.SpringComponentContainer.startComponents(SpringComponentContainer.java:182)
	at org.sonarsource.sonarlint.core.plugin.commons.container.SpringComponentContainer.execute(SpringComponentContainer.java:161)
	at org.sonarsource.sonarlint.core.analysis.container.module.ModuleContainer.analyze(ModuleContainer.java:71)
	at org.sonarsource.sonarlint.core.analysis.command.AnalyzeCommand.execute(AnalyzeCommand.java:58)
	at org.sonarsource.sonarlint.core.analysis.command.AnalyzeCommand.execute(AnalyzeCommand.java:32)
	at org.sonarsource.sonarlint.core.analysis.AnalysisEngine$AsyncCommand.execute(AnalysisEngine.java:153)
	at org.sonarsource.sonarlint.core.analysis.AnalysisEngine.executeQueuedCommands(AnalysisEngine.java:71)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by gquerret** [comment]
Confirmed, will be fixed in next release

**Comment by gquerret** [comment]
Fixed
