### ISSUE TITLE
Parser error: Mismatched input ''END'', expecting '{LEFTPAREN, MINUS, NAMEDO....

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#1066]
After updating some files to address flagged indentation issues (2.21), one file can no longer be parsed:
````
Mismatched input ''END'', expecting '{LEFTPAREN, MINUS, NAMEDOT, PERIOD, PLUS, UNKNOWNVALUE, ANNOTATION, ID, LEXDATE, NUMBER, QSTRING, AACBIT, AACONTROL, AALIST, AAMEMORY, AAMSG, AAPCONTROL, AASERIAL, AATRACE, ANALYZE, ASC, BIGINT, BUTTON, COLUMN, COMPARE, CURRENCY, DBIMS, ERRORCODE, ENABLEDFIELDS, FIELD, FIXCHAR, FONTBASEDLAYOUT, GETCODEPAGE, GETLICENSE, NORMAL, ONLY, ORDER, PINNABLE, PROCTEXT, PROCTEXTBUFFER, REPOSITIONMODE, SAVECACHE, SENDSQLSTATEMENT, SETCURRENTVALUE, STATUSBAR, TIMESTAMP, TOOLBAR, USERID2, IUNKNOWN, ABORT, ABSOLUTE, ABSTRACT, ACCELERATOR, ACCEPTCHANGES, ACCEPTROWCHANGES, ACCUMULATE, ACROSS, ACTIVE, ACTIVEFORM, ACTIVEWINDOW, ACTOR, ADDBUFFER, ADDCALCCOLUMN, ADDCOLUMNSFROM, ADDEVENTSPROCEDURE, ADDFIELDSFROM, ADDFIRST, ADDHEADERENTRY, ADDINDEXFIELD, ADDINTERVAL, ADDLAST, ADDLIKECOLUMN, ADDLIKEFIELD, ADDLIKEINDEX, ADDNEWFIELD, ADDNEWINDEX, ADDPARENTIDRELATION, ADDRELATION, ADDSCHEMALOCATION, ADDSOURCEBUFFER, ADDSUPERPROCEDURE, ADMDATA, ADVISE, AFTERBUFFER, AFTERROWID, AFTERTABLE, AGGREGATE, ALERTBOX, ALIAS, ALLOWCOLUMNSEARCHING, ALLOWPREVDESERIALIZATION, ALLOWREPLICATION, ALTERNATEKEY, ALWAYSONTOP, AMBIGUOUS, ANSIONLY, ANYKEY, ANYPRINTABLE, ANYWHERE, APPEND, APPENDCHILD, APPENDLINE, APPLALERTBOXES, APPLCONTEXTID, APPLICATION, APPLY, APPLYCALLBACK, APPSERVERINFO, APPSERVERPASSWORD, APPSERVERU...
````
The error from the pipeline:
````
[sonar:sonar] 5472/6541 - Current file: system/ids/stbent.i
[sonar:sonar] Syntax error -- <unknown> -- D:\AZDO_Agents\7.35\dev\oe12.2\sonar\bl\logistic\ifallmod\fields\asset_description.i:55:4 -- Mismatched input 'END' expecting { LEFTPAREN, MINUS, NAMEDOT, PERIOD, PLUS, UNKNOWNVALUE, ANNOTATION, ID, LEXDATE, NUMBER, QSTRING, AACBIT, AACONTROL, AALIST, AAMEMORY, AAMSG, AAPCONTROL, AASERIAL, AATRACE, ANALYZE, ... }
[sonar:sonar] Parser error in 'logistic/ifallgen/glperl.p' at position D:\AZDO_Agents\7.35\dev\oe12.2\sonar\bl\logistic\ifallmod\fields\asset_description.i:55:4
[sonar:sonar] org.antlr.v4.runtime.InputMismatchException: null
[sonar:sonar] 	at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:270)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.blockOrStatement(Proparse.java:1560)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.ifElse(Proparse.java:47238)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.ifStatement(Proparse.java:47139)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.statement(Proparse.java:3697)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.blockOrStatement(Proparse.java:1594)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.ifElse(Proparse.java:47238)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.ifStatement(Proparse.java:47139)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.statement(Proparse.java:3697)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.blockOrStatement(Proparse.java:1594)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.codeBlock(Proparse.java:1495)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.doStatementSub(Proparse.java:40560)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.doStatement(Proparse.java:40507)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.statement(Proparse.java:3606)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.blockOrStatement(Proparse.java:1594)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.ifThen(Proparse.java:47190)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.ifStatement(Proparse.java:47132)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.statement(Proparse.java:3697)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.blockOrStatement(Proparse.java:1594)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.codeBlock(Proparse.java:1495)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.procedureStatement(Proparse.java:57114)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.statement(Proparse.java:3858)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.blockOrStatement(Proparse.java:1594)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.Proparse.program(Proparse.java:1430)
[sonar:sonar] 	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:342)
````
I have looked very closely at the include mentioned (which was change), but cannot see any issue.

**Comment by gquerret** [comment]
Which version did you upgrade from ?
And do you have preprocessor instructions in the ELSE block ? From the stack trace, the code should look like:
```
procedure xxx:
 if condition then do:
   if condition2 then /* something */
   else end.
 end.
```
Maybe the preprocessor doesn't evaluation an expression correctly.

**Comment by stefandrissen** [comment]
I did not upgrade sonar-openedge (still on version 2.21) - I changed some of our code to resolve indentation issues. 

This file does use preprocessors and includes. When using the preprocessed file **and** enabling the analysis log I was finally given a useful line number which does indeed point to code that resolves to:

[code]
else
end.
[/code]

**Comment by gquerret** [comment]
Good to see you've found the error. You're probably aware of that, but this parser error won't be fixed in Proparse !

**Comment by stefandrissen** [comment]
I see that someone has reported a [bug](https://community.progress.com/s/article/else-or-then-followed-by-an-end-compiles) that this should not compile in the first place (with which I agree).
