### ISSUE TITLE
StackOverflowError during the analysis

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#1069]
On behalf of @SimonJohnAde

Analysis fails during OpenEdgeProparseSensor phase, with this stack trace:
```
at java.base/java.lang.String.toLowerCase(Unknown Source)
at java.base/java.lang.String.toLowerCase(Unknown Source)
at org.prorefactor.proparse.PreproEval.matches(PreproEval.java:677)
at org.prorefactor.proparse.PreproEval.matches(PreproEval.java:694)
at org.prorefactor.proparse.PreproEval.matches(PreproEval.java:694)
... repeated hundreds of times ...
```

Found that this preprocessor expression leads to this behavior when the propath is long enough:
```
&IF PROPATH MATCHES ("*something*") &THEN
```

**Comment by gquerret** [comment]
Hotfix branch created.

**Comment by gquerret** [comment]
Merged in main
