### ISSUE TITLE
NoViableAltException parser exceptions on DEFINE BUFFER statements

### ISSUE THREAD

**Issue by ssaulius123** [Riverside-Software/sonar-openedge#1107]
We have very big number of NoViableAltException on DEFINE BUFFER statements. As example one of 371 errors. Source code line looks:

```
DEFINE BUFFER cifval   FOR cif.
```

In SQ debug log we have and error:

```
[2024-01-15T07:13:35.610Z] 09:13:35.400 ERROR: Syntax error -- src/nbsf-services/services/cards/cardPreviewDbLang.p:29:28 -- no viable alternative at input 'cif'
[2024-01-15T07:13:35.610Z] 09:13:35.401 ERROR: Parser error in 'src/nbsf-services/services/cards/cardPreviewDbLang.p' at position src/nbsf-services/services/cards/cardPreviewDbLang.p:29:28
[2024-01-15T07:13:35.610Z] org.antlr.v4.runtime.NoViableAltException: null
[2024-01-15T07:13:35.610Z] 	at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2014)
[2024-01-15T07:13:35.610Z] 	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:499)
[2024-01-15T07:13:35.610Z] 	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:371)
[2024-01-15T07:13:35.610Z] 	at org.prorefactor.proparse.antlr4.Proparse.defineBufferStatement(Proparse.java:31248)
[2024-01-15T07:13:35.610Z] 	at org.prorefactor.proparse.antlr4.Proparse.statement(Proparse.java:3710)
[2024-01-15T07:13:35.610Z] 	at org.prorefactor.proparse.antlr4.Proparse.blockOrStatement(Proparse.java:1604)
[2024-01-15T07:13:35.610Z] 	at org.prorefactor.proparse.antlr4.Proparse.program(Proparse.java:1440)
[2024-01-15T07:13:35.610Z] 	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:345)
[2024-01-15T07:13:35.610Z] 	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:299)
[2024-01-15T07:13:35.610Z] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:306)
[2024-01-15T07:13:35.610Z] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:176)
[2024-01-15T07:13:35.610Z] 	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
[2024-01-15T07:13:35.610Z] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:88)
[2024-01-15T07:13:35.610Z] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:61)
[2024-01-15T07:13:35.611Z] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:79)
[2024-01-15T07:13:35.611Z] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:61)
[2024-01-15T07:13:35.611Z] 	at org.sonar.scanner.scan.SpringModuleScanContainer.doAfterStart(SpringModuleScanContainer.java:82)
[2024-01-15T07:13:35.611Z] 	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
[2024-01-15T07:13:35.611Z] 	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
[2024-01-15T07:13:35.611Z] 	at org.sonar.scanner.scan.SpringProjectScanContainer.scan(SpringProjectScanContainer.java:401)
[2024-01-15T07:13:35.611Z] 	at org.sonar.scanner.scan.SpringProjectScanContainer.scanRecursively(SpringProjectScanContainer.java:397)
[2024-01-15T07:13:35.611Z] 	at org.sonar.scanner.scan.SpringProjectScanContainer.doAfterStart(SpringProjectScanContainer.java:366)
[2024-01-15T07:13:35.611Z] 	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
[2024-01-15T07:13:35.611Z] 	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
[2024-01-15T07:13:35.611Z] 	at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:135)
[2024-01-15T07:13:35.611Z] 	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
[2024-01-15T07:13:35.611Z] 	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
[2024-01-15T07:13:35.611Z] 	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
[2024-01-15T07:13:35.611Z] 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
[2024-01-15T07:13:35.611Z] 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
[2024-01-15T07:13:35.611Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-01-15T07:13:35.611Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[2024-01-15T07:13:35.611Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[2024-01-15T07:13:35.611Z] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
[2024-01-15T07:13:35.611Z] 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
[2024-01-15T07:13:35.611Z] 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
[2024-01-15T07:13:35.611Z] 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
[2024-01-15T07:13:35.611Z] 	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
[2024-01-15T07:13:35.611Z] 	at org.sonarsource.scanner.cli.Main.execute(Main.java:126)
[2024-01-15T07:13:35.612Z] 	at org.sonarsource.scanner.cli.Main.execute(Main.java:81)
[2024-01-15T07:13:35.612Z] 	at org.sonarsource.scanner.cli.Main.main(Main.java:62)
[2024-01-15T07:13:35.612Z] 
```

It is our sonar-project.properties (I cut out some secret info):

```
sonar.projectKey=key
sonar.sources=src/progress,src/nbsf-services,src/dbset/crm,src/dbset/req
sonar.oe.binaries=${env.WORKSPACE}/build/progress/rcode,${env.WORKSPACE}/build/nbsf-services/rcode
sonar.oe.propath=src/progress,src/includes,${env.WORKSPACE}/src/git/nbsx-shared/src/includes,${env.WORKSPACE}/src/git/nbsx-shared/src/progress,${env.DLC},${env.DLC}/tty
sonar.sourceEncoding=windows-1257
##Let's leave empty, and guarantee that we have everything in modules
sonar.oe.databases=
sonar.oe.aliases=
sonar.oe.dotpct=${env.WORKSPACE}/build/progress/xref,${env.WORKSPACE}/build/nbsf-services/xref
sonar.oe.dlc=${env.DLC}
sonar.oe.propath.dlc=true
##Modules:
##Module for main source code
sonar.oe.module1.pattern=src/progress/**
sonar.oe.module1.databases=${env.WORKSPACE}/dump/bank/bank.df,${env.WORKSPACE}/dump/logbank/logbank.df,${env.WORKSPACE}/dump/stat/stat.df,${env.WORKSPACE}/dump/tl/tl.df,${env.WORKSPACE}/dump/sulabaas/sulabaas.df,${env.WORKSPACE}/dump/tmpbank/tmpbank.df,${env.WORKSPACE}/dump/ar2022/ar2022.df,${env.WORKSPACE}/dump/kar/kar.df
sonar.oe.module1.aliases=bank;logbank;stat;tl;sulabaas;tmpbank;archive;archive0
##Module for nbsf-services
sonar.oe.module2.pattern=src/nbsf-services/**
sonar.oe.module2.databases=${env.WORKSPACE}/dump/bank/bank.df,${env.WORKSPACE}/dump/logbank/logbank.df,${env.WORKSPACE}/dump/tl/tl.df,${env.WORKSPACE}/dump/crm/crm.df,${env.WORKSPACE}/dump/req/req.df,${env.WORKSPACE}/dump/ar2022/ar2022.df
sonar.oe.module2.aliases=bank;logbank;tl;crm;req;archive
sonar.oe.module2.propath=src/nbsf-services,src/includes,src/progress,${env.WORKSPACE}/src/git/nbsx-shared/src/nbsf-services,${env.WORKSPACE}/src/git/nbsx-shared/src/includes,${env.WORKSPACE}/src/git/nbsx-shared/src/progress
##Module for CRM modules
sonar.oe.module3.pattern=src/dbset/crm/**
sonar.oe.module3.databases=${env.WORKSPACE}/dump/bank/bank.df,${env.WORKSPACE}/dump/logbank/logbank.df,${env.WORKSPACE}/dump/crm/crm.df
sonar.oe.module3.aliases=bank;logbank;crm
sonar.oe.module3.propath=${env.WORKSPACE}/src/git/cards/src/includes,${env.WORKSPACE}/src/git/nbsx-shared/src/includes
##Module for REQ modules
sonar.oe.module4.pattern=src/dbset/req/**
sonar.oe.module4.databases=${env.WORKSPACE}/dump/bank/bank.df,${env.WORKSPACE}/dump/logbank/logbank.df,${env.WORKSPACE}/dump/req/req.df,${env.WORKSPACE}/dump/tl/tl.df,${env.WORKSPACE}/dump/ar2022/ar2022.df
sonar.oe.module4.aliases=bank,logbank,req,tl,archive
##No Copy-Paste Detection on DF files
sonar.cpd.exclusions=${env.WORKSPACE}/dump/**
sonar.oe.proparse.debug=false
sonar.oe.cpd.debug=false
sonar.oe.analytics=false
sonar.oe.coverage.profiler.dirs=${env.WORKSPACE}/target/profiler
#sonar.oe.preprocessor.proversion=12.6
sonar.lang.patterns.apex=-
sonar.analysis.git.prid=${env.CHANGE_ID} # pull request ID (taken from multibranch env variables, can be null for regular branch scan)
sonar.analysis.git.sourcebranch=${env.CHANGE_BRANCH} # from branch of the pull request (taken from multibranch env variables, can be null for regular branch scan)
sonar.analysis.git.targetbranch=${env.CHANGE_TARGET} # to branch of the pull request (taken from multibranch env variables, can be null for regular branch scan)
sonar.analysis.git.changeurl=${env.CHANGE_URL} # pull request url (taken from multibranch env variables, can be null for regular branch scan)
```

But can not publish whole workspace due security and size restrictions. But ready to share additional files by concrete request. 

I tried to make sample single file, but can not reproduce this error. My feeling is, that it is more related, when you scan huge and complex build (with several modules sections) or something like that. 

Any ideas?

Thank you

**Comment by gquerret** [comment]
`no viable alternative at input 'cif'` is the output you get when no DB table (or TT) can be found for the given table name. So first, you should check if you have a table by this name in your DF files. If it's a temp-table, check that it is correctly defined. A common trap could be that the TT is defined in a preprocessor section that is not visible to the parser (with nested `&IF` blocks for example). And as you have multiple modules with different DB schema, then double-check is the files which are failing belong to the right module. You can execute the analysis in verbose mode (huge log ouput expected...) to see which module a file belongs to.

**Comment by ssaulius123** [comment]
Thank you for quick reaction and help with github formatting @gquerret ;-) 

First  what I did - check tables. These tables exist and code is compiling. And I do not see any mess between real tables names and temp-tables - we do not have this practice to use "DEFINE BUFFER real_table_name FOR real_table_name". I take another example, where is only buffer declaration  (developer declare it, but do not use - use default table buffer):

`DEFINE BUFFER x-merloc FOR mer_loc.`

There is no any other entity with name x-merloc. Real table mer_loc exist in one df file and unique (no more databases with the same table name). There is no any temp-table with mer_loc.  And see an error:

![image](https://github.com/Riverside-Software/sonar-openedge/assets/108174688/bf44ab69-5163-44e1-95b4-c01b47f8c283)

If I tried to make sample for you (define buffer without usage), in sample I get normal error:

![image](https://github.com/Riverside-Software/sonar-openedge/assets/108174688/83e969ab-612d-4624-a1d5-c31e3b1bab68)

One "risky" place I see, that in main sonar-project.properties section, I leave empty database list:

![image](https://github.com/Riverside-Software/sonar-openedge/assets/108174688/7ba1a0aa-3902-4f7d-ab2d-24396ce471ee)

Modules section for this file look 

![image](https://github.com/Riverside-Software/sonar-openedge/assets/108174688/d642dcb5-0d55-43fd-9d67-498b9d48d275)

Can be problem there? And if yes, how to manage if we have different database connections list for modules?

**Comment by gquerret** [comment]
I think the first thing to do here is to verify that the file belongs to the right module. Execute scan with `-X` and check for this message: https://github.com/Riverside-Software/sonar-openedge/issues/1087#issuecomment-1808268957
Do you see a failure only on this module ? Or on all modules ?

Modules are checked sequentially. If you have a `src/dbset/crm/foo.p`, it will be checked against each module pattern (starting from 1 until the end). As soon as the pattern matches, file will be considered to belong to this module. If no pattern matches, then the file will belong to the default module (and won't have a DB connection in your case).

**Comment by ssaulius123** [comment]
I see failure on all modules, which have "DEFINE BUFFER buffer_name FOR table_name". I mean "NoViable" failure. 

I can not find any message like "File xxx matches pattern zzzz in module X" in my SQ debug log. For this module grep from debug file look like:
![image](https://github.com/Riverside-Software/sonar-openedge/assets/108174688/b3c76dbe-28d2-4f9b-acce-188754ea6c0a)

and most probable yes - patterns matching not working. I will check more carefully my sonar-project.properties path's (need to look to real workspace directories). And share results there.

**Comment by ssaulius123** [comment]
Fixed. Problem was in modules patterns matching. When I change pattern from 

`sonar.oe.module1.pattern=${env.WORKSPACE}/src/git/cards/src/nbsf-services/**
`

to

`sonar.oe.module1.pattern=src/nbsf-services/**
`

it start working, and I can see message 

![image](https://github.com/Riverside-Software/sonar-openedge/assets/108174688/0357be51-d62b-4906-97cb-9e6d3e12e15e)

I did it, because start refactoring so, that can see external includes (from other repo). In modules compilation, we use includes from other repo. And when we have SQ bug in external include, we do not see where 

![image](https://github.com/Riverside-Software/sonar-openedge/assets/108174688/6a35a61e-31a9-4756-823f-0be70e86c239)

Bug itself is counted in, but you can see test and url, because it is not in **src/dbset/req/card-letter.p** , but in **nbsx-shared/src/includes/transl-ng.i** . I need to find, how to manage and show it. Do you have any suggestions for it, @gquerret  ?

This bug can be closed. Thank you for help and pointing to my mistake.

**Comment by ssaulius123** [comment]
I see 2 ways. Let's say we have 2 SQ/Jenkins pipelines: accounts and payments. They use one additional repository includes for some old sty "include programming".

I can checkout includes as additional source code directory to account+includes and payments+includes. Then SQ analyse show each error from include twice: in account + payments.

I can create separate SQ project for includes. In general, it is already done, because we have not only includes there, but some classes, persistent procedures and so on. But I do not know, is it possible to configure SQ so, that errors in accounts and payments errors "from shared includes" will point this third project? 

I'm asking you Gilles just from you experience with your customers - how they solve "shared include" case? With library classes or persistent procedures there is not big problems - they must be analyzed and reported, where they compile. But include file is specific thing. You can not look to it as separate element from syntax analysis - you collect full preprocess source file and give errors from "full picture". Am I right?

Thank you for explanations

**Comment by gquerret** [comment]
I'd checkout the `includes` directory in both pipelines. Issues shown on include files always come from procedures and classes, no issues are reported directly on the include file. The number of lines of code of the include files will be counted twice.

* Issues can only be reported on the current project, so you can't checkout include files in a separate project and expect issues here
* Include files can be in the propath but not in the source directories. In this case, issues found within the include file are not reported.
* If an include file is not found during the analysis, no rules will be executed.

**Comment by ssaulius123** [comment]
Ok, clear. Thank you for your answers.
