### ISSUE TITLE
Parser issue with include file

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#137]
Shortest possible issue:
```
/* main file */
{ inc.i "{1}" }
```

and
```
/* inc.i */
message {1}.
```

Generates:
```
org.prorefactor.core.ProparseRuntimeException: main.p:2 Unmatched quote
	at org.prorefactor.proparse.Preprocessor.lexicalThrow(Preprocessor.java:507)
	at org.prorefactor.proparse.Lexer.quotedString(Lexer.java:400)
	at org.prorefactor.proparse.Lexer.nextToken(Lexer.java:129)
	at org.prorefactor.proparse.Postlexer.getNextToken(Postlexer.java:103)
	at org.prorefactor.proparse.Postlexer.nextToken(Postlexer.java:51)
	at org.prorefactor.proparse.TokenList.build(TokenList.java:51)
	at org.prorefactor.proparse.DoParse.doParse(DoParse.java:129)
	at org.prorefactor.proparse.DoParse.doParse(DoParse.java:105)
	at org.prorefactor.treeparser.ParseUnit.lex(ParseUnit.java:131)
```

**Comment by gquerret** [comment]
Same message with the compiler, so marked as invalid
