### ISSUE TITLE
Regression in master branch

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#145]
Since commit 55c8a5a17eaf8271735f94448ca1313f9e544247, any parse error in a parent class results in a RuntimeException, thus exiting the analysis. Previous behavior was to have standard exception, which was caught by ProparseSensor.

**Comment by gquerret** [comment]
Stack trace with 1.9.6:
```
     [java] ERROR: Error during code parsing for src/classes/bugsfixed/CacheChild.cls
     [java] org.sonar.plugins.openedge.api.org.prorefactor.core.ProparseRuntimeException: /Users/gquerret/Documents/workspace/sonaroe-test-project/src/classes/bugsfixed/CacheParent.cls:5:22: unexpected token: handle
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ParserSupport.defClass(ParserSupport.java:147) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.classstate(ProParser.java:5587) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.statement(ProParser.java:2043) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:427) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.program(ProParser.java:158) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.DoParse.doParse(DoParse.java:173) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.DoParse.doParse(DoParse.java:102) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:145) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:177) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:107) ~[na:na]
     ... snip ...
     [java] Caused by: org.sonar.plugins.openedge.api.antlr.NoViableAltException: unexpected token: handle
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.definevariablestate(ProParser.java:37675) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.definestatement(ProParser.java:7423) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.statement(ProParser.java:2120) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:427) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.code_block(ProParser.java:458) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.methodstate(ProParser.java:10313) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.statement(ProParser.java:2337) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:427) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.code_block(ProParser.java:458) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.classstate(ProParser.java:5623) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.statement(ProParser.java:2043) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:427) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.program(ProParser.java:158) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.DoParse.doParse(DoParse.java:173) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.DoParse.doParse(DoParse.java:102) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ParserSupport.parseSuper(ParserSupport.java:298) ~[na:na]
     [java] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ParserSupport.defClass(ParserSupport.java:138) ~[na:na]
     [java] 	... 40 common frames omitted
```

**Comment by gquerret** [comment]
Not sure anymore the problem lies here...

**Comment by gquerret** [comment]
It doesn't happen for the first class, but it does for the second class, i.e.:
* class Child1 inherits from Parent => we just have a ProparseException, handled by the sensor
* class Child2 inherits from Parent => we end up with a java.lang.Error, which can't be handled

Don't throw Error...

**Comment by gquerret** [comment]
Fixed
