### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by sonnesen** [Riverside-Software/sonar-openedge#186]
I get the following error when I try to execute the sonar task:

```
BUILD FAILED
java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(ArrayList.java:418)
        at java.util.ArrayList.get(ArrayList.java:431)
        at org.sonar.plugins.openedge.api.eu.rssw.listing.ListingParser.parseFile(ListingParser.java:117)
        at org.sonar.plugins.openedge.api.eu.rssw.listing.ListingParser.<init>(ListingParser.java:36)
        at org.sonar.plugins.openedge.sensor.OpenEdgeListingSensor.execute(OpenEdgeListingSensor.java:78)
        at org.sonar.batch.sensor.SensorWrapper.analyse(SensorWrapper.java:57)
        at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
        at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
        at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
        at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
        at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.ant.SonarQubeTask.launchAnalysis(SonarQubeTask.java:99)
        at org.sonarsource.scanner.ant.SonarQubeTask.execute(SonarQubeTask.java:81)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:853)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)

Total time: 1 minute 47 seconds
```

**Comment by gquerret** [comment]
Could you execute the analysis with verbose mode (`ant -v` or `sonar-scanner -X` depending on the scanner you're using) ? The last line before the exception will be the file where the exception occurs. If possible, could you attach the file to the issue ? I see where the exception occurs and how to fix it, but I just would like to see how the compiler could end up generating this kind of listing file...

Otherwise, you can just disable the listing parser by executing PCTCompile with `listing="false"`

**Comment by sonnesen** [comment]
Follows the execution log.
I disabled the listing parser and the task runs fine.

[log.zip](https://github.com/Riverside-Software/sonar-openedge/files/783299/log.zip)

**Comment by gquerret** [comment]
With `listing="true"`, could you attach the file `src/btb/btb432za.p` in `<buildDir>/.pct` ?

**Comment by sonnesen** [comment]
The log that I send to you was generated with listing="true" and unfortunately I can't send to you the file.
Can I help you with another information?

**Comment by gquerret** [comment]
I'm in fact only interested in the last section of the listing file, where block definitions can be found. The lines after:
```
     File Name       Line Blk. Type   Tran            Blk. Label            
-------------------- ---- ----------- ---- --------------------------------
```
You can send the file by mail if you don't want it to appear on GitHub, but I can understand you don't want to share the file, no problem.

**Comment by sonnesen** [comment]
Unfortunately, I can not send this information to you because this is a critical resource for the company and I am not allowed to send it to you.
Can I help you with any more information?

**Comment by gquerret** [comment]
Could you regenerate the listing file for `src/btb/btb432za.p` and send us the first block after the line:
```
     File Name       Line Blk. Type   Tran            Blk. Label            
-------------------- ---- ----------- ---- --------------------------------
```
That should be something like:
```
...es\sample\test2.p    0 Procedure   No                                    
    Buffers: tt1
             abc.Item
             b1
             abc.Customer
```
Feel free to remove the table names, the information I'm mostly interested in is the "Blk Type"

When you sent the log, you also probably redirected the error channel, as the stack is not visible. An error message is also probably logged, saying
```
[main] ERROR eu.rssw.listing.ListingParser - Unknown block type XXX
```

**Comment by gquerret** [comment]
Merged in master
