### ISSUE TITLE
unexpected token: MEMPTR

### ISSUE THREAD

**Issue by sonnesen** [Riverside-Software/sonar-openedge#187]
When I run the sonar task I get the following error:
```
[sonar:sonar] org.sonar.plugins.openedge.api.org.prorefactor.refactor.RefactorException: C:\desenv\git\Framework\totvs-fwk-progress\src\main\progress\fwk\utils\diProgress.p:1115:51: unexpected token: MEMPTR
[sonar:sonar]   at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:148) ~[na:na]
[sonar:sonar]   at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:177) ~[na:na]
[sonar:sonar]   at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:111) ~[na:na]
[sonar:sonar]   at org.sonar.batch.sensor.SensorWrapper.analyse(SensorWrapper.java:57) [sonar-scanner-engine-shaded-5.6.5.jar:na]
[sonar:sonar]   at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58) [sonar-scanner-engine-shaded-5.6.5.jar:na]
[sonar:sonar]   at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50) [sonar-scanner-engine-shaded-5.6.5.jar:na]
[sonar:sonar]   at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83) [sonar-scanner-engine-shaded-5.6.5.jar:na]
[sonar:sonar]   at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192) [sonar-scanner-engine-shaded-5.6.5.jar:na]
[sonar:sonar]   at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-5.6.5.jar:na]
[sonar:sonar]   at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-5.6.5.jar:na]
[sonar:sonar]   at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241) [sonar-scanner-engine-shaded-5.6.5.jar:na]
[sonar:sonar]   at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236) [sonar-scanner-engine-shaded-5.6.5.jar:na]
[sonar:sonar]   at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226) [sonar-scanner-engine-shaded-5.6.5.jar:na]
[sonar:sonar]   at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-5.6.5.jar:na]
[sonar:sonar]   at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-5.6.5.jar:na]
[sonar:sonar]   at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47) [sonar-scanner-engine-shaded-5.6.5.jar:na]
[sonar:sonar]   at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86) [sonar-scanner-engine-shaded-5.6.5.jar:na]
[sonar:sonar]   at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-5.6.5.jar:na]
[sonar:sonar]   at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-5.6.5.jar:na]
[sonar:sonar]   at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106) [sonar-scanner-engine-shaded-5.6.5.jar:na]
[sonar:sonar]   at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119) [sonar-scanner-engine-shaded-5.6.5.jar:na]
[sonar:sonar]   at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62) [sonar-scanner-api-batch4382372095018660775.jar:na]
[sonar:sonar]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
[sonar:sonar]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
[sonar:sonar]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
[sonar:sonar]   at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
[sonar:sonar]   at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60) [sonarqube-ant-task-2.5.jar:na]
[sonar:sonar]   at com.sun.proxy.$Proxy0.execute(Unknown Source) [na:na]
[sonar:sonar]   at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233) [sonarqube-ant-task-2.5.jar:na]
[sonar:sonar]   at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151) [sonarqube-ant-task-2.5.jar:na]
[sonar:sonar]   at org.sonarsource.scanner.ant.SonarQubeTask.launchAnalysis(SonarQubeTask.java:99) [sonarqube-ant-task-2.5.jar:na]
[sonar:sonar]   at org.sonarsource.scanner.ant.SonarQubeTask.execute(SonarQubeTask.java:81) [sonarqube-ant-task-2.5.jar:na]
[sonar:sonar]   at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293) [ant.jar:1.9.6]
[sonar:sonar]   at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[na:na]
[sonar:sonar]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
[sonar:sonar]   at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
[sonar:sonar]   at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106) [ant.jar:na]
[sonar:sonar]   at org.apache.tools.ant.Task.perform(Task.java:348) [ant.jar:1.9.6]
[sonar:sonar]   at org.apache.tools.ant.Target.execute(Target.java:435) [ant.jar:1.9.6]
[sonar:sonar]   at org.apache.tools.ant.Target.performTasks(Target.java:456) [ant.jar:1.9.6]
[sonar:sonar]   at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405) [ant.jar:1.9.6]
[sonar:sonar]   at org.apache.tools.ant.Project.executeTarget(Project.java:1376) [ant.jar:1.9.6]
[sonar:sonar]   at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41) [ant.jar:na]
[sonar:sonar]   at org.apache.tools.ant.Project.executeTargets(Project.java:1260) [ant.jar:1.9.6]
[sonar:sonar]   at org.apache.tools.ant.Main.runBuild(Main.java:853) [ant.jar:1.9.6]
[sonar:sonar]   at org.apache.tools.ant.Main.startAnt(Main.java:235) [ant.jar:1.9.6]
[sonar:sonar]   at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285) [ant-launcher.jar:na]
[sonar:sonar]   at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112) [ant-launcher.jar:na]
[sonar:sonar] Caused by: org.sonar.plugins.openedge.api.antlr.NoViableAltException: unexpected token: MEMPTR
[sonar:sonar]   at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.datatype_dll(ProParser.java:34998) ~[na:na]
[sonar:sonar]   at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.defineparam_as(ProParser.java:40165) ~[na:na]
[sonar:sonar]   at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.defineparam_var(ProParser.java:40048) ~[na:na]
[sonar:sonar]   at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.defineparameterstate(ProParser.java:36830) ~[na:na]
[sonar:sonar]   at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.definestatement(ProParser.java:7419) ~[na:na]
[sonar:sonar]   at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.statement(ProParser.java:2120) ~[na:na]
[sonar:sonar]   at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:427) ~[na:na]
[sonar:sonar]   at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.code_block(ProParser.java:458) ~[na:na]
[sonar:sonar]   at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.procedurestate(ProParser.java:11733) ~[na:na]
[sonar:sonar]   at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.statement(ProParser.java:2442) ~[na:na]
[sonar:sonar]   at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:427) ~[na:na]
[sonar:sonar]   at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.program(ProParser.java:158) ~[na:na]
[sonar:sonar]   at org.sonar.plugins.openedge.api.org.prorefactor.proparse.DoParse.doParse(DoParse.java:172) ~[na:na]
[sonar:sonar]   at org.sonar.plugins.openedge.api.org.prorefactor.proparse.DoParse.doParse(DoParse.java:101) ~[na:na]
[sonar:sonar]   at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:145) ~[na:na]
[sonar:sonar]   ... 47 common frames omitted
```

![image](https://cloud.githubusercontent.com/assets/14275591/23072343/82c8a492-f518-11e6-8e41-35d344c3cbb3.png)

[log.zip](https://github.com/Riverside-Software/sonar-openedge/files/783664/log.zip)

**Comment by gquerret** [comment]
Thanks for the bug report. Could you include the statement in your screenshot so that we can fix the problem ?

**Comment by sonnesen** [comment]
DEF VAR mMemPtr          AS MEMPTR NO-UNDO.
or
DEFINE VARIABLE mBuffer  AS MEMPTR    NO-UNDO.
or
DEFINE VARIABLE mLastInputInfo AS MEMPTR    NO-UNDO.
or
DEFINE OUTPUT PARAMETER piTime    as HANDLE TO MEMPTR.

That's all references to memptr in the code.
I hope it helps.

**Comment by gquerret** [comment]
That's really a surprise that this kind of statement could fail. Do you use the latest version available of the plugin ?

**Comment by sonnesen** [comment]
I think so. This is the plugin version and rules version.

![image](https://cloud.githubusercontent.com/assets/14275591/23083646/daf255c8-f545-11e6-9577-e586a74e83d3.png)

**Comment by sonnesen** [comment]
I've commented all references to MEMPTR in the source except this:

DEFINE OUTPUT PARAMETER piTime as HANDLE TO MEMPTR.

I think this is the statement that is causing the problem.

**Comment by gquerret** [comment]
Issue has been reproduced with this syntax. Interestingly, the error message when using a wrong datatype is `DLL datatype must be one of CHARACTER, BYTE, SHORT, UNSIGNED-SHORT, LONG, FLOAT, or DOUBLE (3383)` which doesn't mention that MEMPTR can be used.
Will be fixed in next release.

**Comment by gquerret** [comment]
Fixed in master
