### ISSUE TITLE
Analysis stuck in coverage sensor

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#210]
On behalf of O.
No CPU activity, no error message, process is stuck doing nothing...
Verbose mode shows that sensor is extracting executable line numbers from rcode.

RCode sent privately

**Comment by gquerret** [comment]
Exception thrown in test cases:
```
java.lang.IndexOutOfBoundsException
	at java.nio.ByteBuffer.wrap(ByteBuffer.java:375)
	at eu.rssw.pct.RCodeInfo.processProceduresInDebugSegment(RCodeInfo.java:255)
	at eu.rssw.pct.RCodeInfo.processDebugSegment(RCodeInfo.java:187)
	at eu.rssw.pct.RCodeInfo.<init>(RCodeInfo.java:105)
```

**Comment by gquerret** [comment]
Fixed in master
