### ISSUE TITLE
Exceptions with Single Line Comments

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#250]
The following single line comments create exceptions (Version 2.0):
```
//foo:~n&1":T
```
Exception: unexpected token: &1

```
//IF {lLoadDocumentHead} THEN DO:
```
Exception: unexpected token: THEN

**Comment by gquerret** [comment]
Do you have stack traces ? I've added those two code blocks in my sample test project, and they were imported and analyzed without any problem.

**Comment by movedoa** [comment]
Stack of the first error:

```
[sonar:sonar] org.sonar.plugins.openedge.api.org.prorefactor.refactor.RefactorException: C:\Buildtools\Jenkins\workspace\Sonar_Runner\Common\System\StringTable\StringTable2.p:4308:251: unexpected token: &1
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:148)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:177)
[sonar:sonar] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:109)
[sonar:sonar] 	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
[sonar:sonar] 	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
[sonar:sonar] 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
[sonar:sonar] 	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
[sonar:sonar] 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
[sonar:sonar] 	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
[sonar:sonar] 	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
[sonar:sonar] 	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
[sonar:sonar] 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
[sonar:sonar] 	at org.sonar.runner.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:67)
[sonar:sonar] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[sonar:sonar] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:498)
[sonar:sonar] 	at org.sonar.runner.impl.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:61)
[sonar:sonar] 	at com.sun.proxy.$Proxy2.execute(Unknown Source)
[sonar:sonar] 	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:274)
[sonar:sonar] 	at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:165)
[sonar:sonar] 	at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:152)
[sonar:sonar] 	at org.sonarsource.scanner.ant.SonarQubeTask.launchAnalysis(SonarQubeTask.java:72)
[sonar:sonar] 	at org.sonarsource.scanner.ant.SonarQubeTask.execute(SonarQubeTask.java:55)
[sonar:sonar] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[sonar:sonar] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:498)
[sonar:sonar] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[sonar:sonar] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[sonar:sonar] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[sonar:sonar] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[sonar:sonar] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[sonar:sonar] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
[sonar:sonar] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
[sonar:sonar] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[sonar:sonar] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:498)
[sonar:sonar] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[sonar:sonar] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[sonar:sonar] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[sonar:sonar] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
[sonar:sonar] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[sonar:sonar] 	at org.apache.tools.ant.Main.runBuild(Main.java:851)
[sonar:sonar] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
[sonar:sonar] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
[sonar:sonar] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
[sonar:sonar] Caused by: org.sonar.plugins.openedge.api.antlr.NoViableAltException: unexpected token: &1
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.parameter(ProParser.java:16861)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.method_param_list(ProParser.java:21102)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.attr_colon(ProParser.java:20179)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.exprt(ProParser.java:17023)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.unaryExpression(ProParser.java:20082)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.multiplicativeExpression(ProParser.java:19979)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.additiveExpression(ProParser.java:19921)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.relationalExpression(ProParser.java:19741)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.notExpression(ProParser.java:19707)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.andExpression(ProParser.java:19659)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.orExpression(ProParser.java:19621)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.expression(ProParser.java:2870)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.expression_statement(ProParser.java:1799)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:393)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.code_block(ProParser.java:450)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.procedurestate(ProParser.java:11725)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.statement(ProParser.java:2434)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:419)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.program(ProParser.java:150)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.DoParse.doParse(DoParse.java:172)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.DoParse.doParse(DoParse.java:101)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:145)
[sonar:sonar] 	... 61 common frames omitted
```

Stack of the second error:

```
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:148)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:177)
[sonar:sonar] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:109)
[sonar:sonar] 	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
[sonar:sonar] 	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
[sonar:sonar] 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
[sonar:sonar] 	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
[sonar:sonar] 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
[sonar:sonar] 	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
[sonar:sonar] 	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
[sonar:sonar] 	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
[sonar:sonar] 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
[sonar:sonar] 	at org.sonar.runner.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:67)
[sonar:sonar] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[sonar:sonar] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:498)
[sonar:sonar] 	at org.sonar.runner.impl.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:61)
[sonar:sonar] 	at com.sun.proxy.$Proxy2.execute(Unknown Source)
[sonar:sonar] 	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:274)
[sonar:sonar] 	at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:165)
[sonar:sonar] 	at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:152)
[sonar:sonar] 	at org.sonarsource.scanner.ant.SonarQubeTask.launchAnalysis(SonarQubeTask.java:72)
[sonar:sonar] 	at org.sonarsource.scanner.ant.SonarQubeTask.execute(SonarQubeTask.java:55)
[sonar:sonar] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[sonar:sonar] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:498)
[sonar:sonar] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[sonar:sonar] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[sonar:sonar] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[sonar:sonar] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[sonar:sonar] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[sonar:sonar] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
[sonar:sonar] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
[sonar:sonar] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[sonar:sonar] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:498)
[sonar:sonar] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[sonar:sonar] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[sonar:sonar] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[sonar:sonar] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
[sonar:sonar] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[sonar:sonar] 	at org.apache.tools.ant.Main.runBuild(Main.java:851)
[sonar:sonar] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
[sonar:sonar] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
[sonar:sonar] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
[sonar:sonar] Caused by: org.sonar.plugins.openedge.api.antlr.NoViableAltException: unexpected token: THEN
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.ifstate(ProParser.java:9494)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.statement(ProParser.java:2266)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:419)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.code_block(ProParser.java:450)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.functionstate(ProParser.java:8940)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.statement(ProParser.java:2231)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:419)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.program(ProParser.java:150)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.DoParse.doParse(DoParse.java:172)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.DoParse.doParse(DoParse.java:101)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:145)
[sonar:sonar] 	... 61 common frames omitted
```

**Comment by gquerret** [comment]
Given the stack trace, you're not using the latest version.
```
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:177)
[sonar:sonar] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:109)
```
In the latest version, line 109 doesn't execute method treeParser01 :: [See here](https://github.com/Riverside-Software/sonar-openedge/blob/fb0a98fdee7fde6e79a291e34fc77c36b30887dc/openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeProparseSensor.java#L109)
But that's the case in this older version: [See here](https://github.com/Riverside-Software/sonar-openedge/blob/e13c3a01cd9e46201fda2e07417c0e247e3fe4e7/openedge-plugin/src/main/java/org/sonar/plugins/openedge/sensor/OpenEdgeProparseSensor.java#L109)

Please use the latest 2.0.1 from the Releases page, and don't forget to also update your licence from https://ci.rssw.eu (if that wasn't already the case).

**Comment by movedoa** [comment]
Whoops, my bad, stupid copy paste error on my part, i will update an report back if this is fixed now

**Comment by movedoa** [comment]
fixed with 2.0.1

**Comment by movedoa** [comment]
Ok this is fixed on the server but still happens with the eclipse plugin. (Version 3.0.999)

```
org.sonar.plugins.openedge.api.org.prorefactor.refactor.RefactorException: C:\Entwicklung\OE11\Workspace116\B4730\prog\Common\System\StringTable\StringTable2.p:4308:251: unexpected token: &1
	at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:156) ~[na:na]
	at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:183) ~[na:na]
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:110) ~[na:na]
	at org.sonarsource.sonarlint.core.analyzer.sensor.SensorWrapper.analyse(SensorWrapper.java:52) [org.sonarsource.sonarlint.core.sonarlint-core_2.11.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.analyzer.sensor.SensorsExecutor.executeSensor(SensorsExecutor.java:75) [org.sonarsource.sonarlint.core.sonarlint-core_2.11.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.analyzer.sensor.SensorsExecutor.execute(SensorsExecutor.java:63) [org.sonarsource.sonarlint.core.sonarlint-core_2.11.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.analyzer.sensor.PhaseExecutor.execute(PhaseExecutor.java:44) [org.sonarsource.sonarlint.core.sonarlint-core_2.11.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.container.analysis.AnalysisContainer.doAfterStart(AnalysisContainer.java:143) [org.sonarsource.sonarlint.core.sonarlint-core_2.11.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.container.ComponentContainer.startComponents(ComponentContainer.java:125) [org.sonarsource.sonarlint.core.sonarlint-core_2.11.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.container.ComponentContainer.execute(ComponentContainer.java:110) [org.sonarsource.sonarlint.core.sonarlint-core_2.11.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.container.storage.StorageAnalyzer.analyze(StorageAnalyzer.java:72) [org.sonarsource.sonarlint.core.sonarlint-core_2.11.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.container.storage.StorageContainer.analyze(StorageContainer.java:126) [org.sonarsource.sonarlint.core.sonarlint-core_2.11.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.analyze(ConnectedSonarLintEngineImpl.java:158) [org.sonarsource.sonarlint.core.sonarlint-core_2.11.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.analyze(ConnectedSonarLintEngineImpl.java:145) [org.sonarsource.sonarlint.core.sonarlint-core_2.11.0.RSSW.jar:na]
	at org.sonarlint.eclipse.core.internal.server.Server.runAnalysis(Server.java:273) [org.sonarlint.eclipse.core_3.0.999.jar:na]
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.run(AnalyzeProjectJob.java:472) [org.sonarlint.eclipse.core_3.0.999.jar:na]
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob$AnalysisThread.run(AnalyzeProjectJob.java:125) [org.sonarlint.eclipse.core_3.0.999.jar:na]
Caused by: org.sonar.plugins.openedge.api.antlr.NoViableAltException: unexpected token: &1
	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.parameter(ProParser.java:16864) ~[na:na]
	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.method_param_list(ProParser.java:21105) ~[na:na]
	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.attr_colon(ProParser.java:20182) ~[na:na]
	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.exprt(ProParser.java:17026) ~[na:na]
	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.unaryExpression(ProParser.java:20085) ~[na:na]
	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.multiplicativeExpression(ProParser.java:19982) ~[na:na]
	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.additiveExpression(ProParser.java:19924) ~[na:na]
	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.relationalExpression(ProParser.java:19744) ~[na:na]
	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.notExpression(ProParser.java:19710) ~[na:na]
	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.andExpression(ProParser.java:19662) ~[na:na]
	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.orExpression(ProParser.java:19624) ~[na:na]
	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.expression(ProParser.java:2873) ~[na:na]
	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.expression_statement(ProParser.java:1802) ~[na:na]
	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:396) ~[na:na]
	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.code_block(ProParser.java:453) ~[na:na]
	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.procedurestate(ProParser.java:11728) ~[na:na]
	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.statement(ProParser.java:2437) ~[na:na]
	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:422) ~[na:na]
	at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.program(ProParser.java:154) ~[na:na]
	at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:145) ~[na:na]
	... 16 common frames omitted
```

**Comment by movedoa** [comment]
fixed by manually updating the project binding....is there a way to do this automatically or promt the user to do so?

**Comment by gquerret** [comment]
The Eclipse plugin works with the same version as the server (downloaded from the server side). You should download the latest bindings (right-click on your server in the "SonarQube servers" view)

**Comment by gquerret** [comment]
Nice, you just found it !
Eclipse prompts you when Sonar bindings are not up-to-date. It's a small pop-up windows in the bottom right corner. I'll check if there's another way to see if they are out of date.
