### ISSUE TITLE
Unexpected token: no-error

### ISSUE THREAD

**Issue by stroyer** [Riverside-Software/sonar-openedge#26]
The following code generates a proparse error.  This code compiles but I cannot find any doc indicting whether or not `no-error` is supported by the create query statement.

```
define variable qh as handle no-undo.
create query qh no-error.
```

```
INFO: Sensor OpenEdgeProparseSensor
ERROR: Error during code parsing for src/junk.p
org.sonar.plugins.openedge.api.org.prorefactor.refactor.RefactorException: C:\sonar-examples\projects\languages\toe2\src\junk.p:2:17: unexpe
cted token: no-error
        at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:219) ~[na:na]
        at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:248) ~[na:na]
        at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.analyse(OpenEdgeProparseSensor.java:111) ~[na:na]
        at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236) [sonar-scanner-engine-shaded-5.6.jar:na]

        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62) [sonar-scanner-api-batch4
129124597328948539.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60) [sonar-scanner-cli-2.6.1.jar:na]

        at com.sun.proxy.$Proxy0.execute(Unknown Source) [na:na]
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:240) [sonar-scanner-cli-2.6.1.jar:na]
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151) [sonar-scanner-cli-2.6.1.jar:na]
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110) [sonar-scanner-cli-2.6.1.jar:na]
        at org.sonarsource.scanner.cli.Main.execute(Main.java:72) [sonar-scanner-cli-2.6.1.jar:na]
        at org.sonarsource.scanner.cli.Main.main(Main.java:60) [sonar-scanner-cli-2.6.1.jar:na]
Caused by: org.sonar.plugins.openedge.api.antlr.NoViableAltException: unexpected token: no-error
        at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.createquerystate(ProParser.java:33626) ~[na:na]
        at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.createstatement(ProParser.java:6480) ~[na:na]
        at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.statement(ProParser.java:2107) ~[na:na]
        at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:428) ~[na:na]
        at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.program(ProParser.java:159) ~[na:na]
        at org.sonar.plugins.openedge.api.org.prorefactor.proparse.DoParse.doParse(DoParse.java:175) ~[na:na]
        at org.sonar.plugins.openedge.api.org.prorefactor.proparse.DoParse.doParse(DoParse.java:100) ~[na:na]
        at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:204) ~[na:na]
        ... 31 common frames omitted
```

**Comment by jakejustus** [comment]
Could you include the version number ?

**Comment by stroyer** [comment]
sonar openedge plugin 1.9.2 with sonarqube 5.6.  Riverside rules plugin 1.0.4.  Thanks.

**Comment by jakejustus** [comment]
Confirmed and reproduced

**Comment by jakejustus** [comment]
Fixed, will be available in next version.
