### ISSUE TITLE
Unknown field or variable name in Dataset Defintion

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#261]
The following class produces the error:

```
CLASS test:

   DEFINE TEMP-TABLE TempTable1 NO-UNDO
      FIELD Field1 AS INTEGER
      FIELD Field2 AS CHARACTER.

   DEFINE TEMP-TABLE TempTable2 NO-UNDO
   FIELD Foo1 AS RECID.

   DEFINE DATASET DataSet1
      FOR TempTable1, TempTable2
      PARENT-ID-RELATION RELATION1 FOR TempTable1, TempTable2
         PARENT-ID-FIELD Foo1
         PARENT-FIELDS-BEFORE (Field1)
         PARENT-FIELDS-AFTER (Field2).

END CLASS.
```

Stack:

```
org.prorefactor.refactor.RefactorException: org.prorefactor.treeparser.TreeParserException: C:\Entwicklung\OE11\Workspace116\B4730\test.cls:14 Unknown field or variable name: Field1
	at org.prorefactor.treeparser.ParseUnit.treeParser(ParseUnit.java:178) ~[proparse-1.0.14.jar:na]
	at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:193) ~[proparse-1.0.14.jar:na]
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:185) [sonar-openedge-plugin-2.0.1.jar:na]
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:136) [sonar-openedge-plugin-2.0.1.jar:na]
	at org.sonarsource.sonarlint.core.analyzer.sensor.SensorWrapper.analyse(SensorWrapper.java:52) [org.sonarsource.sonarlint.core.sonarlint-core_2.11.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.analyzer.sensor.SensorsExecutor.executeSensor(SensorsExecutor.java:75) [org.sonarsource.sonarlint.core.sonarlint-core_2.11.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.analyzer.sensor.SensorsExecutor.execute(SensorsExecutor.java:63) [org.sonarsource.sonarlint.core.sonarlint-core_2.11.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.analyzer.sensor.PhaseExecutor.execute(PhaseExecutor.java:44) [org.sonarsource.sonarlint.core.sonarlint-core_2.11.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.container.analysis.AnalysisContainer.doAfterStart(AnalysisContainer.java:143) [org.sonarsource.sonarlint.core.sonarlint-core_2.11.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.container.ComponentContainer.startComponents(ComponentContainer.java:125) [org.sonarsource.sonarlint.core.sonarlint-core_2.11.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.container.ComponentContainer.execute(ComponentContainer.java:110) [org.sonarsource.sonarlint.core.sonarlint-core_2.11.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.container.storage.StorageAnalyzer.analyze(StorageAnalyzer.java:72) [org.sonarsource.sonarlint.core.sonarlint-core_2.11.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.container.storage.StorageContainer.analyze(StorageContainer.java:126) [org.sonarsource.sonarlint.core.sonarlint-core_2.11.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.analyze(ConnectedSonarLintEngineImpl.java:158) [org.sonarsource.sonarlint.core.sonarlint-core_2.11.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.analyze(ConnectedSonarLintEngineImpl.java:145) [org.sonarsource.sonarlint.core.sonarlint-core_2.11.0.RSSW.jar:na]
	at org.sonarlint.eclipse.core.internal.server.Server.runAnalysis(Server.java:273) [org.sonarlint.eclipse.core_3.0.999.jar:na]
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.run(AnalyzeProjectJob.java:472) [org.sonarlint.eclipse.core_3.0.999.jar:na]
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob$AnalysisThread.run(AnalyzeProjectJob.java:125) [org.sonarlint.eclipse.core_3.0.999.jar:na]
Caused by: org.prorefactor.treeparser.TreeParserException: C:\Entwicklung\OE11\Workspace116\B4730\test.cls:14 Unknown field or variable name: Field1
	at org.prorefactor.treeparser01.TP01Support.field(TP01Support.java:567) ~[proparse-1.0.14.jar:na]
	at org.prorefactor.treeparser01.TreeParser01.fld1(TreeParser01.java:9086) ~[proparse-1.0.14.jar:na]
	at org.prorefactor.treeparser01.TreeParser01.parent_id_relation(TreeParser01.java:17440) ~[proparse-1.0.14.jar:na]
	at org.prorefactor.treeparser01.TreeParser01.definedatasetstate(TreeParser01.java:17185) ~[proparse-1.0.14.jar:na]
	at org.prorefactor.treeparser01.TreeParser01.statement(TreeParser01.java:35819) ~[proparse-1.0.14.jar:na]
	at org.prorefactor.treeparser01.TreeParser01.blockorstate(TreeParser01.java:279) ~[proparse-1.0.14.jar:na]
	at org.prorefactor.treeparser01.TreeParser01.code_block(TreeParser01.java:11841) ~[proparse-1.0.14.jar:na]
	at org.prorefactor.treeparser01.TreeParser01.classstate(TreeParser01.java:11788) ~[proparse-1.0.14.jar:na]
	at org.prorefactor.treeparser01.TreeParser01.statement(TreeParser01.java:35147) ~[proparse-1.0.14.jar:na]
	at org.prorefactor.treeparser01.TreeParser01.blockorstate(TreeParser01.java:279) ~[proparse-1.0.14.jar:na]
	at org.prorefactor.treeparser01.TreeParser01.program(TreeParser01.java:119) ~[proparse-1.0.14.jar:na]
	at org.prorefactor.treeparser.ParseUnit.treeParser(ParseUnit.java:176) ~[proparse-1.0.14.jar:na]
	... 17 common frames omitted
```

**Comment by samixchoumi** [comment]
Did PCT compile the code ?

**Comment by movedoa** [comment]
I just made this example in my DevStudio.
The real class is huge, i just stripped it down to the minimum to reproduce the error.
But why shouldn't PCT compile this code?
PCT just calls the progress compiler which can compile this class.

**Comment by samixchoumi** [comment]
I got an error like this and PCTCompile couldn't compile, after i changed the code, PTCompile worked fine and then the error disappeared

**Comment by movedoa** [comment]
This is no compile error, this is an error from the sonar parser

**Comment by gquerret** [comment]
Reproduced, fix is coming.

**Comment by gquerret** [comment]
Fixed in master
