### ISSUE TITLE
Unable to start plugin with SonarQube 6.4

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#275]
Stack trace in web.log:
```
java.lang.IllegalStateException: Fail to load plugin OpenEdge [openedge]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:73)
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:534)
	at org.sonar.server.platform.Platform.start(Platform.java:231)
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:205)
	at org.sonar.server.platform.Platform.access$500(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:391)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:375)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/web/CodeColorizerFormat
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	at org.sonar.plugins.openedge.OpenEdgePlugin.define(OpenEdgePlugin.java:62)
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:63)
	... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.web.CodeColorizerFormat
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
```

**Comment by gquerret** [comment]
Code colorization mechanism depends on a class which was deprecated some time ago, and which has been completely removed in 6.4.
Upgrade will be done ASAP

**Comment by gquerret** [comment]
Temporary fix available in master (syntax highlight disabled)

**Comment by gquerret** [comment]
New highlighting mechanism introduced in master
