### ISSUE TITLE
Auditing not being enabled on database used for analysis

### ISSUE THREAD

**Issue by hdaum** [Riverside-Software/sonar-openedge#29]
It's possible I missed the setting that enables this but we need a way to enable auditing on the DB used for analysis as our code base references these tables.

Typical error I am seeing in my output.

```
org.sonar.plugins.openedge.api.org.prorefactor.refactor.RefactorException:  D:\Progress\Trunk\ttDefinitions\ttTableDef.i:9: Unknown table name: _aud-audit-data
        at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:219) ~[na:na]
        at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:248) ~[na:na]
        at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.analyse(OpenEdgeProparseSensor.java:111) ~[na:na]
        at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62) [sonar-scanner-api-batch5285526640578351886.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_74]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_74]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_74]
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60) [sonar-scanner-cli-2.6.1.jar:na]
        at com.sun.proxy.$Proxy0.execute(Unknown Source) [na:na]
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:240) [sonar-scanner-cli-2.6.1.jar:na]
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151) [sonar-scanner-cli-2.6.1.jar:na]
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110) [sonar-scanner-cli-2.6.1.jar:na]
        at org.sonarsource.scanner.cli.Main.execute(Main.java:72) [sonar-scanner-cli-2.6.1.jar:na]
        at org.sonarsource.scanner.cli.Main.main(Main.java:60) [sonar-scanner-cli-2.6.1.jar:na]
Caused by: org.sonar.plugins.openedge.api.antlr.SemanticException: D:\Progress\Trunk\ttDefinitions\ttTableDef.i:9: Unknown table name: _aud-audit-data
        at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.record(ProParser.java:3213) ~[na:na]
        at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.def_table_like(ProParser.java:40805) ~[na:na]
        at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.definetemptablestate(ProParser.java:37291)~[na:na]
        at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.definestatement(ProParser.java:7400) ~[na:na]
        at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.statement(ProParser.java:2121) ~[na:na]
        at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:428) ~[na:na]
        at org.sonar.plugins.openedge.api.org.prorefactor.proparse.ProParser.program(ProParser.java:159) ~[na:na]
        at org.sonar.plugins.openedge.api.org.prorefactor.proparse.DoParse.doParse(DoParse.java:175) ~[na:na]
        at org.sonar.plugins.openedge.api.org.prorefactor.proparse.DoParse.doParse(DoParse.java:100) ~[na:na]
        at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:204) ~[na:na]
        ... 31 common frames omitted
```

**Comment by jakejustus** [comment]
You're right, there's no setting to "enable" auditing. The database schema is populated from the DF files, then metaschema is automatically added. The current version of the metaschema doesn't include audit tables, that will be done in next version.

**Comment by gquerret** [comment]
Fixed in dev
