### ISSUE TITLE
Unable to start SonarQube with OpenEdge and rules plugins

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#316]
Only on SonarQube 6.4 fresh install, and with openedge plugin and rules plugin installed **at the same time**.
Stack trace in web.log:
```
2017.07.31 09:32:27 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "ACTIVE_RULES_UNIQUE ON PUBLIC.ACTIVE_RULES(PROFILE_ID, RULE_ID) VALUES ( /* key:815 */ null, 11, 1285, null, null, null, null)"; SQL statement:
INSERT INTO active_rules (profile_id, rule_id, failure_level, inheritance, created_at, updated_at)
    VALUES (?, ?, ?, ?, ?, ?) [23505-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:103)
	at org.h2.index.PageBtree.find(PageBtree.java:121)
	at org.h2.index.PageBtreeLeaf.addRow(PageBtreeLeaf.java:151)
	at org.h2.index.PageBtreeLeaf.addRowTry(PageBtreeLeaf.java:104)
	at org.h2.index.PageBtreeNode.addRowTry(PageBtreeNode.java:206)
	at org.h2.index.PageBtreeIndex.addRow(PageBtreeIndex.java:97)
	at org.h2.index.PageBtreeIndex.add(PageBtreeIndex.java:88)
	at org.h2.table.RegularTable.addRow(RegularTable.java:120)
	at org.h2.command.dml.Insert.insertRows(Insert.java:157)
	at org.h2.command.dml.Insert.update(Insert.java:115)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.server.TcpServerThread.process(TcpServerThread.java:346)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:160)
	at java.lang.Thread.run(Unknown Source)

### The error may involve org.sonar.db.qualityprofile.ActiveRuleMapper.insert-Inline
### The error occurred while setting parameters
### Cause: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "ACTIVE_RULES_UNIQUE ON PUBLIC.ACTIVE_RULES(PROFILE_ID, RULE_ID) VALUES ( /* key:815 */ null, 11, 1285, null, null, null, null)"; SQL statement:
INSERT INTO active_rules (profile_id, rule_id, failure_level, inheritance, created_at, updated_at)
    VALUES (?, ?, ?, ?, ?, ?) [23505-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)
	at org.h2.index.BaseIndex.getDuplicateKeyException(BaseIndex.java:103)
	at org.h2.index.PageBtree.find(PageBtree.java:121)
	at org.h2.index.PageBtreeLeaf.addRow(PageBtreeLeaf.java:151)
	at org.h2.index.PageBtreeLeaf.addRowTry(PageBtreeLeaf.java:104)
	at org.h2.index.PageBtreeNode.addRowTry(PageBtreeNode.java:206)
	at org.h2.index.PageBtreeIndex.addRow(PageBtreeIndex.java:97)
	at org.h2.index.PageBtreeIndex.add(PageBtreeIndex.java:88)
	at org.h2.table.RegularTable.addRow(RegularTable.java:120)
	at org.h2.command.dml.Insert.insertRows(Insert.java:157)
	at org.h2.command.dml.Insert.update(Insert.java:115)
	at org.h2.command.CommandContainer.update(CommandContainer.java:79)
	at org.h2.command.Command.executeUpdate(Command.java:254)
	at org.h2.server.TcpServerThread.process(TcpServerThread.java:346)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:160)
	at java.lang.Thread.run(Unknown Source)

	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:154)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:141)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:51)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at com.sun.proxy.$Proxy54.insert(Unknown Source)
	at org.sonar.db.qualityprofile.ActiveRuleDao.insert(ActiveRuleDao.java:85)
	at org.sonar.server.qualityprofile.RuleActivator.doInsert(RuleActivator.java:274)
	at org.sonar.server.qualityprofile.RuleActivator.persist(RuleActivator.java:247)
	at org.sonar.server.qualityprofile.RuleActivator.doActivate(RuleActivator.java:135)
	at org.sonar.server.qualityprofile.RuleActivator.activate(RuleActivator.java:87)
	at org.sonar.server.qualityprofile.DefinedQProfileCreationImpl.create(DefinedQProfileCreationImpl.java:54)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.registerPerQualityProfileAndOrganization(RegisterQualityProfiles.java:92)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.lambda$registerPerQualityProfile$2(RegisterQualityProfiles.java:80)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.registerPerQualityProfile(RegisterQualityProfiles.java:80)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.lambda$registerPerLanguage$1(RegisterQualityProfiles.java:71)
	at java.lang.Iterable.forEach(Unknown Source)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.registerPerLanguage(RegisterQualityProfiles.java:71)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.lambda$start$0(RegisterQualityProfiles.java:64)
	at java.lang.Iterable.forEach(Unknown Source)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.start(RegisterQualityProfiles.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110)
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89)
	at org.sonar.core.platform.ComponentContainer$1.start(ComponentContainer.java:320)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:88)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:44)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:82)
	at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:45)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:79)
	at org.sonar.server.platform.Platform.executeStartupTasks(Platform.java:216)
	at org.sonar.server.platform.Platform.access$400(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$1(Platform.java:121)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:391)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:121)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:375)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "ACTIVE_RULES_UNIQUE ON PUBLIC.ACTIVE_RULES(PROFILE_ID, RULE_ID) VALUES ( /* key:815 */ null, 11, 1285, null, null, null, null)"; SQL statement:
INSERT INTO active_rules (profile_id, rule_id, failure_level, inheritance, created_at, updated_at)
    VALUES (?, ?, ?, ?, ?, ?) [23505-176]
	at org.h2.engine.SessionRemote.done(SessionRemote.java:606)
	at org.h2.command.CommandRemote.executeUpdate(CommandRemote.java:192)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:199)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:44)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:69)
	at org.apache.ibatis.executor.ReuseExecutor.doUpdate(ReuseExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:105)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:71)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:152)
	... 47 common frames omitted
2017.07.31 09:32:27 INFO  web[][o.s.p.StopWatcher] Stopping process
2017.07.31 09:32:28 INFO  web[][o.s.s.n.NotificationDaemon] Notification service stopped
2017.07.31 09:32:29 INFO  web[][o.s.s.p.d.EmbeddedDatabase] Embedded database stopped
```

**Comment by gquerret** [comment]
Rules plugin fixed
