### ISSUE TITLE
unexpected token: CAN-FIND with protected buffer in base class

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#334]
Version 2.1.0

I have a protected BUFFER in my ABSTRACT base class
`DEFINE PROTECTED BUFFER bAdrCus FOR AdrCus.`

In the class that inherits this base class i have the following method which triggers the error:
```
 METHOD PRIVATE LOGICAL IsRecordAlreadyDeleted(
      piAdrNbr AS INTEGER,
      plShowMessage AS LOGICAL
   ):
      IF NOT CAN-FIND(
         FIRST bAdrCus WHERE
            bAdrCus.AdrNbr = piAdrNbr
         NO-LOCK
      )
      THEN DO:
         IF plShowMessage = TRUE THEN DO:
            CLS.IssMessage:DisplayIssInfo(CLS.IssMessage:IssMsgCode("MSG101761":U)). 
         END.

         RETURN TRUE.
      END.

      RETURN FALSE.
   END METHOD.
```

```
[sonar:sonar] Error during code parsing for Web/Views/Easy/Expert/CrmSys/CustomerModel.cls
[sonar:sonar] org.prorefactor.refactor.RefactorException: C:\Buildtools\Jenkins\workspace\Sonar_Runner_117\Web\Views\Easy\Expert\CrmSys\CustomerModel.cls:272:14: unexpected token: CAN-FIND
[sonar:sonar] 	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:154)
[sonar:sonar] 	at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:181)
[sonar:sonar] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:197)
[sonar:sonar] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:141)
[sonar:sonar] 	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
[sonar:sonar] 	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
[sonar:sonar] 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
[sonar:sonar] 	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
[sonar:sonar] 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:175)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:262)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:247)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
[sonar:sonar] 	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
[sonar:sonar] 	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:128)
[sonar:sonar] 	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
[sonar:sonar] 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
[sonar:sonar] 	at org.sonar.runner.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:67)
[sonar:sonar] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[sonar:sonar] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:498)
[sonar:sonar] 	at org.sonar.runner.impl.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:61)
[sonar:sonar] 	at com.sun.proxy.$Proxy2.execute(Unknown Source)
[sonar:sonar] 	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:274)
[sonar:sonar] 	at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:165)
[sonar:sonar] 	at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:152)
[sonar:sonar] 	at org.sonarsource.scanner.ant.SonarQubeTask.launchAnalysis(SonarQubeTask.java:72)
[sonar:sonar] 	at org.sonarsource.scanner.ant.SonarQubeTask.execute(SonarQubeTask.java:55)
[sonar:sonar] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[sonar:sonar] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:498)
[sonar:sonar] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[sonar:sonar] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[sonar:sonar] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[sonar:sonar] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[sonar:sonar] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[sonar:sonar] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
[sonar:sonar] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
[sonar:sonar] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[sonar:sonar] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:498)
[sonar:sonar] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[sonar:sonar] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[sonar:sonar] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[sonar:sonar] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
[sonar:sonar] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[sonar:sonar] 	at org.apache.tools.ant.Main.runBuild(Main.java:851)
[sonar:sonar] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
[sonar:sonar] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
[sonar:sonar] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
[sonar:sonar] Caused by: antlr.NoViableAltException: unexpected token: CAN-FIND
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.exprt2(ProParser.java:20914)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.exprt(ProParser.java:17060)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.unaryExpression(ProParser.java:20300)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.multiplicativeExpression(ProParser.java:20197)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.additiveExpression(ProParser.java:20139)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.relationalExpression(ProParser.java:19959)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.notExpression(ProParser.java:19920)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.andExpression(ProParser.java:19877)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.orExpression(ProParser.java:19839)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.expression(ProParser.java:2873)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.ifstate(ProParser.java:9426)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.statement(ProParser.java:2269)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:422)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.code_block(ProParser.java:453)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.methodstate(ProParser.java:10333)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.statement(ProParser.java:2332)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:422)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.code_block(ProParser.java:453)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.classstate(ProParser.java:5645)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.statement(ProParser.java:2038)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:422)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.program(ProParser.java:154)
[sonar:sonar] 	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:143)
[sonar:sonar] 	... 62 common frames omitted
```

**Comment by gquerret** [comment]
From the log output, it seems to be in SonarRunner, not in SonarLint. Did you pass the sonar.oe.binaries property to the process ?

**Comment by movedoa** [comment]
Yes, and it seems the import is running just fine

> [sonar:sonar] 3714 RCode read in 1510 ms - 1259 classes - 14958 methods - 3155 properties

**Comment by movedoa** [comment]
I just checked and i have exactly 3714 *.r files in my build folder, so it seems all rcodes get read withouth problems

**Comment by gquerret** [comment]
Fixed in master

**Comment by movedoa** [comment]
works with current master build, thx

**Comment by gquerret** [comment]
Thanks, and please report any other similar issue you can find, the way table / buffer names are resolved now is quite a big change.

**Comment by movedoa** [comment]
The complete build runs without any error messages at the moment (for the first time ever btw. great work)
I will keep my eyes open
