### ISSUE TITLE
preprocessor with dbtype and something: Unknown datatype passed to getBool

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#372]
````
DEFINE TEMP-TABLE tt  NO-UNDO
   FIELD cc AS CHARACTER.

FIND LAST tt
   &IF "{1}" BEGINS "abc" AND DBTYPE( 1 ) = "ORACLE" &THEN
      WHERE tt.cc = tt.cc
   &ENDIF
NO-ERROR.

RETURN "0"
````
If the preprocess condition is only dbtype( 1 ) = "oracle" then the issue does not occur.

````
[sonar:sonar] Sensor OpenEdgeProparseSensor [openedge]
[sonar:sonar] Runtime exception was caught - Please report this issue : 
[sonar:sonar] org.prorefactor.proparse.antlr4.ProEvalException: Unknown datatype passed to getBool
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.PreproEval.getBool(PreproEval.java:521)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.PreproEval.visitAndOr(PreproEval.java:86)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.PreprocessorParser$AndOrContext.accept(PreprocessorParser.java:603)
[sonar:sonar] 	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.PreproEval.visitPreproIfEval(PreproEval.java:75)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.PostLexer.preproIfCond(PostLexer.java:261)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.PostLexer.preproIf(PostLexer.java:154)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.PostLexer.nextToken(PostLexer.java:61)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.PostLexer.nextToken(PostLexer.java:34)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.TokenList.build(TokenList.java:57)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.TokenList.nextToken(TokenList.java:153)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.MultiChannelTokenSource.nextToken(MultiChannelTokenSource.java:43)
[sonar:sonar] 	at org.prorefactor.proparse.antlr4.ProgressLexer$ANTRL2TokenStreamWrapper.nextToken(ProgressLexer.java:1055)
[sonar:sonar] 	at antlr.TokenStreamHiddenTokenFilter.consume(TokenStreamHiddenTokenFilter.java:38)
[sonar:sonar] 	at antlr.TokenStreamHiddenTokenFilter.consumeFirst(TokenStreamHiddenTokenFilter.java:42)
[sonar:sonar] 	at antlr.TokenStreamHiddenTokenFilter.nextToken(TokenStreamHiddenTokenFilter.java:122)
[sonar:sonar] 	at antlr.TokenBuffer.fill(TokenBuffer.java:69)
[sonar:sonar] 	at antlr.TokenBuffer.LT(TokenBuffer.java:86)
[sonar:sonar] 	at antlr.LLkParser.LT(LLkParser.java:56)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.traceIn(ProParser.java:52)
[sonar:sonar] 	at org.prorefactor.proparse.ProParser.program(ProParser.java:142)
[sonar:sonar] 	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:159)
[sonar:sonar] 	at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:197)
[sonar:sonar] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:224)
[sonar:sonar] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:147)
[sonar:sonar] 	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
[sonar:sonar] 	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
[sonar:sonar] 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
[sonar:sonar] 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
[sonar:sonar] 	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
[sonar:sonar] 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:179)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:261)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:256)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:245)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
[sonar:sonar] 	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
[sonar:sonar] 	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
[sonar:sonar] 	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:119)
[sonar:sonar] 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
[sonar:sonar] 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
[sonar:sonar] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[sonar:sonar] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:498)
[sonar:sonar] 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
[sonar:sonar] 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
[sonar:sonar] 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
[sonar:sonar] 	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
[sonar:sonar] 	at org.sonarsource.scanner.ant.SonarQubeTask.launchAnalysis(SonarQubeTask.java:99)
[sonar:sonar] 	at org.sonarsource.scanner.ant.SonarQubeTask.execute(SonarQubeTask.java:81)
[sonar:sonar] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[sonar:sonar] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:498)
[sonar:sonar] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[sonar:sonar] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[sonar:sonar] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[sonar:sonar] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
[sonar:sonar] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[sonar:sonar] 	at org.eclipse.ant.internal.launching.remote.EclipseDefaultExecutor.executeTargets(EclipseDefaultExecutor.java:36)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
[sonar:sonar] 	at org.eclipse.ant.internal.launching.remote.InternalAntRunner.run(InternalAntRunner.java:453)
[sonar:sonar] 	at org.eclipse.ant.internal.launching.remote.InternalAntRunner.main(InternalAntRunner.java:140)
````

Work-around is to nest the conditions (and potentially duplicate code):

````
DEFINE TEMP-TABLE tt  NO-UNDO
   FIELD cc AS CHARACTER.

FIND LAST tt
   &IF "{1}" BEGINS "abc" &THEN
      &IF DBTYPE( 1 ) = "ORACLE" &THEN
         WHERE tt.cc = tt.cc
      &ENDIF
   &ELSEIF DBTYPE( 2 ) = "ORACLE" &THEN
         WHERE tt.cc = tt.cc
   &ENDIF
NO-ERROR.

RETURN "0":u.
````

**Comment by gquerret** [comment]
Yes, the DBTYPE preprocessor function is not implemented. An empty implementation will be added in next version (or with output controlled by a property) so that it doesn't crash the parser.
However, please don't include work-around for the parser, I think it's better to have a parser failure and rant here to have it fixed than having weird syntax in your source code just for the parser. Not all issues will be fixed, especially the ones (left to the appreciation of the maintainers) where the compiler should never have accepted that. DBTYPE is not one of them!

**Comment by gquerret** [comment]
Fixed in master
