### ISSUE TITLE
NullPointerException in PublicVariable rule reported as license error

### ISSUE THREAD

**Issue by hdaum** [Riverside-Software/sonar-openedge#39]
Getting the following when using the latest riverside rules jar.

INFO: No licence found or invalid signature
java.lang.NullPointerException: null

**Comment by gquerret** [comment]
Do you have a stack trace ? Would you be able to run the analysis with the verbose switch ?

**Comment by hdaum** [comment]
Not all of the errors had a stack trace but here is one that did. 

INFO: No licence found or invalid signature 
java.lang.NullPointerException: null
        at eu.rssw.antlr.proparse.checks.PublicVariable.a(Unknown Source) ~[riverside-rules-plugin-1.0.6.jar:na]
        at org.sonar.plugins.openedge.c.lint(Unknown Source) [riverside-rules-plugin-1.0.6.jar:na]
        at org.sonar.plugins.openedge.api.checks.AbstractLintRule.execute(AbstractLintRule.java:32) [openedge-checks-sha
ded-1.3.6.jar:na]
        at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.analyse(OpenEdgeProparseSensor.java:157) [sonar-open
edge-plugin-1.9.3.jar:na]
        at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58) [sonar-scanner-engine-shaded-5.
6.jar:na]
        at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50) [sonar-scanner-engine-shaded-5.6.jar:
na]
        at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83) [sonar-scanner-engine-sha
ded-5.6.jar:na]
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192) [sonar-scanner-engine-sha
ded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine
-shaded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-
5.6.jar:na]
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241) [sonar-scanner-engine-shaded-5.
6.jar:na]
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236) [sonar-scanner-engin
e-shaded-5.6.jar:na]
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226) [sonar-scanner-engine-s
haded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine
-shaded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-
5.6.jar:na]
        at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86) [sonar-scanner-engine-shaded-5.6.jar:n
a]
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142) [sonar-scanner-engine
-shaded-5.6.jar:na]
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127) [sonar-scanner-engine-shaded-
5.6.jar:na]
        at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106) [sonar-scanner-engine-shaded-
5.6.jar:na]
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119) [sonar-scanner-engine-shaded-5.6.jar:na]
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62) [sona
r-scanner-api-batch3556126556547322862.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_74]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_74]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_74]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_74]
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60) [sonar-scann
er-cli-2.6.1.jar:na]
        at com.sun.proxy.$Proxy0.execute(Unknown Source) [na:na]
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:240) [sonar-scanner-cli-2.6.1.jar:
na]
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151) [sonar-scanner-cli-2.6.1.ja
r:na]
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110) [sonar-scanner-cli-2.6.1.jar:na]
        at org.sonarsource.scanner.cli.Main.execute(Main.java:72) [sonar-scanner-cli-2.6.1.jar:na]
        at org.sonarsource.scanner.cli.Main.main(Main.java:60) [sonar-scanner-cli-2.6.1.jar:na]

**Comment by hdaum** [comment]
I should also mention that even though I am getting this in my log the rules appear to still be running correctly.

**Comment by gquerret** [comment]
The NPE comes from the rule, and is mistakenly reported as a licence error by the engine. So two issues here, first one is the NPE which has to be fixed, the second one is the wrong error message.
I'll update the issue.

**Comment by gquerret** [comment]
Both NPE and error message were fixed.
