### ISSUE TITLE
Parsing fails for DEFINE BUFFER FOR TEMP-TABLE with the same name as table name in db

### ISSUE THREAD

**Issue by laumingis** [Riverside-Software/sonar-openedge#403]
I seem to be struck by some old issue: http://www.oehive.org/node/1856

In my case there is both table in db and temp-table defined with the same name _list_.
`DEFINE BUFFER blist FOR TEMP-TABLE list.` parsing fails with the following stacktrace:
```
[sonar:sonar] org.prorefactor.refactor.RefactorException: org.prorefactor.treeparser.TreeParserException: /tmp/myfile.w:101 Storetype mismatch between proparse.dll and treeparser01: list 1103 1102
[sonar:sonar] 	at org.prorefactor.treeparser.ParseUnit.treeParser(ParseUnit.java:186)
[sonar:sonar] 	at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:201)
[sonar:sonar] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:226)
[sonar:sonar] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:148)
[sonar:sonar] 	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
[sonar:sonar] 	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:87)
[sonar:sonar] 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:81)
[sonar:sonar] 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:67)
[sonar:sonar] 	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:75)
[sonar:sonar] 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:178)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:259)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:254)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:243)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
[sonar:sonar] 	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
[sonar:sonar] 	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
[sonar:sonar] 	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
[sonar:sonar] 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
[sonar:sonar] 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
[sonar:sonar] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[sonar:sonar] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:497)
[sonar:sonar] 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
[sonar:sonar] 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
[sonar:sonar] 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
[sonar:sonar] 	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
[sonar:sonar] 	at org.sonarsource.scanner.ant.SonarQubeTask.launchAnalysis(SonarQubeTask.java:99)
[sonar:sonar] 	at org.sonarsource.scanner.ant.SonarQubeTask.execute(SonarQubeTask.java:81)
[sonar:sonar] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[sonar:sonar] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:497)
[sonar:sonar] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[sonar:sonar] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[sonar:sonar] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[sonar:sonar] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
[sonar:sonar] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
[sonar:sonar] 	at org.apache.tools.ant.Main.runBuild(Main.java:853)
[sonar:sonar] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
[sonar:sonar] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
[sonar:sonar] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
[sonar:sonar] Caused by: org.prorefactor.treeparser.TreeParserException: /tmp/myfile.w:101 Storetype mismatch between proparse.dll and treeparser01: list 1103 1102
[sonar:sonar] 	at org.prorefactor.treeparser01.TP01Support.recordNodeSymbol(TP01Support.java:943)
[sonar:sonar] 	at org.prorefactor.treeparser01.TP01Support.recordNameNode(TP01Support.java:985)
[sonar:sonar] 	at org.prorefactor.treeparser01.TreeParser01.tbl(TreeParser01.java:432)
[sonar:sonar] 	at org.prorefactor.treeparser01.TreeParser01.definebufferstate(TreeParser01.java:15891)
[sonar:sonar] 	at org.prorefactor.treeparser01.TreeParser01.statement(TreeParser01.java:35784)
[sonar:sonar] 	at org.prorefactor.treeparser01.TreeParser01.blockorstate(TreeParser01.java:275)
[sonar:sonar] 	at org.prorefactor.treeparser01.TreeParser01.program(TreeParser01.java:115)
[sonar:sonar] 	at org.prorefactor.treeparser.ParseUnit.treeParser(ParseUnit.java:184)
[sonar:sonar] 	... 49 common frames omitted
```

**Comment by gquerret** [comment]
Same issue has been reported privately 2 days ago, but without a test case... Glad you included it !

**Comment by gquerret** [comment]
Also reproduced with `DEFINE TEMP-TABLE xxx FOR db.xxx`

**Comment by gquerret** [comment]
Fixed in master
