### ISSUE TITLE
Problem highlighting file

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#407]
On behalf of HL

Getting NPE when highlighting a simple include file:
```
     [java] ERROR: Unable to lex file src/...
     [java] java.lang.NullPointerException: null
     [java] 	at org.prorefactor.proparse.antlr4.TokenList.reviewObjcolon(TokenList.java:102)
     [java] 	at org.prorefactor.proparse.antlr4.TokenList.fillHeap(TokenList.java:84)
     [java] 	at org.prorefactor.proparse.antlr4.TokenList.nextToken(TokenList.java:164)
     [java] 	at org.prorefactor.proparse.antlr4.MultiChannelTokenSource.nextToken(MultiChannelTokenSource.java:43)
     [java] 	at org.prorefactor.proparse.antlr4.FunctionKeywordTokenFilter.nextToken(FunctionKeywordTokenFilter.java:44)
     [java] 	at org.prorefactor.proparse.antlr4.ProgressLexer$ANTRL2TokenStreamWrapper.nextToken(ProgressLexer.java:1066)
     [java] 	at org.sonar.plugins.openedge.sensor.OpenEdgeCodeColorizer.highlightFile(OpenEdgeCodeColorizer.java:84)
     [java] 	at org.sonar.plugins.openedge.sensor.OpenEdgeCodeColorizer.execute(OpenEdgeCodeColorizer.java:71)
     [java] 	...
```

File content:
```
/* Comment */
{&procedure-handle}:file-name + "_":U + string({&procedure-handle})
```

**Comment by gquerret** [comment]
Fixed in master
