### ISSUE TITLE
Multiple preprocessor errors without details

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#423]
On behalf of RE

Log file is filled with preprocessor messages:
```
21:34:29.715 ERROR - Runtime exception was caught - Please report this issue : 
java.lang.IllegalArgumentException: Line 573 - Unexpected end of input when consuming discarded &IF/&ELSEIF/&ELSE text
  at org.prorefactor.proparse.antlr4.PostLexer.throwMessage(PostLexer.java:267)
  at org.prorefactor.proparse.antlr4.PostLexer.preproconsume(PostLexer.java:134)
  at org.prorefactor.proparse.antlr4.PostLexer.preproIf(PostLexer.java:161)
  at org.prorefactor.proparse.antlr4.PostLexer.preproconsume(PostLexer.java:122)
  at org.prorefactor.proparse.antlr4.PostLexer.preproIf(PostLexer.java:161)
```

But no details about file name, why the problem occured or the line number.

**Comment by gquerret** [comment]
Fixed in master
