### ISSUE TITLE
Preprocessor error when discarding tokens

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#427]
On behalf of RE

Works correctly:
```
&IF TRUE &THEN &SCOPED-DEFINED XX YY ~n &ENDIF
```

Throws an exception:
```
&IF FALSE &THEN &SCOPED-DEFINED XX YY ~n &ENDIF
```

Stack trace:
```
     [java] org.prorefactor.core.ProparseRuntimeException: File 'test.p' - Current position 'test.p':64 - Unexpected end of input when consuming discarded &IF/&ELSEIF/&ELSE text
     [java]     at org.prorefactor.proparse.antlr4.PostLexer.throwMessage(PostLexer.java:262)
     [java]     at org.prorefactor.proparse.antlr4.PostLexer.preproconsume(PostLexer.java:127)
     [java]     at org.prorefactor.proparse.antlr4.PostLexer.preproIf(PostLexer.java:154)
     [java]     at org.prorefactor.proparse.antlr4.PostLexer.nextToken(PostLexer.java:57)
     [java]     at org.prorefactor.proparse.antlr4.PostLexer.nextToken(PostLexer.java:31)
     [java]     at org.prorefactor.proparse.antlr4.TokenList.fillHeap(TokenList.java:88)
     [java]     at org.prorefactor.proparse.antlr4.TokenList.nextToken(TokenList.java:164)
     [java]     at org.prorefactor.proparse.antlr4.MultiChannelTokenSource.nextToken(MultiChannelTokenSource.java:43)
     [java]     at org.prorefactor.proparse.antlr4.FunctionKeywordTokenFilter.nextToken(FunctionKeywordTokenFilter.java:44)
     [java]     at org.prorefactor.proparse.antlr4.ProgressLexer$ANTRL2TokenStreamWrapper.nextToken(ProgressLexer.java:1075)
     [java]     at antlr.TokenStreamHiddenTokenFilter.consume(TokenStreamHiddenTokenFilter.java:38)
     [java]     at antlr.TokenStreamHiddenTokenFilter.consumeFirst(TokenStreamHiddenTokenFilter.java:42)
     [java]     at antlr.TokenStreamHiddenTokenFilter.nextToken(TokenStreamHiddenTokenFilter.java:122)
     [java]     at antlr.TokenBuffer.fill(TokenBuffer.java:69)
     [java]     at antlr.TokenBuffer.LA(TokenBuffer.java:80)
     [java]     at antlr.LLkParser.LA(LLkParser.java:52)
     [java]     at org.prorefactor.proparse.ProParser.program(ProParser.java:132)
     [java]     at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:174)
     [java]     at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:204)
     [java]     at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:231)
```

Seems `~n` isn't escaped when *discarding* tokens

**Comment by gquerret** [comment]
Fixed in master
