### ISSUE TITLE
Unable to execute analysis due to profiler issue

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#490]
On behalf of KH

Analysis stops with this stack trace:
```
16:30:21.797 DEBUG: Checking directory C:\Latest\Profiler for *.out files
16:30:21.804 DEBUG: Parsing profiler output C:\Latest\Profiler\xxxx.out
16:30:21.885 INFO: ------------------------------------------------------------------------
16:30:21.887 INFO: EXECUTION FAILURE
16:30:21.887 INFO: ------------------------------------------------------------------------
16:30:21.888 INFO: Total time: 5.071s
16:30:21.953 INFO: Final Memory: 50M/320M
16:30:21.955 INFO: ------------------------------------------------------------------------
16:30:21.955 ERROR: Error during SonarQube Scanner execution
java.lang.ArrayIndexOutOfBoundsException: 118
        at eu.rssw.antlr.profiler.ProfilerSession.addCall(ProfilerSession.java:65)
        at eu.rssw.antlr.profiler.ProfilerSessionVisitor.visitCall_tree_data_line(ProfilerSessionVisitor.java:61)
        at eu.rssw.antlr.profiler.ProfilerSessionVisitor.visitCall_tree_data_line(ProfilerSessionVisitor.java:15)
        at eu.rssw.antlr.profiler.ProfilerGrammarParser$Call_tree_data_lineContext.accept(ProfilerGrammarParser.java:405)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at eu.rssw.antlr.profiler.ProfilerSessionVisitor.visitCall_tree_data(ProfilerSessionVisitor.java:56)
        at eu.rssw.antlr.profiler.ProfilerSessionVisitor.visitCall_tree_data(ProfilerSessionVisitor.java:15)
        at eu.rssw.antlr.profiler.ProfilerGrammarParser$Call_tree_dataContext.accept(ProfilerGrammarParser.java:346)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at eu.rssw.antlr.profiler.ProfilerGrammarBaseVisitor.visitProfiler(ProfilerGrammarBaseVisitor.java:20)
        at eu.rssw.antlr.profiler.ProfilerGrammarParser$ProfilerContext.accept(ProfilerGrammarParser.java:118)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at eu.rssw.antlr.profiler.ProfilerUtils.getProfilerSession(ProfilerUtils.java:42)
        at eu.rssw.antlr.profiler.ProfilerUtils.getProfilerSession(ProfilerUtils.java:32)
        at org.sonar.plugins.openedge.ProfilerCoverageSensor.a(Unknown Source)
        at org.sonar.plugins.openedge.ProfilerCoverageSensor.execute(Unknown Source)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:288)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:283)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:261)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
        at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

Profiler file sent offline

**Comment by gquerret** [comment]
Fixed in upcoming 2.1.5
