### ISSUE TITLE
SonarLint error with temp-table in base class

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#498]
Analyzing Class2 produces the attached error in SonarLint.
This only happens in SonarLint, the analysis runs fine on the server.

```
CLASS Class1:
   DEFINE PROTECTED STATIC TEMP-TABLE ttFoo NO-UNDO
      FIELD Foo1 AS CHARACTER.
END CLASS.
```

```
CLASS Class2 INHERITS Class1:
   METHOD PUBLIC VOID Foo(
   ):
      DEFINE BUFFER lbFoof FOR ttFoo.
   END METHOD.
END CLASS.
```

```
Error during code parsing for [path=C:\Entwicklung\OE11\Workspace117\B4830\prog\Iss\Class2.cls] at position null:-1:-1
antlr.SemanticException: prog/Iss/Class2.cls:5: Unknown table name: ttFoo
	at org.prorefactor.proparse.ProParser.record(ProParser.java:3002) ~[proparse-2.1.5.1.jar:na]
	at org.prorefactor.proparse.ProParser.definebufferstate(ProParser.java:34147) ~[proparse-2.1.5.1.jar:na]
	at org.prorefactor.proparse.ProParser.definestatement(ProParser.java:6871) ~[proparse-2.1.5.1.jar:na]
	at org.prorefactor.proparse.ProParser.statement(ProParser.java:1966) ~[proparse-2.1.5.1.jar:na]
	at org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:391) ~[proparse-2.1.5.1.jar:na]
	at org.prorefactor.proparse.ProParser.code_block(ProParser.java:417) ~[proparse-2.1.5.1.jar:na]
	at org.prorefactor.proparse.ProParser.methodstate(ProParser.java:9765) ~[proparse-2.1.5.1.jar:na]
	at org.prorefactor.proparse.ProParser.statement(ProParser.java:2183) ~[proparse-2.1.5.1.jar:na]
	at org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:391) ~[proparse-2.1.5.1.jar:na]
	at org.prorefactor.proparse.ProParser.code_block(ProParser.java:417) ~[proparse-2.1.5.1.jar:na]
	at org.prorefactor.proparse.ProParser.classstate(ProParser.java:5322) ~[proparse-2.1.5.1.jar:na]
	at org.prorefactor.proparse.ProParser.statement(ProParser.java:1889) ~[proparse-2.1.5.1.jar:na]
	at org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:391) ~[proparse-2.1.5.1.jar:na]
	at org.prorefactor.proparse.ProParser.program(ProParser.java:133) ~[proparse-2.1.5.1.jar:na]
	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:191) ~[proparse-2.1.5.1.jar:na]
	at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:221) ~[proparse-2.1.5.1.jar:na]
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:239) [sonar-openedge-plugin-2.1.5.1.jar:na]
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:153) [sonar-openedge-plugin-2.1.5.1.jar:na]
	at org.sonarsource.sonarlint.core.analyzer.sensor.SensorWrapper.analyse(SensorWrapper.java:52) [org.sonarsource.sonarlint.core.sonarlint-core_3.0.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.analyzer.sensor.AllSensorsExecutor.executeSensor(AllSensorsExecutor.java:79) [org.sonarsource.sonarlint.core.sonarlint-core_3.0.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.analyzer.sensor.AllSensorsExecutor.execute(AllSensorsExecutor.java:67) [org.sonarsource.sonarlint.core.sonarlint-core_3.0.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.analyzer.sensor.PhaseExecutor.execute(PhaseExecutor.java:36) [org.sonarsource.sonarlint.core.sonarlint-core_3.0.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.container.analysis.AnalysisContainer.doAfterStart(AnalysisContainer.java:142) [org.sonarsource.sonarlint.core.sonarlint-core_3.0.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.container.ComponentContainer.startComponents(ComponentContainer.java:125) [org.sonarsource.sonarlint.core.sonarlint-core_3.0.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.container.ComponentContainer.execute(ComponentContainer.java:110) [org.sonarsource.sonarlint.core.sonarlint-core_3.0.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.container.storage.StorageAnalyzer.analyze(StorageAnalyzer.java:74) [org.sonarsource.sonarlint.core.sonarlint-core_3.0.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.container.storage.StorageContainerHandler.analyze(StorageContainerHandler.java:69) [org.sonarsource.sonarlint.core.sonarlint-core_3.0.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.lambda$analyze$0(ConnectedSonarLintEngineImpl.java:154) [org.sonarsource.sonarlint.core.sonarlint-core_3.0.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.withReadLock(ConnectedSonarLintEngineImpl.java:338) [org.sonarsource.sonarlint.core.sonarlint-core_3.0.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.withReadLock(ConnectedSonarLintEngineImpl.java:328) [org.sonarsource.sonarlint.core.sonarlint-core_3.0.0.RSSW.jar:na]
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.analyze(ConnectedSonarLintEngineImpl.java:152) [org.sonarsource.sonarlint.core.sonarlint-core_3.0.0.RSSW.jar:na]
	at org.sonarlint.eclipse.core.internal.server.Server.runAnalysis(Server.java:275) ~[na:na]
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.run(AnalyzeProjectJob.java:426) ~[na:na]
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.runAnalysisAndUpdateMarkers(AnalyzeProjectJob.java:182) ~[na:na]
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.doRun(AnalyzeProjectJob.java:143) ~[na:na]
	at org.sonarlint.eclipse.core.internal.jobs.AbstractSonarProjectJob.runInWorkspace(AbstractSonarProjectJob.java:43) ~[na:na]
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39) ~[na:na]
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55) ~[na:na]
```

**Comment by gquerret** [comment]
Do you have rcode available for the base class ? Temp-table definition from parent classes are read from rcode, as it's much faster and reliable than parsing the hierarchy tree. Can you verify if `sonar.oe.binaries` is set correctly ?

**Comment by movedoa** [comment]
Everything is set correct (i guess) and this is the only case i found where SonarLint is not working.
I guess this is not the only case sonar.oe.binaries is used?
Also the r-code is available for both classes.

**Comment by gquerret** [comment]
I'll try to reproduce.

**Comment by cverbiest** [comment]
I had the same issue. did not have sonar.oe.binaries set.
I Added sonar.oe.binaries with same value as sonar.oe.propath and now sonarlint can parse the source.

**Comment by gquerret** [comment]
What are your `sonar.sources` and `sonar.oe.binaries` settings ?

**Comment by gquerret** [comment]
If `sonar.oe.binaries` is not specified, then SonarLint will look for rcode in the source directories.

**Comment by cverbiest** [comment]
> If sonar.oe.binaries is not specified, then SonarLint will look for rcode in the source directories.
Makes sense, in our multi project setup the base class is in a different project,  it cannot be found in the source directory which is limited to the current project. Our propath contains all projects this explains why setting sonar.oe.binaries equal to sonar.oe.propath is a solution for us.

**Comment by movedoa** [comment]
Yep, was a type in the sonar.sources property, thx for the help
