### ISSUE TITLE
TT field name 'options' lead to parser exception

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#509]
On behalf of AK

Code excerpt:
```
DEFINE {&ACCESS} TEMP-TABLE eFileUpload{&SUFFIX} NO-UNDO {&REFERENCE-ONLY} &IF DEFINED (NO-BEFORE) EQ 0 &THEN BEFORE-TABLE eFileUploadBefore{&SUFFIX} &ENDIF
    FIELD options AS CHARACTER FORMAT "X(50)":U LABEL "options":T
```

Stack trace:
```
antlr.NoViableAltException: unexpected token: options
	at org.prorefactor.proparse.ProParser.identifier(ProParser.java:1729)
	at org.prorefactor.proparse.ProParser.def_table_field(ProParser.java:39465)
	at org.prorefactor.proparse.ProParser.definetemptablestate(ProParser.java:36105)
	at org.prorefactor.proparse.ProParser.definestatement(ProParser.java:7016)
	at org.prorefactor.proparse.ProParser.statement(ProParser.java:1966)
	at org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:391)
	at org.prorefactor.proparse.ProParser.code_block(ProParser.java:417)
	at org.prorefactor.proparse.ProParser.classstate(ProParser.java:5322)
	at org.prorefactor.proparse.ProParser.statement(ProParser.java:1889)
	at org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:391)
	at org.prorefactor.proparse.ProParser.program(ProParser.java:133)
	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:191)
	at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:221)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:239)
    ...
```

**Comment by gquerret** [comment]
Fixed in develop
