### ISSUE TITLE
DEFINED function

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#515]
On behalf of XPO

Following statement:
```
&glob xxx xxx
def var xxx as char.
message substitute("&1", defined(XXX)).
```
leads to:
```
src\test\resources\data\bugsfixed\defined.p:3:24: expecting RIGHTPAREN, found ','
	at antlr.Parser.match(Parser.java:211)
	at org.prorefactor.proparse.ProParser.exprt2(ProParser.java:19630)
	at org.prorefactor.proparse.ProParser.exprt(ProParser.java:16167)
	at org.prorefactor.proparse.ProParser.unaryExpression(ProParser.java:19252)
	at org.prorefactor.proparse.ProParser.multiplicativeExpression(ProParser.java:19154)
	at org.prorefactor.proparse.ProParser.additiveExpression(ProParser.java:19101)
	at org.prorefactor.proparse.ProParser.relationalExpression(ProParser.java:18926)
	at org.prorefactor.proparse.ProParser.notExpression(ProParser.java:18897)
	at org.prorefactor.proparse.ProParser.andExpression(ProParser.java:18854)
	at org.prorefactor.proparse.ProParser.orExpression(ProParser.java:18821)
	at org.prorefactor.proparse.ProParser.expression(ProParser.java:2709)
	at org.prorefactor.proparse.ProParser.message_item(ProParser.java:44363)
	at org.prorefactor.proparse.ProParser.messagestate(ProParser.java:9560)
	at org.prorefactor.proparse.ProParser.statement(ProParser.java:2176)
	at org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:391)
	at org.prorefactor.proparse.ProParser.program(ProParser.java:133)
    ...
```

Code compiles correctly, but leads to runtime error: `DEFINED() function is valid only in preprocessor expressions. (2908)`. Interesting scenario, as the DEFINED function should be evaluated during compilation to my mind.
But if a function called `defined` is available, then this function call is used.

```
function defined returns logical(prm as char):
 return true.
end.
&glob xxx xxx
def var xxx as char.
message substitute("&1", defined(XXX)).
```

This problem should be reported as a rule, because defined can't be used outside of &IF
And no function should be called 'defined'.

**Comment by gquerret** [comment]
Works in ANTLR4
