### ISSUE TITLE
PROPATH function in preprocessor

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#516]
On behalf of XPO

This code:
```
&IF PROPATH MATCHES "*" &THEN
 .
&ENDIF
```

throws an exception:
```
org.prorefactor.proparse.antlr4.ProEvalException: Incompatible datatype
	at org.prorefactor.proparse.antlr4.PreproEval.getString(PreproEval.java:589)
	at org.prorefactor.proparse.antlr4.PreproEval.matches(PreproEval.java:665)
	at org.prorefactor.proparse.antlr4.PreproEval.visitStringOp(PreproEval.java:112)
	at org.prorefactor.proparse.antlr4.PreprocessorParser$StringOpContext.accept(PreprocessorParser.java:739)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at org.prorefactor.proparse.antlr4.PreproEval.visitPreproIfEval(PreproEval.java:78)
	at org.prorefactor.proparse.antlr4.PostLexer.preproIfCond(PostLexer.java:262)
	at org.prorefactor.proparse.antlr4.PostLexer.preproIf(PostLexer.java:151)
	at org.prorefactor.proparse.antlr4.PostLexer.nextToken(PostLexer.java:61)
	at org.prorefactor.proparse.antlr4.PostLexer.nextToken(PostLexer.java:1)
	at org.prorefactor.proparse.antlr4.TokenList.fillHeap(TokenList.java:89)
	at org.prorefactor.proparse.antlr4.TokenList.nextToken(TokenList.java:165)
	at org.prorefactor.proparse.antlr4.MultiChannelTokenSource.nextToken(MultiChannelTokenSource.java:45)
	at org.prorefactor.proparse.antlr4.FunctionKeywordTokenFilter.nextToken(FunctionKeywordTokenFilter.java:44)
	at org.prorefactor.proparse.antlr4.ProgressLexer$ANTRL2TokenStreamWrapper.nextToken(ProgressLexer.java:1095)
	at antlr.TokenStreamHiddenTokenFilter.consume(TokenStreamHiddenTokenFilter.java:38)
	at antlr.TokenStreamHiddenTokenFilter.consumeFirst(TokenStreamHiddenTokenFilter.java:42)
	at antlr.TokenStreamHiddenTokenFilter.nextToken(TokenStreamHiddenTokenFilter.java:122)
	at antlr.TokenBuffer.fill(TokenBuffer.java:69)
	at antlr.TokenBuffer.LA(TokenBuffer.java:80)
	at antlr.LLkParser.LA(LLkParser.java:52)
	at org.prorefactor.proparse.ProParser.program(ProParser.java:132)

```

**Comment by gquerret** [comment]
Fixed in master
