### ISSUE TITLE
Can't read rcode when using min-size

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#531]
RCode of classes compiled with min-size option set to true always lead to this stack trace:
```
     [java] ERROR: Unable to read rcode for file C:\Users\gquer\Projets\sonaroe-test-project\build\rssw\StaticLoad.r
     [java] eu.rssw.pct.RCodeInfo$InvalidRCodeException: Not enough bytes in type block
     [java]     at eu.rssw.pct.RCodeInfoDebugSegment.processTypeBlock(Unknown Source)
     [java]     at eu.rssw.pct.RCodeInfo.<init>(RCodeInfo.java:133)
     [java]     at eu.rssw.pct.RCodeInfo.<init>(RCodeInfo.java:95)
     [java]     at eu.rssw.pct.RCodeInfoDebugSegment.<init>(Unknown Source)
     [java]     at org.sonar.plugins.openedge.ProfilerCoverageSensor.a(Unknown Source)
     [java]     at org.sonar.plugins.openedge.ProfilerCoverageSensor.execute(Unknown Source)
```

**Comment by gquerret** [comment]
@dominickdm Fixed in develop, will be included in next release
