### ISSUE TITLE
NoViableException: unexpected token: IF

### ISSUE THREAD

**Issue by jcromanu** [Riverside-Software/sonar-openedge#557]
I´m having multiple exceptions related to the .i files where the parser encounters IF tokens

```
ERROR: Error during code parsing for ParentDirectory/sourceFile.p at position iseg001.i:2:1
antlr.NoViableAltException: unexpected token: IF
        at org.prorefactor.proparse.ProParser.expression_statement(ProParser.java:1687)
        at org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:395)
        at org.prorefactor.proparse.ProParser.program(ProParser.java:133)
        at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:191)
        at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:221)
        at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:239)
        at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:153)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:288)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:283)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:261)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
        at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
        at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

**Comment by gquerret** [comment]
It seems you're trying to execute the full parser on include files, which is likely to fail (in most cases) if you don't have the right preprocessor values. Would you be able to send the first two lines of the include file ?
Which version the OE plugin do you use ?

**Comment by gquerret** [comment]
And just for confirmation, are you under a support contract ?

**Comment by jckhan** [comment]
Hi @gquerret 

Here is the full content of the .i file 

`
IF  USERID("{1}") = "" OR
    USERID("{1}") = ? THEN
    RETURN ERROR.
`

I´m using the OE plugin version 2.1.5.3

What do you mean by the "right preprocessor values" ?

We are using the sonar scanner version 3.0.3.778

**Comment by gquerret** [comment]
Forget my first comment, it was probably too late, you're executing the parser on a .p file.
Would you be able to trim down sourceFile.p in order to reproduce the issue ?

**Comment by jckhan** [comment]
Not yet , which preprocessor values are the recommended ?

**Comment by jckhan** [comment]
Here are the first lines of the .p file 

`{iseg001.i payments}
/********
/*Author ...
/*Date ...
RUN _pfile.p ("WAIT").
`
We are not using PCT for the compilation

**Comment by gquerret** [comment]
If I try to analyze this file (source.p):
```
{iseg001.i payments}
RUN _pfile.p ("WAIT").
```

With include file iseg001.i:
```
    IF  USERID("{1}") = "" OR
        USERID("{1}") = ? THEN
        RETURN ERROR.
```

There's probably more code in your procedure, could you include it ?

**Comment by gquerret** [comment]
Any update ?

**Comment by jckhan** [comment]
There is more code but , the error comes when it reaches line 1 of iseg001.i over the "IF" token .
Should we always include all the .r files ?

**Comment by jcromanu** [comment]
@gquerret  Do we need to include all the  reference to all .r files ?

**Comment by gquerret** [comment]
.r is required for code coverage, and is recommended for better code analysis, but missing r-code can't be the cause of your exception.
Would you be able to reproduce your problem on the [sonaroe test project](https://github.com/Riverside-Software/sonaroe-test-project) ? Just add your include file and a sample .p in `src/procedures/sample` and execute `ant sonar`

**Comment by jcromanu** [comment]
Created the test project and added the .p and .i files and got the same error as the main project. 
Analyzing the .i file with a hex editor I found the following characters EF BB BF 0D 0A at the beginning of the file . Once I deleted those characters the .p included fine the .i file .
Looking with visual studio code with a UTF-8 encoding of the .i file seemed everything fine buy looking closer saw something strange.

**Comment by gquerret** [comment]
`EF BB BF` is the byte order mark in UTF-8.
I reproduced the problem locally, BOM is not handled correctly in include files, and lead to strange stack trace. I'll open another specifically for this improvement.
Thanks !

**Comment by gquerret** [comment]
@jcromanu Fix included in develop branch, you can try this snapshot: https://ci.rssw.eu/job/sonar-openedge/job/develop/65/
