### ISSUE TITLE
Enhancement request: Add scanner option to not report failed compiles

### ISSUE THREAD

**Issue by cverbiest** [Riverside-Software/sonar-openedge#560]
Some sources do not compile, these cause huge (40+lines) log entries with complete java stack.
In our build they will either have been excluded from the build 
or the error will have been reported during the compile part of the build.

Would it be possible to add an option to not report these as scanner errors ? 
I checked https://github.com/Riverside-Software/sonar-openedge/wiki/Property-list but could not find such an option.

It would help to focus on real scanner issues, I frequently check scanner errors that turn out to be non-compiling code.

Example entry
```
[ScanSmartLisaAppl] ERROR: Error during code parsing for src/erpord/conv/1002_2POST_aanpassen_KLORDQ_KPAR-TYPE.p at position null:-1:-1
[ScanSmartLisaAppl] antlr.SemanticException: src/erpord/conv/1002_2POST_aanpassen_KLORDQ_KPAR-TYPE.p:8: Unknown table name: ANKKPAR

... trimmed 40+ lines

[ScanSmartLisaAppl] 	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
[ScanSmartLisaAppl] 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

**Comment by gquerret** [comment]
Couldn't you exclude them of the analysis, with the `sonar.exclusions` property ?

**Comment by cverbiest** [comment]
Maybe, but I consider it normal, not an error, that code that does not compile cannot be scanned.
The huge error entry with stack trace is not useful in that case
Could it be reduced to a warning ?

**Comment by gquerret** [comment]
There might be an option, but that probably won't be the default behavior, as it helps reporting issues for first time users of SQ. It would be easier for "regular" users to specify this property once they know that some files don't compile.

**Comment by cverbiest** [comment]
Our build log file is currently 15000 lines, 12500 are from the scanner.
I'm trying to reduce the log file size (see also #559), at their current size nobody, except me, tries to read the logs.
