### ISSUE TITLE
ClassCastException in SubstituteLongChar rule

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#587]
```
     [java] ERROR: Error during rule execution for xxxx.w
     [java] java.lang.ClassCastException: org.prorefactor.treeparser.symbols.widgets.Browse cannot be cast to org.prorefactor.treeparser.Primative
     [java]     at org.prorefactor.core.nodetypes.FieldRefNode.getDataType(FieldRefNode.java:53)
     [java]     at eu.rssw.antlr.proparse.checks.SubstituteLongChar.execute(Unknown Source)
     [java]     at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.sensorExecute(OpenEdgeProparseCheck.java:47)
     [java]     at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:344)
     [java]     at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:176)
```

**Comment by gquerret** [comment]
Merged in develop
