### ISSUE TITLE
Unable to execute analysis after OE 11.7.4 upgrade

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#615]
Analysis log has lots of those lines:
```
line 3:102 missing NEWLINE at '850'
line 3:108 mismatched input '\r\n' expecting STRING
line 4:97 missing NEWLINE at '1655'
line 4:104 mismatched input '\r\n' expecting STRING
```

Followed by:
```
BUILD FAILED
/path/to/sonar.xml:43: java.lang.NullPointerException
	at eu.rssw.antlr.profiler.ProfilerSessionVisitor.visitModule_data_line(ProfilerSessionVisitor.java:60)
	at eu.rssw.antlr.profiler.ProfilerSessionVisitor.visitModule_data_line(ProfilerSessionVisitor.java:34)
	at eu.rssw.antlr.profiler.ProfilerGrammarParser$Module_data_lineContext.accept(ProfilerGrammarParser.java:297)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at eu.rssw.antlr.profiler.ProfilerGrammarBaseVisitor.visitModule_data(ProfilerGrammarBaseVisitor.java:34)
	at eu.rssw.antlr.profiler.ProfilerGrammarParser$Module_dataContext.accept(ProfilerGrammarParser.java:234)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
	at eu.rssw.antlr.profiler.ProfilerGrammarBaseVisitor.visitProfiler(ProfilerGrammarBaseVisitor.java:20)
	at eu.rssw.antlr.profiler.ProfilerGrammarParser$ProfilerContext.accept(ProfilerGrammarParser.java:118)
	at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
	at eu.rssw.antlr.profiler.ProfilerUtils.getProfilerSession(ProfilerUtils.java:61)
	at eu.rssw.antlr.profiler.ProfilerUtils.getProfilerSession(ProfilerUtils.java:51)
	at org.sonar.plugins.openedge.ProfilerCoverageSensor.a(Unknown Source)
	at org.sonar.plugins.openedge.ProfilerCoverageSensor.execute(Unknown Source)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:45)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:62)
    ...
```

**Comment by gquerret** [comment]
Fixed in 2.2.1
