### ISSUE TITLE
CommentedOutCode - String index out of range: 35

### ISSUE THREAD

**Issue by dominickdm** [Riverside-Software/sonar-openedge#647]
Hello,

We noticed an issue in +- 200 of our sources. They all return exactly the same error: **java.lang.StringIndexOutOfBoundsException: String index out of range: 35**

I tried isolating the error and it seems to be that a commented &GLOBAL-DEFINE is causing the issue.

`DEFINE VARIABLE test AS CHARACTER NO-UNDO.`
`/*&GLOBAL-DEFINE SupportDotNetOkCancel*/`

Source:
[out_of_range.zip](https://github.com/Riverside-Software/sonar-openedge/files/2851880/out_of_range.zip)

Console output:
```
Error during rule execution for [path=C:\Workspace\glims_dev_pro\tmp\ap_ppo_PP.p]
java.lang.StringIndexOutOfBoundsException: String index out of range: 35
	at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:237)
	at java.lang.StringBuilder.charAt(StringBuilder.java:76)
	at org.prorefactor.proparse.antlr4.Lexer.macroDefine(Lexer.java:1052)
	at org.prorefactor.proparse.antlr4.Lexer.directive(Lexer.java:889)
	at org.prorefactor.proparse.antlr4.Lexer.ampText(Lexer.java:872)
	at org.prorefactor.proparse.antlr4.Lexer.nextToken(Lexer.java:169)
	at org.prorefactor.proparse.antlr4.PostLexer.getNextToken(PostLexer.java:108)
	at org.prorefactor.proparse.antlr4.PostLexer.nextToken(PostLexer.java:58)
	at org.prorefactor.proparse.antlr4.PostLexer.nextToken(PostLexer.java:37)
	at org.prorefactor.proparse.antlr4.TokenList.fillHeap(TokenList.java:83)
	at org.prorefactor.proparse.antlr4.TokenList.nextToken(TokenList.java:167)
	at org.prorefactor.proparse.antlr4.MultiChannelTokenSource.nextToken(MultiChannelTokenSource.java:47)
	at org.prorefactor.proparse.antlr4.FunctionKeywordTokenFilter.nextToken(FunctionKeywordTokenFilter.java:48)
	at org.prorefactor.proparse.antlr4.ProgressLexer$ANTRL2TokenStreamWrapper.nextToken(ProgressLexer.java:1111)
	at antlr.TokenStreamHiddenTokenFilter.consume(TokenStreamHiddenTokenFilter.java:38)
	at antlr.TokenStreamHiddenTokenFilter.consumeFirst(TokenStreamHiddenTokenFilter.java:42)
	at antlr.TokenStreamHiddenTokenFilter.nextToken(TokenStreamHiddenTokenFilter.java:122)
	at antlr.TokenBuffer.fill(TokenBuffer.java:69)
	at antlr.TokenBuffer.LA(TokenBuffer.java:80)
	at antlr.LLkParser.LA(LLkParser.java:52)
	at org.prorefactor.proparse.ProParser.program(ProParser.java:132)
	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:199)
	at eu.rssw.antlr.proparse.checks.CommentedOutCode$ParseHiddenTokensWalker.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.CommentedOutCode$ParseHiddenTokensWalker.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.CommentedOutCode$ParseHiddenTokensWalker.visitNode(Unknown Source)
	at org.prorefactor.core.JPNode.walk(JPNode.java:1022)
	at org.prorefactor.core.JPNode.walk(JPNode.java:1024)
	at eu.rssw.antlr.proparse.checks.CommentedOutCode.execute(Unknown Source)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.sensorExecute(OpenEdgeProparseCheck.java:47)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:352)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:177)
	at org.sonarsource.sonarlint.core.analyzer.sensor.SensorWrapper.analyse(SensorWrapper.java:52)
	at org.sonarsource.sonarlint.core.analyzer.sensor.AllSensorsExecutor.executeSensor(AllSensorsExecutor.java:79)
	at org.sonarsource.sonarlint.core.analyzer.sensor.AllSensorsExecutor.execute(AllSensorsExecutor.java:67)
	at org.sonarsource.sonarlint.core.analyzer.sensor.PhaseExecutor.execute(PhaseExecutor.java:36)
	at org.sonarsource.sonarlint.core.container.analysis.AnalysisContainer.doAfterStart(AnalysisContainer.java:141)
	at org.sonarsource.sonarlint.core.container.ComponentContainer.startComponents(ComponentContainer.java:125)
	at org.sonarsource.sonarlint.core.container.ComponentContainer.execute(ComponentContainer.java:110)
	at org.sonarsource.sonarlint.core.container.storage.StorageAnalyzer.analyze(StorageAnalyzer.java:75)
	at org.sonarsource.sonarlint.core.container.storage.StorageContainerHandler.analyze(StorageContainerHandler.java:76)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.lambda$analyze$0(ConnectedSonarLintEngineImpl.java:152)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.withReadLock(ConnectedSonarLintEngineImpl.java:339)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.withReadLock(ConnectedSonarLintEngineImpl.java:329)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.analyze(ConnectedSonarLintEngineImpl.java:150)
	at org.sonarlint.eclipse.core.internal.server.Server.runAnalysis(Server.java:277)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.run(AnalyzeProjectJob.java:453)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.runAnalysisAndUpdateMarkers(AnalyzeProjectJob.java:204)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.doRun(AnalyzeProjectJob.java:160)
	at org.sonarlint.eclipse.core.internal.jobs.AbstractSonarProjectJob.runInWorkspace(AbstractSonarProjectJob.java:43)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

1 files proparse'd, 0 XML files, 0 listing files, 0 failure(s), 0 NCLOCs
```

**Comment by gquerret** [comment]
Reproduced !

**Comment by gquerret** [comment]
Fixed in develop
