### ISSUE TITLE
proparse: some unexpected token errors

### ISSUE THREAD

**Issue by dominickdm** [Riverside-Software/sonar-openedge#648]
The constructions below are causing parse errors. They are all compiled by the progress compiler. I known some code is bad an easy fixable, but maybe the parser could be extended to handle these constructions?

### 1.  ****unexpected token: GET****. 

`    METHOD PUBLIC VOID Test():`
`         /* some logic */`
`    END GET.`

_Stacktrace:_
_glims-abl-sources/be/mips/glims/manual/DataAccessDelegates/AssessmentMethodDataAccessDelegate.cls:20:9: unexpected token: GET
	at org.prorefactor.proparse.ProParser.method_end(ProParser.java:44737)
	at org.prorefactor.proparse.ProParser.methodstate(ProParser.java:9782)
	at org.prorefactor.proparse.ProParser.statement(ProParser.java:2196)
	at org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:395)
	at org.prorefactor.proparse.ProParser.code_block(ProParser.java:421)
	at org.prorefactor.proparse.ProParser.classstate(ProParser.java:5337)
	at org.prorefactor.proparse.ProParser.statement(ProParser.java:1902)
	at org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:395)
	at org.prorefactor.proparse.ProParser.program(ProParser.java:133)_

### 2.unexpected token: METHOD: 

`DEFINE PUBLIC PROPERTY TimeElapsed AS CHARACTER NO-UNDO`
`GET.`
`SET(arg AS CHARACTER):`
`ASSIGN`
`TimeElapsed = arg`
`TimeElapsedTextField:Text = arg.`
`END METHOD.`

_Stack:
at org.prorefactor.proparse.ProParser.defineproperty_accessor(ProParser.java:39162)
	at org.prorefactor.proparse.ProParser.definepropertystate(ProParser.java:35562)
	at org.prorefactor.proparse.ProParser.definestatement(ProParser.java:6981)
	at org.prorefactor.proparse.ProParser.statement(ProParser.java:1979)
	at org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:395)
	at org.prorefactor.proparse.ProParser.code_block(ProParser.java:421)
	at org.prorefactor.proparse.ProParser.classstate(ProParser.java:5337)_

### 3. **unexpected token: CHR**

`    METHOD PUBLIC CHARACTER GetEOF(): /* Unit Tested */`
`        RETURN CHR(-0x01, TargetCodePage, SourceCodePage). /* -1 */`
`    END METHOD.`

_Stack:
at org.prorefactor.proparse.ProParser.exprt2(ProParser.java:19878)
	at org.prorefactor.proparse.ProParser.exprt(ProParser.java:16192)
	at org.prorefactor.proparse.ProParser.unaryExpression(ProParser.java:19285)
	at org.prorefactor.proparse.ProParser.multiplicativeExpression(ProParser.java:19187)
	at org.prorefactor.proparse.ProParser.additiveExpression(ProParser.java:19134)
	at org.prorefactor.proparse.ProParser.relationalExpression(ProParser.java:18959)
	at org.prorefactor.proparse.ProParser.notExpression(ProParser.java:18930)
	at org.prorefactor.proparse.ProParser.andExpression(ProParser.java:18887)
	at org.prorefactor.proparse.ProParser.orExpression(ProParser.java:18854)_

### 4.**unexpected token: SERIALIZABLE**

`CLASS be.mips.ablframework.reports.AbstractXmlReportProcessingData ABSTRACT SERIALIZABLE:`
`    DEFINE PRIVATE SERIALIZABLE TEMP-TABLE test NO-UNDO`
`        FIELD test AS INTEGER.`
`END CLASS.`

_Stack:
at org.prorefactor.proparse.ProParser.definestatement(ProParser.java:7061)
	at org.prorefactor.proparse.ProParser.statement(ProParser.java:1979)
	at org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:395)
	at org.prorefactor.proparse.ProParser.code_block(ProParser.java:421)
	at org.prorefactor.proparse.ProParser.classstate(ProParser.java:5337)
	at org.prorefactor.proparse.ProParser.statement(ProParser.java:1902)
	at org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:395)
	at org.prorefactor.proparse.ProParser.program(ProParser.java:133)_

**Comment by gquerret** [comment]
Issue number 1 and 2 won't be fixed, they shouldn't be accepted by the compiler (and I already reported those constructs to Progress, so I think they might fail at some point).

And from a quick look, issues 3 and 4 seem to be legit, so they should be accepted by the parser.

**Comment by gquerret** [comment]
Issue 3 and 4 fixed in develop branch, that will be available in next release.
Issue 3 was about negative hex numbers, which were not supported.
