### ISSUE TITLE
SonarLint - Schema dump sometimes not dumping all databases

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#650]
Often when i start DevStudio not all database schemas get dumped and the analysis will fail because of that.
Most of the databeses are connected locally but the one creating the issue (issdata) is connected over network.
It seems the dump happens to early when the database isn't connected yet.
Happens more when i have multiple projects open, so the db connect takes longer.

![grafik](https://user-images.githubusercontent.com/13309951/53624768-a1481380-3c01-11e9-8296-0e60f65c4aa2.png)

```
repository 'rssw-oedb-main' associated with COMMERCIAL license permanent ID 'sonarlint-185de7f1e5d09db' - Customer 'move IT Software GmbH' - Expiration date 2019-09-19T22:00:00
Parsing 'C:\Entwicklung\OE11\Workspace117\B4910\.sonarlint\BOM.schema' with db name BOM
Parsing 'C:\Entwicklung\OE11\Workspace117\B4910\.sonarlint\mgr.schema' with db name mgr
Parsing 'C:\Entwicklung\OE11\Workspace117\B4910\.sonarlint\Fax.schema' with db name Fax
Parsing 'C:\Entwicklung\OE11\Workspace117\B4910\.sonarlint\SCM.schema' with db name SCM
Parsing 'C:\Entwicklung\OE11\Workspace117\B4910\.sonarlint\tempdb.schema' with db name tempdb
Parsing [path=C:\Entwicklung\OE11\Workspace117\B4910\prog\Iss\AdminConsole\UserSessionModel.cls]
Parsing XML XREF file C:\Entwicklung\Xref\B4910\AdminConsole\UserSessionModel.xref.xml
Parsing hierarchy of '[path=C:\Entwicklung\OE11\Workspace117\B4910\prog\Iss\AdminConsole\UserSessionModel.cls]' - Relative 'AdminConsole\UserSessionModel.cls'
  RCode found: 'C:\Entwicklung\OE11\Workspace117\B4910\prog\Iss\AdminConsole\UserSessionModel.r'
Parsing rcode C:\Entwicklung\OE11\Workspace117\B4910\prog\Iss\AdminConsole\UserSessionModel.r
Injecting type info 'Type info AdminConsole.UserSessionModel - Parent Progress.Lang.Object'
Listing file for '[path=C:\Entwicklung\OE11\Workspace117\B4910\prog\Iss\AdminConsole\UserSessionModel.cls]' not found or contains space character - Was looking for 'null'
Error during code parsing for [path=C:\Entwicklung\OE11\Workspace117\B4910\prog\Iss\AdminConsole\UserSessionModel.cls] at position null:-1:-1
 prog/Iss/AdminConsole/UserSessionModel.cls:121: Unknown table name: ISSDATA._Connect
	at org.prorefactor.proparse.ProParser.record(ProParser.java:3015)
	at org.prorefactor.proparse.ProParser.definebufferstate(ProParser.java:34180)
	at org.prorefactor.proparse.ProParser.definestatement(ProParser.java:6886)
	at org.prorefactor.proparse.ProParser.statement(ProParser.java:1979)
	at org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:395)
	at org.prorefactor.proparse.ProParser.code_block(ProParser.java:421)
	at org.prorefactor.proparse.ProParser.methodstate(ProParser.java:9780)
	at org.prorefactor.proparse.ProParser.statement(ProParser.java:2196)
	at org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:395)
	at org.prorefactor.proparse.ProParser.code_block(ProParser.java:421)
	at org.prorefactor.proparse.ProParser.classstate(ProParser.java:5337)
	at org.prorefactor.proparse.ProParser.statement(ProParser.java:1902)
	at org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:395)
	at org.prorefactor.proparse.ProParser.program(ProParser.java:133)
	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:199)
	at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:231)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:272)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:177)
	at org.sonarsource.sonarlint.core.analyzer.sensor.SensorWrapper.analyse(SensorWrapper.java:52)
	at org.sonarsource.sonarlint.core.analyzer.sensor.AllSensorsExecutor.executeSensor(AllSensorsExecutor.java:79)
	at org.sonarsource.sonarlint.core.analyzer.sensor.AllSensorsExecutor.execute(AllSensorsExecutor.java:67)
	at org.sonarsource.sonarlint.core.analyzer.sensor.PhaseExecutor.execute(PhaseExecutor.java:36)
	at org.sonarsource.sonarlint.core.container.analysis.AnalysisContainer.doAfterStart(AnalysisContainer.java:141)
	at org.sonarsource.sonarlint.core.container.ComponentContainer.startComponents(ComponentContainer.java:125)
	at org.sonarsource.sonarlint.core.container.ComponentContainer.execute(ComponentContainer.java:110)
	at org.sonarsource.sonarlint.core.container.storage.StorageAnalyzer.analyze(StorageAnalyzer.java:75)
	at org.sonarsource.sonarlint.core.container.storage.StorageContainerHandler.analyze(StorageContainerHandler.java:76)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.lambda$analyze$0(ConnectedSonarLintEngineImpl.java:152)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.withReadLock(ConnectedSonarLintEngineImpl.java:339)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.withReadLock(ConnectedSonarLintEngineImpl.java:329)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.analyze(ConnectedSonarLintEngineImpl.java:150)
	at org.sonarlint.eclipse.core.internal.server.Server.runAnalysis(Server.java:277)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.run(AnalyzeProjectJob.java:453)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.runAnalysisAndUpdateMarkers(AnalyzeProjectJob.java:204)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.doRun(AnalyzeProjectJob.java:160)
	at org.sonarlint.eclipse.core.internal.jobs.AbstractSonarProjectJob.runInWorkspace(AbstractSonarProjectJob.java:43)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

1 files proparse'd, 1 XML files, 0 listing files, 1 failure(s), 0 NCLOCs
```

**Comment by gquerret** [comment]
Another case has been reported (but not easily reproduced) where the same schema file was dumped multiple times. Some time will be taken with Progress to verify how their API can be used in a better way. 
An option in the context menu to refresh the .schema files will also be included.

**Comment by movedoa** [comment]
Would it be possible to automatically try and redump the schema if it is missing as a workaround? Imho this is a timing problem, at least it looks like it from the outside.

**Comment by gquerret** [comment]
If this case still happens, can you delete the `.sonarlint/*.schema` files in your project, and then use OpenEdge -> Refresh Cache menu in PDSOE ? That should be enough to regenerate the SL cache. There's unfortunately no way for SL to know if the PDSOE cache is not up to date.

**Comment by movedoa** [comment]
I just tried that and it only created 2 of 6 schema files. 
Then i deleted those two and Refreshed again and now i get 0 files. 
Then i restarted PDSOE and it again dumped only 2 of 6.

**Comment by gquerret** [comment]
Can you also verify if you have the same ID for those databases ? In a Progress session, Data Administration -> Database identification. If the DB were created as a copy of $DLC/empty, then they end up by default with the same ID.

**Comment by gquerret** [comment]
And just in case, using `sonar.oe.databases` is the fallback method in case the PDSOE DB connections don't work correctly.

**Comment by movedoa** [comment]
The DB Indentifier is different for all databases.

**Comment by lievencardoen** [comment]
Having the same issue, Gilles.

**Comment by gquerret** [comment]
Next version of SonarLint will fix this issue.
