### ISSUE TITLE
NullPointerException while parsing database schema

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#658]
On behalf of JG

This DB schema leads to NullPointerException:
```
ADD TABLE "Tab1"
  DESCRIPTION "XYZ"
  FROZEN
  DUMP-NAME "Tab1"

ADD FIELD "Fld1" OF "Tab1" AS character
  FORMAT "x(24)"
  MANDATORY

ADD INDEX "Idx1" ON "Tab1"
  PRIMARY
  INDEX-FIELD "Fld1"
.
```

Stacktrace:
```
java.lang.NullPointerException
        at eu.rssw.antlr.database.DumpFileVisitor.visitIndexField(DumpFileVisitor.java:312)
        at eu.rssw.antlr.database.DumpFileVisitor.visitIndexField(DumpFileVisitor.java:63)
        at eu.rssw.antlr.database.DumpFileGrammarParser$IndexFieldContext.accept(DumpFileGrammarParser.java:5020)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at eu.rssw.antlr.database.DumpFileVisitor.visitAddIndex(DumpFileVisitor.java:264)
        at eu.rssw.antlr.database.DumpFileVisitor.visitAddIndex(DumpFileVisitor.java:63)
        at eu.rssw.antlr.database.DumpFileGrammarParser$AddIndexContext.accept(DumpFileGrammarParser.java:4705)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at eu.rssw.antlr.database.DumpFileGrammarBaseVisitor.visitDump_type(DumpFileGrammarBaseVisitor.java:27)
```

**Comment by gquerret** [comment]
NPE is incorrectly thrown when `ASCENDING` keyword is missing in index field definition. Fix will be available in next release.

**Comment by gquerret** [comment]
Fixed in develop
