### ISSUE TITLE
how to debug proparse error's

### ISSUE THREAD

**Issue by dominickdm** [Riverside-Software/sonar-openedge#670]
Hi,

We have a file which isn't sonarlinted because of a proparse error. The java stack is also not revealing the line where the error occurs. 

What is the best approach to debug the issue? I tried configuring the 'sonar.oe.proparse.debug'-parameter, but i can't find the .proparse directory..

![image](https://user-images.githubusercontent.com/40289256/56964890-50e72680-6b5c-11e9-92d8-10fe539a240b.png)

```
Error during code parsing for glims-abl-sources/be/mips/glims/manual/communication/lcsd/LCSDLoad.p
java.lang.NullPointerException
	at org.prorefactor.proparse.SymbolScope.defineBuffer(SymbolScope.java:76)
	at org.prorefactor.proparse.ParserSupport.defBuffer(ParserSupport.java:171)
	at org.prorefactor.proparse.ProParser.definebufferstate(ProParser.java:34476)
	at org.prorefactor.proparse.ProParser.definestatement(ProParser.java:6902)
	at org.prorefactor.proparse.ProParser.statement(ProParser.java:1979)
	at org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:395)
	at org.prorefactor.proparse.ProParser.code_block(ProParser.java:421)
	at org.prorefactor.proparse.ProParser.procedurestate(ProParser.java:11125)
	at org.prorefactor.proparse.ProParser.statement(ProParser.java:2301)
	at org.prorefactor.proparse.ProParser.blockorstate(ProParser.java:395)
	at org.prorefactor.proparse.ProParser.program(ProParser.java:133)
	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:199)
	at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:231)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:272)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:177)
	at org.sonarsource.sonarlint.core.analyzer.sensor.SensorWrapper.analyse(SensorWrapper.java:52)
	at org.sonarsource.sonarlint.core.analyzer.sensor.AllSensorsExecutor.executeSensor(AllSensorsExecutor.java:79)
	at org.sonarsource.sonarlint.core.analyzer.sensor.AllSensorsExecutor.execute(AllSensorsExecutor.java:67)
	at org.sonarsource.sonarlint.core.analyzer.sensor.PhaseExecutor.execute(PhaseExecutor.java:36)
	at org.sonarsource.sonarlint.core.container.analysis.AnalysisContainer.doAfterStart(AnalysisContainer.java:141)
	at org.sonarsource.sonarlint.core.container.ComponentContainer.startComponents(ComponentContainer.java:125)
	at org.sonarsource.sonarlint.core.container.ComponentContainer.execute(ComponentContainer.java:110)
	at org.sonarsource.sonarlint.core.container.storage.StorageAnalyzer.analyze(StorageAnalyzer.java:75)
	at org.sonarsource.sonarlint.core.container.storage.StorageContainerHandler.analyze(StorageContainerHandler.java:76)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.lambda$analyze$0(ConnectedSonarLintEngineImpl.java:152)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.withReadLock(ConnectedSonarLintEngineImpl.java:339)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.withReadLock(ConnectedSonarLintEngineImpl.java:329)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.analyze(ConnectedSonarLintEngineImpl.java:150)
	at org.sonarlint.eclipse.core.internal.server.Server.runAnalysis(Server.java:277)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.run(AnalyzeProjectJob.java:453)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.runAnalysisAndUpdateMarkers(AnalyzeProjectJob.java:204)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.doRun(AnalyzeProjectJob.java:160)
	at org.sonarlint.eclipse.core.internal.jobs.AbstractSonarProjectJob.runInWorkspace(AbstractSonarProjectJob.java:43)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by gquerret** [comment]
NullPointerException are unfortunately impossible to debug directly in SonarLint, you need the source code to do that. Without a dev environment, the last line tells you that the NPE was raised in [SymbolScope.java at line 76](https://github.com/Riverside-Software/sonar-openedge/blob/master/proparse/src/main/java/org/prorefactor/proparse/SymbolScope.java#L76). The method name in the next lines tell you that the problem occured in a `DEFINE BUFFER` statement. You could try to isolate all the `DEFINE BUFFER` statements in this procedure, and see which one is the culprit. I'd think it has a buffer for dbname.tablename and where dbname has something unusual (which then leads to the NPE).
