### ISSUE TITLE
NPE - OUTPUT LIKE

### ISSUE THREAD

**Issue by movedoa** [Riverside-Software/sonar-openedge#678]
![grafik](https://user-images.githubusercontent.com/13309951/58785825-a0e75c00-85e6-11e9-816e-0d574f9fa681.png)

Since 2.5.0 

`[sonar:sonar] Unable to set JPNode symbol for variable piAdrNbrLIKEAdrHdr.AdrNbr`

```
[sonar:sonar] java.lang.NullPointerException: null
[sonar:sonar] 	at eu.rssw.antlr.proparse.checks.VariableAssignedButNotRead.a(Unknown Source)
[sonar:sonar] 	at eu.rssw.antlr.proparse.checks.VariableAssignedButNotRead.execute(Unknown Source)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.sensorExecute(OpenEdgeProparseCheck.java:47)
[sonar:sonar] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:330)
[sonar:sonar] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:158)
[sonar:sonar] 	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
[sonar:sonar] 	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
[sonar:sonar] 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
[sonar:sonar] 	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
[sonar:sonar] 	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
[sonar:sonar] 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:288)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:283)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:261)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
[sonar:sonar] 	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
[sonar:sonar] 	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
[sonar:sonar] 	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
[sonar:sonar] 	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
[sonar:sonar] 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
[sonar:sonar] 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
[sonar:sonar] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[sonar:sonar] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:498)
[sonar:sonar] 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
[sonar:sonar] 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
[sonar:sonar] 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
[sonar:sonar] 	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
[sonar:sonar] 	at org.sonarsource.scanner.ant.SonarQubeTask.launchAnalysis(SonarQubeTask.java:99)
[sonar:sonar] 	at org.sonarsource.scanner.ant.SonarQubeTask.execute(SonarQubeTask.java:81)
[sonar:sonar] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[sonar:sonar] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:498)
[sonar:sonar] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[sonar:sonar] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[sonar:sonar] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[sonar:sonar] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[sonar:sonar] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[sonar:sonar] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
[sonar:sonar] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
[sonar:sonar] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[sonar:sonar] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:498)
[sonar:sonar] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[sonar:sonar] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[sonar:sonar] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[sonar:sonar] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
[sonar:sonar] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[sonar:sonar] 	at org.apache.tools.ant.Main.runBuild(Main.java:851)
[sonar:sonar] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
[sonar:sonar] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
[sonar:sonar] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
```

**Comment by gquerret** [comment]
Confirmed.

**Comment by gquerret** [comment]
Fixed in develop
