### ISSUE TITLE
SonarLint - other has different root 

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/sonar-openedge#682]
## Subject of the issue
I have this error when executing sonarlint from PDS : 
```
Parsing 'D:\workspace\SonarTest\.sonarlint\GCO.schema' with db name GCO
Parsing [path=W:\Sonar\v51x\src\TestMessage.p]
Parsing hierarchy of '[path=W:\Sonar\v51x\src\TestMessage.p]' - Relative 'TestMessage.p'
  RCode found: 'W:\Sonar\v51x\obj\TestMessage.r'
Parsing rcode W:\Sonar\v51x\obj\TestMessage.r
Listing file for '[path=W:\Sonar\v51x\src\TestMessage.p]' not found or contains space character - Was looking for 'null'
Error during execution of SonarLint analysis
java.lang.IllegalArgumentException: 'other' has different root
	at sun.nio.fs.WindowsPath.relativize(WindowsPath.java:392)
	at sun.nio.fs.WindowsPath.relativize(WindowsPath.java:44)
	at org.sonar.plugins.openedge.foundation.InputFileUtils.getRelativePath(InputFileUtils.java:68)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:306)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:158)
	at org.sonarsource.sonarlint.core.analyzer.sensor.SensorWrapper.analyse(SensorWrapper.java:52)
	at org.sonarsource.sonarlint.core.analyzer.sensor.AllSensorsExecutor.executeSensor(AllSensorsExecutor.java:79)
	at org.sonarsource.sonarlint.core.analyzer.sensor.AllSensorsExecutor.execute(AllSensorsExecutor.java:67)
	at org.sonarsource.sonarlint.core.analyzer.sensor.PhaseExecutor.execute(PhaseExecutor.java:36)
	at org.sonarsource.sonarlint.core.container.analysis.AnalysisContainer.doAfterStart(AnalysisContainer.java:141)
	at org.sonarsource.sonarlint.core.container.ComponentContainer.startComponents(ComponentContainer.java:125)
	at org.sonarsource.sonarlint.core.container.ComponentContainer.execute(ComponentContainer.java:110)
	at org.sonarsource.sonarlint.core.container.storage.StorageAnalyzer.analyze(StorageAnalyzer.java:75)
	at org.sonarsource.sonarlint.core.container.storage.StorageContainerHandler.analyze(StorageContainerHandler.java:76)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.lambda$analyze$0(ConnectedSonarLintEngineImpl.java:152)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.withReadLock(ConnectedSonarLintEngineImpl.java:339)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.withReadLock(ConnectedSonarLintEngineImpl.java:329)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.analyze(ConnectedSonarLintEngineImpl.java:150)
	at org.sonarlint.eclipse.core.internal.server.Server.runAnalysis(Server.java:277)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.run(AnalyzeProjectJob.java:453)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.runAnalysisAndUpdateMarkers(AnalyzeProjectJob.java:204)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.doRun(AnalyzeProjectJob.java:160)
	at org.sonarlint.eclipse.core.internal.jobs.AbstractSonarProjectJob.runInWorkspace(AbstractSonarProjectJob.java:43)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

This error appears because I use "Linked Folder" in my eclipse project for legacy reason and this "Linked Folder" is not on the same Drive : 
* My Project is located in `D:\workspace\SonarTest`
* My Src folder is located in `W:\Sonar\v51x\src`

The error is throw from `InputFileUtils.getRelativePath(...)` in a catch block (and this error is the reason why we are in the catch block) : 
* `      LOG.error("Error during code parsing for " + InputFileUtils.getRelativePath(file, context.fileSystem()), caught);`

A solution could be to return the absolute path (if valid) instead of an exception if `InputFileUtils.getRelativePath(...)` fails.

What do you think ? I can create a Pull Request if needed.

## Your environment
OpenEdge version 11.7.4
SonarLint 3.6.1008
Sonar Openedge Rules : 2.5.0

**Comment by gquerret** [comment]
Do you have your source directory in the propath ?

**Comment by clement-brodu** [comment]
Yes, this is the beginning of my propath : 
`Using PROPATH : W:\Sonar\v51x\src,D:\workspace\SonarTest\SrcLocal`

I tried different settings, but nothing works because of the different drive letters.

**Comment by gquerret** [comment]
With verbose logs activated, what are the values in this section:
```
Starting analysis with configuration:
[
  moduleKey: 
  baseDir: 
  workDir: 
  extraProperties: 
  inputFiles: [
  ]
]
```

And what do you have in the .project file for linked folders ?

**Comment by clement-brodu** [comment]
Here is my configuration : 

```
Starting analysis with configuration:
[
  moduleKey: sonar-key
  baseDir: D:\workspace\SonarTest
  workDir: D:\workspace\.metadata\.plugins\org.eclipse.core.resources\.projects\SonarTest\org.sonarlint.eclipse.core
  extraProperties: {sonar.oe.binaries=W:/Sonar/v51x/obj,D:/workspace/SonarTest/ObjLocal, sonar.sources=W:\Sonar\v51x\src,D:\workspace\SonarTest\SrcLocal, sonar.oe.lint.databases=D:\workspace\SonarTest\.sonarlint\GCO.schema, sonar.oe.propath=W:\Sonar\v51x\src,D:\workspace\SonarTest\SrcLocal,D:\workspace\SonarTest,D:\Outils\Openedge\OE1174\gui\,D:\Outils\Openedge\OE1174\gui\adecomm.pl,D:\Outils\Openedge\OE1174\gui\adecomp.pl,D:\Outils\Openedge\OE1174\gui\adedict.pl,D:\Outils\Openedge\OE1174\gui\adeedit.pl,D:\Outils\Openedge\OE1174\gui\adeicon.pl,D:\Outils\Openedge\OE1174\gui\adeshar.pl,D:\Outils\Openedge\OE1174\gui\adeuib.pl,D:\Outils\Openedge\OE1174\gui\adeweb.pl,D:\Outils\Openedge\OE1174\gui\adexml.pl,D:\Outils\Openedge\OE1174\gui\dataadmin.pl,D:\Outils\Openedge\OE1174\gui\prodict.pl,D:\Outils\Openedge\OE1174\gui\protools.pl,D:\Outils\Openedge\OE1174\gui\OpenEdge.Core.pl,D:\Outils\Openedge\OE1174\gui\OpenEdge.BusinessLogic.pl,D:\Outils\Openedge\OE1174\gui\netlib\OpenEdge.Net.pl,D:\Outils\Openedge\OE1174,D:\Outils\Openedge\OE1174\bin}
  inputFiles: [
    W:\Sonar\v51x\src\TestMessage.p (UTF-8)
  ]
]
```
And this is my linked folder : 
```xml
<linkedResources>
	<link>
		<name>Src</name>
		<type>2</type>
		<location>W:/Sonar/v51x/src</location>
	</link>
</linkedResources>
```

**Comment by gquerret** [comment]
Reproduced, will be fixed in next release. But side effects might probably remain, as it's an expectation of SonarQube to have all source code in a subfolder of the base directory (which should be the case when source code is checked out from a code repository).

**Comment by cverbiest** [comment]
@gquerret I'm picking in on 

> it's an expectation of SonarQube to have all source code in a subfolder of the base directory.

Does this mean that if you put each project in it's own repository and one repository references Interfaces or includes of another project that is on the propath this will never fully work ?

Is there documentation, guidelines or a demo available on how to structure projects so that you can fully use SonarQube for openedge ?

**Comment by gquerret** [comment]
No detailed reference available right now, but just include in `sonar.sources` a directory not under base directory, and the scanner will just ignore those files (with a warning).
Even if a project references another project, the source code of the main project still resides in `src` (or any other subdir). `sonar.sources` and `sonar.oe.propath` don't have to point to the same set of directories.

**Comment by gquerret** [comment]
Merged in develop
