### ISSUE TITLE
StackOverflowError when analyzing large class

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#689]
On behalf of DOA

Since 2.5.0, analyzing large class leads to StackOverflowError. Eclipse log file says:
```
java.lang.StackOverflowError
	at java.util.IdentityHashMap.hash(IdentityHashMap.java:294)
	at java.util.IdentityHashMap.put(IdentityHashMap.java:425)
	at org.antlr.v4.runtime.tree.ParseTreeProperty.put(ParseTreeProperty.java:32)
	at org.prorefactor.proparse.ParserSupport.pushNode(ParserSupport.java:241)
	at org.prorefactor.core.JPNode$Builder.build(JPNode.java:1009)
	at org.prorefactor.core.JPNode$Builder.build(JPNode.java:1020)
	at org.prorefactor.core.JPNode$Builder.build(JPNode.java:1034)
	at org.prorefactor.core.JPNode$Builder.build(JPNode.java:1020)
	at org.prorefactor.core.JPNode$Builder.build(JPNode.java:1034)
	at org.prorefactor.core.JPNode$Builder.build(JPNode.java:1034)
    ... thousands of JPNode.java:1034 line ...
```
One method has approx. 5000 statements.

**Comment by gquerret** [comment]
The syntax tree is generated recursively, and a block of code with a very large number of children can blow the stack. A quick fix is to increase the initial stack size in PDSOE (or in the batch analyzer as the problem will also occur there), by using `-Xss2m` or `-Xss4m` (initial value is 1Mb on Java 64bits). Unless you have customized your PDSOE startup shortcut, you can add that in %DLC%\oeide\eclipse\eclipse.ini

**Comment by movedoa** [comment]
Works now. Thx
