### ISSUE TITLE
ERROR: Failed to find LIKE datatype at <filename> line nn

### ISSUE THREAD

**Issue by grendal100** [Riverside-Software/sonar-openedge#706]
Hi there,

We're bringing a new project into SonarQube and have compiled the code using PCTAnt to generate the necessary XREF and Listing files needed by the sonar scanner.

When running the sonar scanner, this message is appearing when a variable or column is defined LIKE a table column.. The message appears regardless of whether the column in question is defined in a DEFINE TEMP-TABLE or DEFINE VARIABLE statement, or whether it is within an include file or directly within the .p or .w.

Also, the majority of these instances are for columns which are used elsewhere within the codebase, used as the basis of other such definitions yet these are not flagged as an error within the scan.

The table and column names are not abbreviated in any way. We have found that resolution is reached by prefixing the reference with the logical db name ie DB.TABLE_NAME.FIELD_NAME but this doesn't explain the issue and so I do not wish to modify the code to include this.

If you need any further detail, let me know.

Many thanks.

Mark

**Comment by gquerret** [comment]
Can you include the version number of sonar-openedge ?

**Comment by grendal100** [comment]
Hi there,

Versions are:
OE: 11.7.4
PCTAnt: pct-212 (commit 830b8cb)
Sonar-openedge: 2.3.2

Schoolboy error!! I've noticed that the sonar-openedge version is out of date so I've updated this to 2.5.1. 

After doing so, I'm now getting many instances of 'ERROR: Failed to find LIKE datatype at 0 line 0' but these contain no reference to a file. There are some other errors appearing too so I will resolve these first and report back if this is still an issue.

Many thanks

**Comment by grendal100** [comment]
Ok, so this appears to still be an issue.

All the update has done is remove reference to the files. It appears to still be complaining about the same files.

I also have an additional error when parsing some files (the commonality I am unable to locate at this time):

11:34:18.052 ERROR: Error during code parsing for <filename>
java.lang.NullPointerException: null
        at org.prorefactor.proparse.antlr4.TreeParser.field(TreeParser.java:2741)
        at org.prorefactor.proparse.antlr4.TreeParser.exitField(TreeParser.java:1824)
        at org.prorefactor.proparse.antlr4.Proparse$FieldContext.exitRule(Proparse.java:11094)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:47)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:30)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
        at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28) 
        <many instances of the previous line>
        at org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:215)
        at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:251)
        at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:158)
        at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:359)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:354)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:317)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:128)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)

Using the -X parameter for sonar-scanner, for this file the debug has many 'Enter FrameStack#nodeOfBlock' and 'Enter FrameStack#statementEnd' entries. It does not, however, conclude with the 'nn milliseconds to generate ParseUnit' message ... it just moves on to the next file.

For reference, this one procedure has 5162 lines containing 70 procedures and 7 functions, but we have some which are far greater in size than this which have passed through the parser successfully.

Any help would be gratefully appreciated. In the interim, I will step back to version 2.3.2 and incrementally move up the versions to see if any additional light can be shed.

**Comment by grendal100** [comment]
In addition, 2.5.1 appears to have taken a step back in reporting the errors above. They no longer report the filename nor the field/column which is causing the issue. I've reverted to 2.3.2 and get the descriptive errors again.

So, from my perspective the issue is still there which I have initially reported ... just that 2.5.1 is not reporting them correctly.

**Comment by gquerret** [comment]
Regarding this `Failed to find LIKE datatype`, are you able to submit a small test case to reproduce the issue ? Maybe by trimming all unnecessary lines of code of a procedure where this issue occurs. 
Please also note that even if there's this message in the log, it doesn't prevent the analysis from being executed.
Version 2.5 included a big change in the parser, and error reporting was completely changed, sometimes not in a good way. We're working on this topic.
