### ISSUE TITLE
[2.5.1] Stackoverflow parsing Enum

### ISSUE THREAD

**Issue by lneumeier** [Riverside-Software/sonar-openedge#707]
Hello,

I'm getting a StackOverflow Exception:

```
16:21:23.775 DEBUG: Parsing src/hhberlin/prodoppik/database/EDatabaseField.cls
16:21:23.775 DEBUG: Parsing XML XREF file E:\Sonarqube\v501.69\build\.pct\hhberlin\prodoppik\database\EDatabaseField.cls.xref
16:21:23.977 INFO: ------------------------------------------------------------------------
16:21:23.977 INFO: EXECUTION FAILURE
16:21:23.977 INFO: ------------------------------------------------------------------------
16:21:23.978 INFO: Total time: 1:18:38.519s
16:21:25.401 INFO: Final Memory: 1522M/4810M
16:21:25.401 INFO: ------------------------------------------------------------------------
16:21:25.401 ERROR: Error during SonarQube Scanner execution
java.lang.StackOverflowError
	at java.base/java.util.IdentityHashMap.hash(Unknown Source)
	at java.base/java.util.IdentityHashMap.put(Unknown Source)
	at org.antlr.v4.runtime.tree.ParseTreeProperty.put(ParseTreeProperty.java:32)
	at org.prorefactor.proparse.ParserSupport.pushNode(ParserSupport.java:242)
	at org.prorefactor.core.JPNode$Builder.build(JPNode.java:1009)
	at org.prorefactor.core.JPNode$Builder.build(JPNode.java:1034)
	at org.prorefactor.core.JPNode$Builder.build(JPNode.java:1020)
	at org.prorefactor.core.JPNode$Builder.build(JPNode.java:1034)
```

The class EDatabaseField is a Enum with 8419 DEFINE ENUM ... statements.

**Comment by gquerret** [comment]
Probably identical to #689
Can you try increasing -Xss ? The way the tree is generated will be updated in a future version so that it won't require such a large stack

**Comment by lneumeier** [comment]
Thank you, that worked.
