### ISSUE TITLE
Parser - Dynamic-Invoke with crash

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/sonar-openedge#708]
## Subject of the issue
I have a Parser error that crash **sonar-scanner** process.

I use only 2 simples "home made" rules (for unused variables and varaible of 1 character).

I'm on version 2.5.1 of the plugin.
It also fails in SonarLint.

## Code to reproduce 

```abl
 BLOCK-LEVEL ON ERROR UNDO, THROW.

CLASS Sonar.Bug2 : 
    
    DEFINE PROTECTED PROPERTY gToto AS CHARACTER INITIAL "Bug1" NO-UNDO GET. SET.
    /*------------------------------------------------------------------------------ 
     Purpose: 
     Notes: 
    -----------------------------------------------------------------------------*/ 
    METHOD PROTECTED VOID Case4 ( ) :
       DEFINE VARIABLE vText AS CHARACTER NO-UNDO.
       // this line makes an error and makes the application crash and its a big problem
       // -> cf error 1 
       vText = DYNAMIC-INVOKE("Sonar." + THIS-OBJECT:gToto, "HelloWorld").
       // this line makes an error but no crash 
       // -> cf error 2
       vText = DYNAMIC-INVOKE("Sonar." + "Bug1", "HelloWorld").
    END METHOD.
END CLASS.
```

### Error 1 : 
```
16:02:35.529 DEBUG: Parsing Src/Sonar/Bug2.cls
16:02:35.533 DEBUG: Listing file for 'Src/Sonar/Bug2.cls' not found or contains space character - Was looking for 'null'
16:02:35.576 DEBUG: No TypeInfo found for Sonar.Bug2
16:02:35.592 ERROR: Syntax error -- Src/Sonar/Bug2.cls:14:40 -- no viable alternative at input 'vText = DYNAMIC-INVOKE("Sonar." +'
16:02:35.593 ERROR: Syntax error -- Src/Sonar/Bug2.cls:14:40 -- no viable alternative at input 'vText = DYNAMIC-INVOKE("Sonar." +'
16:02:35.661 ERROR: Syntax error -- Src/Sonar/Bug2.cls:14:59 -- no viable alternative at input 'THIS-OBJECT:gToto,'
16:02:35.704 ERROR: Syntax error -- Src/Sonar/Bug2.cls:17:40 -- no viable alternative at input 'vText = DYNAMIC-INVOKE("Sonar." +'
16:02:35.711 ERROR: Syntax error -- Src/Sonar/Bug2.cls:17:48 -- mismatched input ',' expecting {<EOF>, PERIOD, NOERROR_KW}
16:02:35.717 DEBUG: 164 milliseconds to generate ParseUnit
16:02:35.743 INFO: ------------------------------------------------------------------------
16:02:35.744 INFO: EXECUTION FAILURE
16:02:35.744 INFO: ------------------------------------------------------------------------
16:02:35.745 INFO: Total time: 11.860s
16:02:35.934 INFO: Final Memory: 15M/399M
16:02:35.938 INFO: ------------------------------------------------------------------------
16:02:35.941 ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
        at org.prorefactor.core.JPNode.walk(JPNode.java:788)
        at org.prorefactor.core.JPNode.walk(JPNode.java:792)
        at org.prorefactor.core.JPNode.walk(JPNode.java:792)
        at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.computeCpd(OpenEdgeProparseSensor.java:445)
        at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:315)
        at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:158)
        at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:400)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:395)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:358)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
        at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:128)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

### Error 2 : 
```
16:04:26.480 DEBUG: Parsing Src/Sonar/Bug2.cls
16:04:26.484 DEBUG: Listing file for 'Src/Sonar/Bug2.cls' not found or contains space character - Was looking for 'null'
16:04:26.520 DEBUG: No TypeInfo found for Sonar.Bug2
16:04:26.534 ERROR: Syntax error -- Src/Sonar/Bug2.cls:17:40 -- no viable alternative at input 'vText = DYNAMIC-INVOKE("Sonar." +'
16:04:26.534 ERROR: Syntax error -- Src/Sonar/Bug2.cls:17:40 -- no viable alternative at input 'vText = DYNAMIC-INVOKE("Sonar." +'
16:04:26.548 ERROR: Syntax error -- Src/Sonar/Bug2.cls:17:48 -- mismatched input ',' expecting {<EOF>, PERIOD, NOERROR_KW}
16:04:26.553 DEBUG: 46 milliseconds to generate ParseUnit
16:04:26.554 DEBUG: Not enough content in 'Src/Sonar/Bug2.cls' to have CPD blocks, it will not be part of the duplication detection
16:04:26.681 DEBUG: ActiveRule - ******
16:04:26.682 DEBUG: ActiveRule - ******
16:04:26.766 INFO: 2 files proparse'd, 0 XML files, 0 listing files, 0 failure(s), 37 NCLOCs
16:04:26.767 INFO: AST Generation | time=1987 ms
16:04:26.770 INFO: XML Parsing    | time=0 ms
16:04:26.773 INFO: Rule ****** | time=0 ms
16:04:26.773 INFO: Rule ****** | time=1 ms
16:04:26.773 INFO: Sensor OpenEdgeProparseSensor [pnvrules] (done) | time=2384ms
16:04:26.782 INFO: ------------- Run sensors on project
16:04:26.791 INFO: Sensor Zero Coverage Sensor
16:04:26.800 INFO: Sensor Zero Coverage Sensor (done) | time=9ms
16:04:26.803 INFO: SCM Publisher is disabled
16:04:26.807 INFO: 2 files had no CPD blocks
16:04:26.809 INFO: Calculating CPD for 0 files
16:04:26.813 INFO: CPD calculation finished
16:04:27.116 INFO: Analysis report generated in 286ms, dir size=8 KB
16:04:30.329 INFO: Analysis report compressed in 3212ms, zip size=4 KB
16:04:30.330 INFO: Analysis report generated in ******\.scannerwork\scanner-report
16:04:30.469 INFO: Analysis report uploaded in 137ms
16:04:30.470 INFO: ANALYSIS SUCCESSFUL, you can browse ******
******
16:04:30.528 INFO: Analysis total time: 13.674 s
16:04:30.532 INFO: ------------------------------------------------------------------------
16:04:30.533 INFO: EXECUTION SUCCESS
16:04:30.534 INFO: ------------------------------------------------------------------------
16:04:30.534 INFO: Total time: 16.257s
16:04:30.663 INFO: Final Memory: 11M/362M
16:04:30.664 INFO: ------------------------------------------------------------------------
```

**Comment by gquerret** [comment]
Reproduced, first argument can be a full expression and not just an expression term.
Fix will be included in next release.

**Comment by gquerret** [comment]
Fixed in develop
