### ISSUE TITLE
Sonarlint - Variable and Include

### ISSUE THREAD

**Issue by clement-brodu** [Riverside-Software/sonar-openedge#710]
## Subject of the issue
In SonarLint, when I try to analyse my code, it fails.
It's because I have a variable named `VarA###` in one of my includes.
If the variable is declared in the main file, it works fine.

In sonar-scanner, everything seems OK.

I use only 2 simples "home made" rules (for unused variables and varaible of 1 character).

I'm on version 2.5.1 of the plugin.

## Code to Reproduce 
```abl
DEFINE VARIABLE vCharbid AS CHARACTER NO-UNDO.
DEFINE VARIABLE v AS INTEGER NO-UNDO.


/* This Line is NOK */
{Sonar/IncBug3.i}
/* Include with 
DEFINE VARIABLE VarA### AS CHARACTER NO-UNDO.
*/

/* This line is OK */
DEFINE VARIABLE VarB### AS CHARACTER NO-UNDO.

```

## Error
The stack trace :
```
Error during rule execution for [path=D:\workspace\Src\Sonar\Bug3.p]
java.lang.NullPointerException
	at org.sonarsource.sonarlint.core.container.analysis.filesystem.RelativePathPredicate.apply(RelativePathPredicate.java:45)
	at org.sonar.api.batch.fs.internal.OptimizedFilePredicateAdapter.apply(OptimizedFilePredicateAdapter.java:35)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at org.sonar.api.batch.fs.internal.DefaultFileSystem.inputFile(DefaultFileSystem.java:117)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.getInputFile(OpenEdgeProparseCheck.java:73)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.createIssue(OpenEdgeProparseCheck.java:85)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.reportIssue(OpenEdgeProparseCheck.java:128)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.reportIssue(OpenEdgeProparseCheck.java:117)
	at com.acme.rules.UnusedVarRule.execute(UnusedVarRule.java:24)
	at com.acme.rules.UnusedVarRule.execute(UnusedVarRule.java:12)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.sensorExecute(OpenEdgeProparseCheck.java:47)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:330)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:158)
	at org.sonarsource.sonarlint.core.analyzer.sensor.SensorWrapper.analyse(SensorWrapper.java:52)
	at org.sonarsource.sonarlint.core.analyzer.sensor.AllSensorsExecutor.executeSensor(AllSensorsExecutor.java:79)
	at org.sonarsource.sonarlint.core.analyzer.sensor.AllSensorsExecutor.execute(AllSensorsExecutor.java:67)
	at org.sonarsource.sonarlint.core.analyzer.sensor.PhaseExecutor.execute(PhaseExecutor.java:36)
	at org.sonarsource.sonarlint.core.container.analysis.AnalysisContainer.doAfterStart(AnalysisContainer.java:141)
	at org.sonarsource.sonarlint.core.container.ComponentContainer.startComponents(ComponentContainer.java:125)
	at org.sonarsource.sonarlint.core.container.ComponentContainer.execute(ComponentContainer.java:110)
	at org.sonarsource.sonarlint.core.container.storage.StorageAnalyzer.analyze(StorageAnalyzer.java:75)
	at org.sonarsource.sonarlint.core.container.storage.StorageContainerHandler.analyze(StorageContainerHandler.java:76)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.lambda$analyze$0(ConnectedSonarLintEngineImpl.java:152)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.withReadLock(ConnectedSonarLintEngineImpl.java:339)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.withReadLock(ConnectedSonarLintEngineImpl.java:329)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.analyze(ConnectedSonarLintEngineImpl.java:150)
	at org.sonarlint.eclipse.core.internal.server.Server.runAnalysis(Server.java:277)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.run(AnalyzeProjectJob.java:453)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.runAnalysisAndUpdateMarkers(AnalyzeProjectJob.java:204)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.doRun(AnalyzeProjectJob.java:160)
	at org.sonarlint.eclipse.core.internal.jobs.AbstractSonarProjectJob.runInWorkspace(AbstractSonarProjectJob.java:43)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by gquerret** [comment]
See last comment on issue #711. Can you try the fix ?

**Comment by clement-brodu** [comment]
The fix solves the issue. 
Thank you 👍
