### ISSUE TITLE
Sonarlint - Rule execution NPE

### ISSUE THREAD

**Issue by lneumeier** [Riverside-Software/sonar-openedge#711]
Hello,

I'm getting with the latest Sonarlint version errors and an incomplete list of issues. Sometimes I get for the same file 232 issues, sometimes 0, sometimes 16.

The exception is thrown on different rules. Unfortunately, the order of rules changes each time (this should be fixed?).

Here are three examples of the same file with same content.

```
570 milliseconds to generate ParseUnit
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.AvoidFortranOperators
Initializing metadata of file file:/D:/Entwickl/v410/src/basis/fibu/haushaltsplan.p
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.xref.checks.WholeIndexAnalyzer
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.WhereCanDo
ActiveRule - Internal key  - Repository rssw-oe - Rule org.sonar.plugins.openedge.checks.SharedObjectsAnalyzer
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.xref.checks.SortAccessWholeIndexAnalyzer
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.BackslashInIncludeFile
ActiveRule - Internal key  - Repository rssw-oe - Rule org.sonar.plugins.openedge.checks.LargeTransactionScope
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.OutdatedDigest
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.UsingStars
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.NoRoutineInWhere
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.FindNoError
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.VariableAssignedButNotRead
Error during rule execution for [path=D:\Entwickl\v410\src\basis\fibu\haushaltsplan.p]
java.lang.NullPointerException
	at org.sonarsource.sonarlint.core.container.analysis.filesystem.RelativePathPredicate.apply(RelativePathPredicate.java:45)
	at org.sonar.api.batch.fs.internal.OptimizedFilePredicateAdapter.apply(OptimizedFilePredicateAdapter.java:35)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at org.sonar.api.batch.fs.internal.DefaultFileSystem.inputFile(DefaultFileSystem.java:117)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.getInputFile(OpenEdgeProparseCheck.java:73)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.createIssue(OpenEdgeProparseCheck.java:85)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.reportIssue(OpenEdgeProparseCheck.java:128)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.reportIssue(OpenEdgeProparseCheck.java:117)
	at org.sonar.plugins.openedge.LicensedRule.reportIssue(Unknown Source)
	at eu.rssw.antlr.proparse.checks.VariableAssignedButNotRead.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.VariableAssignedButNotRead.execute(Unknown Source)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.sensorExecute(OpenEdgeProparseCheck.java:47)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:330)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:158)
	at org.sonarsource.sonarlint.core.analyzer.sensor.SensorWrapper.analyse(SensorWrapper.java:52)
	at org.sonarsource.sonarlint.core.analyzer.sensor.AllSensorsExecutor.executeSensor(AllSensorsExecutor.java:79)
	at org.sonarsource.sonarlint.core.analyzer.sensor.AllSensorsExecutor.execute(AllSensorsExecutor.java:67)
	at org.sonarsource.sonarlint.core.analyzer.sensor.PhaseExecutor.execute(PhaseExecutor.java:36)
	at org.sonarsource.sonarlint.core.container.analysis.AnalysisContainer.doAfterStart(AnalysisContainer.java:141)
	at org.sonarsource.sonarlint.core.container.ComponentContainer.startComponents(ComponentContainer.java:125)
	at org.sonarsource.sonarlint.core.container.ComponentContainer.execute(ComponentContainer.java:110)
	at org.sonarsource.sonarlint.core.container.storage.StorageAnalyzer.analyze(StorageAnalyzer.java:75)
	at org.sonarsource.sonarlint.core.container.storage.StorageContainerHandler.analyze(StorageContainerHandler.java:76)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.lambda$analyze$0(ConnectedSonarLintEngineImpl.java:152)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.withReadLock(ConnectedSonarLintEngineImpl.java:339)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.withReadLock(ConnectedSonarLintEngineImpl.java:329)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.analyze(ConnectedSonarLintEngineImpl.java:150)
	at org.sonarlint.eclipse.core.internal.server.Server.runAnalysis(Server.java:277)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.run(AnalyzeProjectJob.java:453)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.runAnalysisAndUpdateMarkers(AnalyzeProjectJob.java:204)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.doRun(AnalyzeProjectJob.java:160)
	at org.sonarlint.eclipse.core.internal.jobs.AbstractSonarProjectJob.runInWorkspace(AbstractSonarProjectJob.java:43)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

```
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.AbbreviatedTableName
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.WrongAssignWhen
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.SerializableError
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.ErrorHandlingDirective
Initializing metadata of file file:/D:/Entwickl/v410/src/basis/fibu/haushaltsplan.p
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.ReturnError
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.PublicVariable
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.xref.checks.TempTableWholeIndexAnalyzer
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.TableScanAndWhere
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.BackslashInIncludeFile
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.GlobalSharedVariable
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.UpperCaseKeywords
Error during rule execution for [path=D:\Entwickl\v410\src\basis\fibu\haushaltsplan.p]
java.lang.NullPointerException
	at org.sonarsource.sonarlint.core.container.analysis.filesystem.RelativePathPredicate.apply(RelativePathPredicate.java:45)
	at org.sonar.api.batch.fs.internal.OptimizedFilePredicateAdapter.apply(OptimizedFilePredicateAdapter.java:35)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at org.sonar.api.batch.fs.internal.DefaultFileSystem.inputFile(DefaultFileSystem.java:117)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.getInputFile(OpenEdgeProparseCheck.java:73)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.createIssue(OpenEdgeProparseCheck.java:85)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.reportIssue(OpenEdgeProparseCheck.java:128)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.execute(Unknown Source)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.sensorExecute(OpenEdgeProparseCheck.java:47)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:330)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:158)
	at org.sonarsource.sonarlint.core.analyzer.sensor.SensorWrapper.analyse(SensorWrapper.java:52)
	at org.sonarsource.sonarlint.core.analyzer.sensor.AllSensorsExecutor.executeSensor(AllSensorsExecutor.java:79)
	at org.sonarsource.sonarlint.core.analyzer.sensor.AllSensorsExecutor.execute(AllSensorsExecutor.java:67)
	at org.sonarsource.sonarlint.core.analyzer.sensor.PhaseExecutor.execute(PhaseExecutor.java:36)
	at org.sonarsource.sonarlint.core.container.analysis.AnalysisContainer.doAfterStart(AnalysisContainer.java:141)
	at org.sonarsource.sonarlint.core.container.ComponentContainer.startComponents(ComponentContainer.java:125)
	at org.sonarsource.sonarlint.core.container.ComponentContainer.execute(ComponentContainer.java:110)
	at org.sonarsource.sonarlint.core.container.storage.StorageAnalyzer.analyze(StorageAnalyzer.java:75)
	at org.sonarsource.sonarlint.core.container.storage.StorageContainerHandler.analyze(StorageContainerHandler.java:76)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.lambda$analyze$0(ConnectedSonarLintEngineImpl.java:152)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.withReadLock(ConnectedSonarLintEngineImpl.java:339)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.withReadLock(ConnectedSonarLintEngineImpl.java:329)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.analyze(ConnectedSonarLintEngineImpl.java:150)
	at org.sonarlint.eclipse.core.internal.server.Server.runAnalysis(Server.java:277)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.run(AnalyzeProjectJob.java:453)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.runAnalysisAndUpdateMarkers(AnalyzeProjectJob.java:204)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.doRun(AnalyzeProjectJob.java:160)
	at org.sonarlint.eclipse.core.internal.jobs.AbstractSonarProjectJob.runInWorkspace(AbstractSonarProjectJob.java:43)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
...
Rule rssw-oe:org.sonar.plugins.openedge.checks.SharedObjectsAnalyzer | time=0 ms
Execute Sensor: HTML
Found 232 issue(s)
Done in 685 ms
```

```
518 milliseconds to generate ParseUnit
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.VariableAssignedButNotRead
Error during rule execution for [path=D:\Entwickl\v410\src\basis\fibu\haushaltsplan.p]
java.lang.NullPointerException
	at org.sonarsource.sonarlint.core.container.analysis.filesystem.RelativePathPredicate.apply(RelativePathPredicate.java:45)
	at org.sonar.api.batch.fs.internal.OptimizedFilePredicateAdapter.apply(OptimizedFilePredicateAdapter.java:35)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at org.sonar.api.batch.fs.internal.DefaultFileSystem.inputFile(DefaultFileSystem.java:117)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.getInputFile(OpenEdgeProparseCheck.java:73)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.createIssue(OpenEdgeProparseCheck.java:85)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.reportIssue(OpenEdgeProparseCheck.java:128)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.reportIssue(OpenEdgeProparseCheck.java:117)
	at org.sonar.plugins.openedge.LicensedRule.reportIssue(Unknown Source)
	at eu.rssw.antlr.proparse.checks.VariableAssignedButNotRead.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.VariableAssignedButNotRead.execute(Unknown Source)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.sensorExecute(OpenEdgeProparseCheck.java:47)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:330)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:158)
	at org.sonarsource.sonarlint.core.analyzer.sensor.SensorWrapper.analyse(SensorWrapper.java:52)
	at org.sonarsource.sonarlint.core.analyzer.sensor.AllSensorsExecutor.executeSensor(AllSensorsExecutor.java:79)
	at org.sonarsource.sonarlint.core.analyzer.sensor.AllSensorsExecutor.execute(AllSensorsExecutor.java:67)
	at org.sonarsource.sonarlint.core.analyzer.sensor.PhaseExecutor.execute(PhaseExecutor.java:36)
	at org.sonarsource.sonarlint.core.container.analysis.AnalysisContainer.doAfterStart(AnalysisContainer.java:141)
	at org.sonarsource.sonarlint.core.container.ComponentContainer.startComponents(ComponentContainer.java:125)
	at org.sonarsource.sonarlint.core.container.ComponentContainer.execute(ComponentContainer.java:110)
	at org.sonarsource.sonarlint.core.container.storage.StorageAnalyzer.analyze(StorageAnalyzer.java:75)
	at org.sonarsource.sonarlint.core.container.storage.StorageContainerHandler.analyze(StorageContainerHandler.java:76)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.lambda$analyze$0(ConnectedSonarLintEngineImpl.java:152)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.withReadLock(ConnectedSonarLintEngineImpl.java:339)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.withReadLock(ConnectedSonarLintEngineImpl.java:329)
	at org.sonarsource.sonarlint.core.ConnectedSonarLintEngineImpl.analyze(ConnectedSonarLintEngineImpl.java:150)
	at org.sonarlint.eclipse.core.internal.server.Server.runAnalysis(Server.java:277)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.run(AnalyzeProjectJob.java:453)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.runAnalysisAndUpdateMarkers(AnalyzeProjectJob.java:204)
	at org.sonarlint.eclipse.core.internal.jobs.AnalyzeProjectJob.doRun(AnalyzeProjectJob.java:160)
	at org.sonarlint.eclipse.core.internal.jobs.AbstractSonarProjectJob.runInWorkspace(AbstractSonarProjectJob.java:43)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

1 files proparse'd, 0 XML files, 0 listing files, 0 failure(s), 0 NCLOCs
AST Generation | time=518 ms
XML Parsing    | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.AbbreviatedTableName | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.AvoidFortranOperators | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.BackslashCurlyBrace | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.BackslashInIncludeFile | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ClassNameCasing | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ColonForBlock | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.DosKeyword | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.DotComment | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.EmptyStatement | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.EndType | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ErrorHandlingDirective | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.FindNoError | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.GlobalSharedVariable | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.HiddenVariable | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.LinesTooLong | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.LogRethrowException | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NoReturnInFinally | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NoReturnInFuncOrMethod | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NoRoutineInLoop | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NoRoutineInWhere | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.NoUndo | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.OneStatementPerLine | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.OutdatedDigest | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.PublicVariable | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ReadkeyKeyword | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.RecidKeyword | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ReturnError | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.SerializableError | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ShareLock | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.SharedVariable | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.SubstituteLongChar | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.TableScanAndWhere | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.TabsIndent | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.ToDoTracker | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UndoWithoutOption | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UnixKeyword | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UnusedBuffer | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UnusedVariable | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UpperCaseKeywords | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.UsingStars | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.VariableAssignedButNotRead | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.VariableReadButNotAssigned | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.WhereCanDo | time=0 ms
Rule rssw-oe-main:eu.rssw.antlr.proparse.checks.WrongAssignWhen | time=0 ms
Rule rssw-oe-main:eu.rssw.xref.checks.SortAccessAnalyzer | time=0 ms
Rule rssw-oe-main:eu.rssw.xref.checks.SortAccessWholeIndexAnalyzer | time=0 ms
Rule rssw-oe-main:eu.rssw.xref.checks.TempTableSortAccessWholeIndexAnalyzer | time=0 ms
Rule rssw-oe-main:eu.rssw.xref.checks.TempTableWholeIndexAnalyzer | time=0 ms
Rule rssw-oe-main:eu.rssw.xref.checks.WholeIndexAnalyzer | time=0 ms
Rule rssw-oe:org.sonar.plugins.openedge.checks.ClumsySyntax | time=0 ms
Rule rssw-oe:org.sonar.plugins.openedge.checks.LargeTransactionScope | time=0 ms
Rule rssw-oe:org.sonar.plugins.openedge.checks.SharedObjectsAnalyzer | time=0 ms
Execute Sensor: HTML
Found 0 issue(s)
Done in 607 ms
```

**Comment by gquerret** [comment]
Sonar-Openedge 2.5.1 and SonarLint 3.6.1012 ?

**Comment by lneumeier** [comment]
Yes.

**Comment by gquerret** [comment]
Can you try [this version](https://ci.rssw.eu/job/sonar-openedge/job/bugfix%252FSOE-711-SonarLintNPE/lastSuccessfulBuild/artifact/openedge-plugin/target/sonar-openedge-plugin-2.5.2-SNAPSHOT.jar) ? That should solve the issue, but just would like a confirmation. You can stay with the same version of riverside-rules plugin.
Unless you find additional issues, this version will be released as a hotfix next week.

**Comment by lneumeier** [comment]
Thank you, that worked!
