### ISSUE TITLE
Unable to include \{ in string

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#72]
_Reported by email_
This code can be compiled and executed:

```
message "Hello \{ world".
```

But it throws a RuntimeException :

```
org.prorefactor.core.ProparseRuntimeException: Proparse error. Infinite loop caught by preprocessor.
        at org.prorefactor.proparse.Preprocessor.getRawChar(Preprocessor.java:411)                  
        at org.prorefactor.proparse.Preprocessor.getChar(Preprocessor.java:263)                     
        at org.prorefactor.proparse.Preprocessor.macroReference(Preprocessor.java:526)              
        at org.prorefactor.proparse.Preprocessor.getChar(Preprocessor.java:284)                     
        at org.prorefactor.proparse.Lexer.getChar(Lexer.java:962)                                   
        at org.prorefactor.proparse.Lexer.quotedString(Lexer.java:410)                              
        at org.prorefactor.proparse.Lexer.nextToken(Lexer.java:129)                                 
        at org.prorefactor.proparse.Postlexer.getNextToken(Postlexer.java:103)                      
        at org.prorefactor.proparse.Postlexer.nextToken(Postlexer.java:51)                          
        at org.prorefactor.proparse.TokenList.build(TokenList.java:51)                              
        at org.prorefactor.proparse.DoParse.doParse(DoParse.java:130)                               
        at org.prorefactor.proparse.DoParse.doParse(DoParse.java:102)                               
        at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:145)                           
        at org.prorefactor.core.unittest.BugFixTest.test01(BugFixTest.java:59)                      
```

**Comment by gquerret** [comment]
Fixed in pull request, looking for any regression
