### ISSUE TITLE
Parser error - Valid line offset

### ISSUE THREAD

**Issue by lneumeier** [Riverside-Software/sonar-openedge#750]
Hello,

I'm getting for various files the following errors:

```
Line 101:
       	 WHERE hueleb.jahr = "20" + substring ( abgaben.huelnr, 1, 2 ) /* Jahr 3000 Fehler ! */

ERROR: Error during rule execution for src/basis/tm/korr-bv_del.p
java.lang.IllegalArgumentException: 36 is not a valid line offset for pointer. File src/basis/tm/korr-bv_del.p has 21 character(s) at line 101
	at org.sonar.api.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:339)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:272)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:287)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.createIssue(OpenEdgeProparseCheck.java:96)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.reportIssue(OpenEdgeProparseCheck.java:128)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.UpperCaseKeywords.execute(Unknown Source)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.sensorExecute(OpenEdgeProparseCheck.java:47)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:379)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:174)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:400)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:395)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:358)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

```

**Comment by movedoa** [comment]
I am having the same issue in one file.

```
[sonar:sonar] java.lang.IllegalArgumentException: 15 is not a valid line offset for pointer. File Common/Doc/DocDiscount.cls has 0 character(s) at line 21368
[sonar:sonar] 	at org.sonar.api.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
[sonar:sonar] 	at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:339)
[sonar:sonar] 	at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:272)
[sonar:sonar] 	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:287)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.createIssue(OpenEdgeProparseCheck.java:96)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.reportIssue(OpenEdgeProparseCheck.java:128)
[sonar:sonar] 	at eu.rssw.antlr.proparse.checks.SortAccessAnalyzer.execute(Unknown Source)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.sensorExecute(OpenEdgeProparseCheck.java:47)
[sonar:sonar] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:379)
[sonar:sonar] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:174)
[sonar:sonar] 	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
[sonar:sonar] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
[sonar:sonar] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
[sonar:sonar] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
[sonar:sonar] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
[sonar:sonar] 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:400)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:395)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:358)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
[sonar:sonar] 	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
[sonar:sonar] 	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
[sonar:sonar] 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
[sonar:sonar] 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
[sonar:sonar] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[sonar:sonar] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:498)
[sonar:sonar] 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
[sonar:sonar] 	at com.sun.proxy.$Proxy2.execute(Unknown Source)
[sonar:sonar] 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
[sonar:sonar] 	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
[sonar:sonar] 	at org.sonarsource.scanner.ant.SonarQubeTask.launchAnalysis(SonarQubeTask.java:107)
[sonar:sonar] 	at org.sonarsource.scanner.ant.SonarQubeTask.execute(SonarQubeTask.java:88)
[sonar:sonar] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[sonar:sonar] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:498)
[sonar:sonar] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[sonar:sonar] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[sonar:sonar] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[sonar:sonar] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[sonar:sonar] 	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[sonar:sonar] 	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:440)
[sonar:sonar] 	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
[sonar:sonar] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[sonar:sonar] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[sonar:sonar] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.lang.reflect.Method.invoke(Method.java:498)
[sonar:sonar] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[sonar:sonar] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[sonar:sonar] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[sonar:sonar] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
[sonar:sonar] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[sonar:sonar] 	at org.apache.tools.ant.Main.runBuild(Main.java:851)
[sonar:sonar] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
[sonar:sonar] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
[sonar:sonar] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
```

**Comment by gquerret** [comment]
Can you verify if new line characters are consistent in this file ?

**Comment by movedoa** [comment]
I could not find any inconsistencies with CR/LF. (But i am not sure how to 100% verify that)
But i noticed that this does not happen in SonarLint it only happens with the ant task for some reason.

**Comment by movedoa** [comment]
Quick Update: It wasn't inconsistent cr/lf but the file had a broken character in it.
I removed the broken character and now the error is gone.

**Comment by gquerret** [comment]
@lneumeier Did you check the newline characters ? Just in case, you can use Notepad++, and display "hidden" characters with "View -> Show symbols -> Show all characters".
You should also check if all characters in the file match the encoding specified in sonar.encoding.
