### ISSUE TITLE
Problem with DB alias

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#82]
Can be seen during PCT analysis :
```
[sonar:sonar] Error during code parsing for src/progress/pct/v10/_dmpincr.p
[sonar:sonar] org.sonar.plugins.openedge.api.org.prorefactor.refactor.RefactorException:  C:\Users\gquer\Projets\pct2\src\progress\prodict/dump/dumpvars10.i:61: Unknown table name: DICTDB2._Field
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:148) ~[na:na]
[sonar:sonar] 	at org.sonar.plugins.openedge.api.org.prorefactor.treeparser.ParseUnit.treeParser01(ParseUnit.java:177) ~[na:na]
...
```
Analysis properties :
```
<property name="sonar.oe.databases" value="dictdb.df" />
<property name="sonar.oe.aliases"   value="dictdb,dictdb2" />
```
Problem happens only on metaschema tables in PCT ; raise priority if issue is reproduced with real tables.

**Comment by gquerret** [comment]
Fixed in master
