### ISSUE TITLE
java.lang.ClassCastException: class java.lang.Object cannot be cast to class java.lang.String

### ISSUE THREAD

**Issue by stefandrissen** [Riverside-Software/sonar-openedge#840]
Since upgrade to 2.9.0 (although it may be that I am looking at this log more often):
````
[sonar:sonar] Error during rule execution for system/modu/selpack.p
[sonar:sonar] java.lang.ClassCastException: class java.lang.Object cannot be cast to class java.lang.String (java.lang.Object and java.lang.String are in module java.base of loader 'bootstrap')
[sonar:sonar] 	at eu.rssw.cabl.security.HardCodedCredentials.a(Unknown Source)
[sonar:sonar] 	at eu.rssw.cabl.security.HardCodedCredentials.a(Unknown Source)
[sonar:sonar] 	at eu.rssw.cabl.security.HardCodedCredentials.execute(Unknown Source)
[sonar:sonar] 	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.sensorExecute(OpenEdgeProparseCheck.java:50)
[sonar:sonar] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:414)
[sonar:sonar] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:192)
[sonar:sonar] 	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
[sonar:sonar] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
[sonar:sonar] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
[sonar:sonar] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
[sonar:sonar] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
[sonar:sonar] 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:400)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:395)
[sonar:sonar] 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:358)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
[sonar:sonar] 	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
[sonar:sonar] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
[sonar:sonar] 	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
[sonar:sonar] 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
[sonar:sonar] 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
[sonar:sonar] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[sonar:sonar] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[sonar:sonar] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[sonar:sonar] 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
[sonar:sonar] 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
[sonar:sonar] 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
[sonar:sonar] 	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
[sonar:sonar] 	at org.sonarsource.scanner.ant.SonarQubeTask.launchAnalysis(SonarQubeTask.java:107)
[sonar:sonar] 	at org.sonarsource.scanner.ant.SonarQubeTask.execute(SonarQubeTask.java:88)
[sonar:sonar] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
[sonar:sonar] 	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[sonar:sonar] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[sonar:sonar] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[sonar:sonar] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[sonar:sonar] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[sonar:sonar] 	at org.apache.tools.ant.Target.execute(Target.java:435)
[sonar:sonar] 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
[sonar:sonar] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[sonar:sonar] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
[sonar:sonar] 	at org.apache.tools.ant.Main.runBuild(Main.java:853)
[sonar:sonar] 	at org.apache.tools.ant.Main.startAnt(Main.java:235)
[sonar:sonar] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
[sonar:sonar] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
[sonar:sonar] 208 files proparse'd, 0 XML files, 0 listing files, 0 failure(s), 76184 NCLOCs
````
Based on the error could this be triggering it?
````
PROCEDURE ConnectAppServer PRIVATE:
   DEFINE       OUTPUT  PARAMETER o_cpassword   AS CHARACTER   NO-UNDO INITIAL ?.
````

**Comment by gquerret** [comment]
It comes from initial values of CHARACTER variables. I don't know if that's a very large procedure or not, but do you have some CHAR variables with "non-standard" values ?
The rule makes the incorrect assumption that the initial value will return a String for every variable. I'll fix this wrong assumption.

**Comment by gquerret** [comment]
I see your update, thanks for the example. I'll reproduce and fix the problem.

**Comment by gquerret** [comment]
Fixed in develop
