### ISSUE TITLE
NullPointerException in DefaultSQLWidth rule

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#85]
```
[sonar:sonar] Sensor OpenEdgeDBRulesSensor

BUILD FAILED
<http://xxxx:8080/job/yyy%20Library%20116-64%20SonarSource/ws/sonarsource.xml>:262: java.lang.NullPointerException
        at eu.rssw.database.checks.DefaultSqlWidthAnalyzer.execute(Unknown Source)
        at org.sonar.plugins.openedge.sensor.OpenEdgeDBRulesSensor.execute(OpenEdgeDBRulesSensor.java:80)
...
```

**Comment by gquerret** [comment]
Fixed in riverside-rules plugin, will be available in 1.0.8
