### ISSUE TITLE
Connect to SonarQube error: Unable to test connection:org/sonarsource/sonarlint/core/client/api/common/Language

### ISSUE THREAD

**Issue by zipingwang** [Riverside-Software/sonar-openedge#864]
Installed version 5.5.1507 on Progress Developer Studio 4.5.2-OpenEdge Release 11.7.5
When coonect to sonarQube, got een error:
Unable to test connection:org/sonarsource/sonarlint/core/client/api/common/Language
Version 4.2.1200  works well.

Error detail:
```
org/sonarsource/sonarlint/core/client/api/common/Language
java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:420)
	at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:1002)
	at org.sonarlint.eclipse.ui.internal.binding.wizard.connection.ServerConnectionWizard.testConnection(ServerConnectionWizard.java:311)
	at org.sonarlint.eclipse.ui.internal.binding.wizard.connection.ServerConnectionWizard.handlePageChanging(ServerConnectionWizard.java:255)
	at org.eclipse.jface.wizard.WizardDialog$10.run(WizardDialog.java:1554)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.wizard.WizardDialog.firePageChanging(WizardDialog.java:1551)
	at org.eclipse.jface.wizard.WizardDialog.doPageChanging(WizardDialog.java:899)
	at org.eclipse.jface.wizard.WizardDialog.showPage(WizardDialog.java:1186)
	at org.eclipse.jface.wizard.WizardDialog.nextPressed(WizardDialog.java:885)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:425)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
Caused by: java.lang.NoClassDefFoundError: org/sonarsource/sonarlint/core/client/api/common/Language
	at org.sonarlint.eclipse.core.internal.engine.connected.ConnectedEngineFacade.getConfigBuilderNoCredentials(ConnectedEngineFacade.java:525)
	at org.sonarlint.eclipse.core.internal.engine.connected.ConnectedEngineFacade.testConnection(ConnectedEngineFacade.java:479)
	at org.sonarlint.eclipse.ui.internal.binding.wizard.connection.ServerConnectionTestJob.run(ServerConnectionTestJob.java:53)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: java.lang.ClassNotFoundException: org.sonarsource.sonarlint.core.client.api.common.Language cannot be found by org.sonarlint.eclipse.core_5.5.1507
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:439)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more
```

**Comment by gquerret** [comment]
I suspect it's an installation problem, as the class is available in the package. Could you uninstall any SonarLint version installed on PDSOE, then do a clean reinstall of 5.5.1507 ?

**Comment by zipingwang** [comment]
First uninstall the existing SonarLint, then reinstall the version 5.5.1507
Still got an error when restarting Progress Developer studio
An internal error occurred during: "SonarLint Core startup".
org/sonarsource/sonarlint/core/client/api/common/Language

![image](https://user-images.githubusercontent.com/9693956/105359702-07742000-5bf8-11eb-9e0b-48f475328487.png)

**Comment by gquerret** [comment]
Can you include a screenshot of the installation details ? Help menu -> Installation details

**Comment by zipingwang** [comment]
![image](https://user-images.githubusercontent.com/9693956/105362538-4e174980-5bfb-11eb-9b49-07d88f4ec007.png)

**Comment by zipingwang** [comment]
![image](https://user-images.githubusercontent.com/9693956/105362668-71da8f80-5bfb-11eb-9875-450d6813f762.png)

**Comment by gquerret** [comment]
5.5.1507 was not tested with this specific patch level, but with 11.7.8. The Eclipse version didn't change in the mean time, so I don't think there could be an impact, but I'll perhaps try to test on this specific version.
Among other solutions, did you try to start PDSOE in Clean mode ? If that still doesn't work, can you uninstall SonarLint again, close PDSOE, and manually remove all `org.sonarlint.*` and `org.sonarsource.*` files from `%DLC%\oeide\eclipse\plugins`, then restart and re-install ? It should be enough to clean everything.

**Comment by zipingwang** [comment]
After delete all org.sonarlint.* and org.sonarsource.* files, it works.
Thanks!

![image](https://user-images.githubusercontent.com/9693956/105369251-a867d880-5c02-11eb-8b55-4ad3a07037b8.png)
