### ISSUE TITLE
java.lang.UnsupportedOperationException: hasRelativePath in Developer Studio

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#868]
Separate issue reported in issue #866. Since the upgrade to 5.5.1507, those stack traces are always reported when issues are found in include files:
```
ActiveRule - Internal key  - Repository rssw-oe-main - Rule eu.rssw.antlr.proparse.checks.**VariableReadButNotAssigned**
Error during rule execution for [uri=file:/C:/Workspace/glims_dev_pro/glims-abl-sources/man/**bd_ord2.p**]
java.lang.UnsupportedOperationException: hasRelativePath
	at org.sonarsource.sonarlint.core.container.analysis.filesystem.DefaultFilePredicates.hasRelativePath(DefaultFilePredicates.java:67)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.getInputFile(OpenEdgeProparseCheck.java:284)
```

**Comment by gquerret** [comment]
Fixed in release 2.12.1
