### ISSUE TITLE
IllegalArgumentException in CommentedOutCode rule

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#891]
On behalf of PT

Stack trace in analysis log:
```
ERROR: Error during rule execution for lib/xxx.p
java.lang.IllegalArgumentException: 56 is not a valid line for pointer. File lib/xxx.p has 40 line(s)
	at org.sonar.api.utils.Preconditions.checkArgument(Preconditions.java:43)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:336)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:272)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.selectLine(DefaultInputFile.java:295)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeCheck.reportIssue(OpenEdgeCheck.java:96)
	at eu.rssw.antlr.proparse.checks.CommentedOutCode$ParseHiddenTokensWalker.a(Unknown Source)
	at eu.rssw.antlr.proparse.checks.CommentedOutCode$ParseHiddenTokensWalker.visitNode(Unknown Source)
	at org.prorefactor.core.JPNode.walk(JPNode.java:794)
	at org.prorefactor.core.JPNode.walk(JPNode.java:796)
	at eu.rssw.antlr.proparse.checks.CommentedOutCode.execute(Unknown Source)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.sensorExecute(OpenEdgeProparseCheck.java:57)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:425)
```

**Comment by gquerret** [comment]
Can be reproduced with this main file:
```
{ lib/inc.i }
message "xxx".
```

And include file `lib/inc.i`:
```
/***
 * function f1 returns character ( xxx as integer, yyy as integer ) in super.
 ***/
```

**Comment by gquerret** [comment]
Fixed in develop
