### ISSUE TITLE
ERROR: Error during SonarQube Scanner execution

### ISSUE THREAD

**Issue by Gpandye** [Riverside-Software/sonar-openedge#9]
HI,

i am using sonar runner, i tried with 10 programs, it did worked and generated analysis, i then ran with large set of programs and got below error -
```
ERROR: Error during SonarQube Scanner execution
java.lang.NumberFormatException: For input string: "-("
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:492)
        at java.lang.Integer.parseInt(Integer.java:527)
        at eu.rssw.listing.ListingParser.parseTransactionLine(ListingParser.java:105)
        at eu.rssw.listing.ListingParser.parseFile(ListingParser.java:92)
        at eu.rssw.listing.ListingParser.<init>(ListingParser.java:22)
        at org.sonar.plugins.openedge.sensor.OpenEdgeListingSensor.analyse(OpenEdgeListingSensor.java:77)
        at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
        at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
        at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:102)
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:185)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:120)
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:264)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:259)
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:249)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.batch.scan.ProjectScanContainer.startComponents(ProjectScanContainer.java:127)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:120)
        at org.sonar.batch.task.ScanTask.execute(ScanTask.java:55)
        at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:120)
        at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:122)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
        at org.sonar.runner.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:67)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.sonar.runner.impl.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:61)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:274)
        at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:165)
        at org.sonar.runner.api.EmbeddedRunner.runAnalysis(EmbeddedRunner.java:152)
        at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:133)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:82)
        at org.sonarsource.scanner.cli.Main.main(Main.java:66)
ERROR:
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging
```
I searched for "-(" character in my programs, found 4 programs, so i did ran for those programs only, it ran without any error.

Any idea? what is the issue?

**Comment by jakejustus** [comment]
If you're using the Ant task, could you execute Ant with the -v option ? And if using the SonarRunner task, could you add argument -X ?
In both cases, you'll end up with a debug output ; the line just before the stack trace will say something like :
```
[java] 16:37:18.361 DEBUG - Looking for listing of src/procedures/sample/test1.p
```
The listing file is found in `${buildDir}/.pct/procedures/sample/test1.p` ; would you then be able to attach this file ?

**Comment by Gpandye** [comment]
Hi Gilles,

I analysed more with -X parameter and found the root cause for this, this issue is coming because of listing file, as this file is having more than 32767 lines, in that case, the line numbers in the listing portion go negative, i.e., 32768 = -32768, 32769 = -32767 ... and first occurrence is added as - 

...e_proc_testoroc.p   -( Do          No                                    
...e_proc_testoroc.p -32666 Procedure   No   Procedure P3-HIST         
    Buffers: OLDTABLE
             TABLE 

More is in attached image.

As i removed '-(' character and replaced it with some number like '-32637'; and then ran sonar-runner, it worked.

So i think a patch is required to ignore this character in listing file while importing, or do let me know if some workaround is there like to have a keyword ignore list when running sonar-runner.

![sonarerror_codefile](https://cloud.githubusercontent.com/assets/18287928/14316422/8541efd6-fc20-11e5-84a7-e61f92efc198.JPG)

**Comment by jakejustus** [comment]
Thanks for your investigation. In fact, the negative number problem was caught some time ago, but AFAIK we didn't see this issue where there's no line number at all. The dev version has been updated in  order to catch the exception and not to fail the analysis.

**Comment by Gpandye** [comment]
Thanks for the update. as you said The dev version has been updated in order to catch the exception and not to fail the analysis, you men to say this keyword exception as well '-(' ?

Do let me know when this patch will be available to test.

**Comment by jakejustus** [comment]
If you're using http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+Jenkins
Then you should be able to add -X in the JVM Options.

**Comment by jakejustus** [comment]
Yes, the "-(" case will be handled. It should be available tomorrow morning
