### ISSUE TITLE
Regression with 2.14.8 and SonarLint on PDSOE 11.7

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#945]
On behalf of Casol

Analyzing a .cls file leads to this exception:
```
!ENTRY org.eclipse.core.jobs 4 2 2022-02-23 10:55:20.751
!MESSAGE An internal error occurred during: "SonarLint processing file /TestProject/src/MyClass.cls".
!STACK 0
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at eu.rssw.pct.PLReader.readEntry(PLReader.java:140)
	at eu.rssw.pct.PLReader.readFileList(PLReader.java:81)
	at eu.rssw.pct.PLReader.getFileList(PLReader.java:57)
	at eu.rssw.pct.PLReader.getEntry(PLReader.java:62)
	at org.sonar.plugins.openedge.foundation.OpenEdgeSettings.getRCode2(OpenEdgeSettings.java:431)
	at org.sonar.plugins.openedge.foundation.OpenEdgeSettings.parseHierarchy(OpenEdgeSettings.java:258)
	at org.sonar.plugins.openedge.foundation.OpenEdgeSettings.parseHierarchy(OpenEdgeSettings.java:249)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:262)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:176)
    ...
```

**Comment by gquerret** [comment]
In order to keep compatibility with Java 8, the line `channel.read(buf1.position(0));` was changed to `channel.read((ByteBuffer) buf1.position(0));`. But it looks like the bytecode generated by JDK11 still references a method which doesn't exist in Java 8, leading to the exception mentioned in initial post.

Project will be built with JDK8 (instead of Java 11 with Java 8 target), until full migration to Java 11.

**Comment by gquerret** [comment]
Fixed in develop
