### ISSUE TITLE
ClassCastException

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#955]
On behalf of RITS, issue is visible since migration from 2.12.1 to 2.14.10

This code block throws an exception:
```
define stream s1.
define frame f1 xx like customer.name.
```

```
java.lang.ClassCastException: org.prorefactor.treeparser.symbols.Stream cannot be cast to org.prorefactor.treeparser.Primative
	at org.prorefactor.treeparser.TreeParserVariableDefinition.defLike(TreeParserVariableDefinition.java:2170)
	at org.prorefactor.treeparser.TreeParserVariableDefinition.exitFormatOption(TreeParserVariableDefinition.java:1490)
	at org.prorefactor.proparse.antlr4.Proparse$FormatOptionContext.exitRule(Proparse.java:37919)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:62)
```
Looks like the `like` attribute is handled incorrectly.

**Comment by gquerret** [comment]
Does not throw exception since commit 4cdce8f, but displays an log message.

**Comment by gquerret** [comment]
Fixed in develop
