### ISSUE TITLE
NullPointerException during code analysis

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#969]
On behalf of QAD

```
12-May-2022 01:34:36 | [sonar:sonar] Sensor OpenEdgeProparseSensor [cabllicense] (done) | time=1724ms
12-May-2022 01:34:36 | [sonar:sonar] Sensor OpenEdgeDBRulesSensor [cabllicense]
12-May-2022 01:34:36 | [echo] Sonar scan failed with the following error, but this will not fail the build
12-May-2022 01:34:36 | [echo] /dr01/bamboo-agent-home/xml-data/build-dir/XXXX/bl.build.xml:2038: java.lang.NullPointerException
```

**Comment by gquerret** [comment]
Problem happened after migration to 2.15.0. Stack trace wasn't directly available, but was found later:
```
java.lang.NullPointerException
        at eu.rssw.antlr.database.DumpFileVisitor.visitFieldLabel(DumpFileVisitor.java:122)
        at eu.rssw.antlr.database.DumpFileVisitor.visitFieldLabel(DumpFileVisitor.java:67)
        at eu.rssw.antlr.database.DumpFileGrammarParser$FieldLabelContext.accept(DumpFileGrammarParser.java:3505)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at eu.rssw.antlr.database.DumpFileVisitor.visitAddField(DumpFileVisitor.java:108)
        at eu.rssw.antlr.database.DumpFileVisitor.visitAddField(DumpFileVisitor.java:67)
        at eu.rssw.antlr.database.DumpFileGrammarParser$AddFieldContext.accept(DumpFileGrammarParser.java:2922)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at eu.rssw.antlr.database.DumpFileGrammarBaseVisitor.visitDump_type(DumpFileGrammarBaseVisitor.java:27)
        at eu.rssw.antlr.database.DumpFileGrammarParser$Dump_typeContext.accept(DumpFileGrammarParser.java:322)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visitChildren(AbstractParseTreeVisitor.java:46)
        at eu.rssw.antlr.database.DumpFileGrammarBaseVisitor.visitDump(DumpFileGrammarBaseVisitor.java:20)
        at eu.rssw.antlr.database.DumpFileGrammarParser$DumpContext.accept(DumpFileGrammarParser.java:216)
        at org.antlr.v4.runtime.tree.AbstractParseTreeVisitor.visit(AbstractParseTreeVisitor.java:18)
        at eu.rssw.antlr.database.DumpFileUtils.getDatabaseDescription(DumpFileUtils.java:96)
        at org.sonar.plugins.openedge.foundation.OpenEdgeSettings.readSchemaFromProp1(OpenEdgeSettings.java:734)
        at org.sonar.plugins.openedge.foundation.OpenEdgeSettings.readSchema(OpenEdgeSettings.java:783)
        at org.sonar.plugins.openedge.foundation.OpenEdgeSettings.getProparseSession(OpenEdgeSettings.java:630)
        at org.sonar.plugins.openedge.foundation.OpenEdgeSettings.getProparseSessions(OpenEdgeSettings.java:591)
        at org.sonar.plugins.openedge.sensor.OpenEdgeCodeColorizer.execute(OpenEdgeCodeColorizer.java:66)
```

**Comment by gquerret** [comment]
Regression introduced in version 2.15 in the DF parser, when field definition has this attribute:
```
LABEL ?
```

**Comment by gquerret** [comment]
Fixed in develop
