### ISSUE TITLE
Proparse Error - ClassCastException

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#975]
On behalf of NCC

Parser error found multiple times during code scanning, with this stack trace:
```
ERROR: Parser error in 'src/main/abl/....'
java.lang.ClassCastException: class org.prorefactor.treeparser.symbols.TableBuffer cannot be cast to class org.prorefactor.treeparser.Primative (org.prorefactor.treeparser.symbols.TableBuffer and org.prorefactor.treeparser.Primative are in unnamed module of loader org.sonar.classloader.ClassRealm @1d81e101)
	at org.prorefactor.treeparser.TreeParserVariableDefinition.defLike(TreeParserVariableDefinition.java:2178)
	at org.prorefactor.treeparser.TreeParserVariableDefinition.exitFormatOption(TreeParserVariableDefinition.java:1498)
	at org.prorefactor.proparse.antlr4.Proparse$FormatOptionContext.exitRule(Proparse.java:36715)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:62)
```

Invalid code has not been identified yet.

OE Plugin 2.15

**Comment by gquerret** [comment]
Improved error message in this case. New issue will be opened with additional details.
