### ISSUE TITLE
ClassCastException in NestedDo rule

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#976]
On behalf of NCC

The NestedDo rule triggers a ClassCastException:
```
ERROR: Error during rule execution for src/main/abl/...
java.lang.ClassCastException: class org.prorefactor.core.JPNode cannot be cast to class org.prorefactor.core.nodetypes.FieldRefNode (org.prorefactor.core.JPNode and org.prorefactor.core.nodetypes.FieldRefNode are in unnamed module of loader org.sonar.classloader.ClassRealm @30cdae70)
	at eu.rssw.antlr.proparse.checks.NestedDo.execute(SourceFile:1028)
	at org.sonar.plugins.openedge.api.checks.OpenEdgeProparseCheck.sensorExecute(OpenEdgeProparseCheck.java:57)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:402)
	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:176)
	...
```

**Comment by gquerret** [comment]
Comment added in rule source code ; first child can be an IExpression instead of FieldRefNode (array access for example).

**Comment by gquerret** [comment]
Fixed in develop
