### ISSUE TITLE
Proparse error on package-protected constructor

### ISSUE THREAD

**Issue by gquerret** [Riverside-Software/sonar-openedge#978]
Hi! Getting this error from code parsing this code. The unique thing is the PACKAGE-PROTECTED. Other classes works fine.

```
    CONSTRUCTOR PACKAGE-PROTECTED MyClassName( ):
        
        SUPER( ).
        
    END CONSTRUCTOR.
```

```
sonar.scanner.Twin360BackEnd:
     [exec] INFO: Scanner configuration file: D:\TWIN360\sonar-scanner-4.7.0.2747-windows\bin\..\conf\sonar-scanner.properties
     [exec] INFO: Project root configuration file: D:\Workspace\SA-SE-TwinBatch\TWIN360Agile\Branches\Development\MainFuture\Twin360BackEnd\sonar-project.properties
     [exec] INFO: SonarScanner 4.7.0.2747
     [exec] INFO: Java 11.0.14.1 Eclipse Adoptium (64-bit)
     [exec] INFO: Windows Server 2019 10.0 amd64
     [exec] INFO: User cache: C:\Users\SA-SE-TwinBatch\.sonar\cache
     [exec] INFO: Scanner configuration file: D:\TWIN360\sonar-scanner-4.7.0.2747-windows\bin\..\conf\sonar-scanner.properties
     [exec] INFO: Project root configuration file: D:\Workspace\SA-SE-TwinBatch\TWIN360Agile\Branches\Development\MainFuture\Twin360BackEnd\sonar-project.properties
     [exec] INFO: Analyzing on SonarQube server 8.9.7
     [exec] INFO: Default locale: "en_US", source code encoding: "iso8859-1"
     [exec] INFO: Load global settings
     [exec] INFO: Load global settings (done) | time=210ms
     [exec] INFO: Server id: 61CE5E40-AX9F18SstBCNrSkcl_mA
     [exec] INFO: User cache: C:\Users\SA-SE-TwinBatch\.sonar\cache
     [exec] INFO: Load/download plugins
     [exec] INFO: Load plugins index
     [exec] INFO: Load plugins index (done) | time=79ms
     [exec] INFO: Load/download plugins (done) | time=450ms
     [exec] INFO: Process project properties
     [exec] INFO: Process project properties (done) | time=13ms
     [exec] INFO: Execute project builders
     [exec] INFO: Execute project builders (done) | time=1ms
     [exec] INFO: Project key: Twin360BackEnd
     [exec] INFO: Base dir: D:\Workspace\SA-SE-TwinBatch\TWIN360Agile\Branches\Development\MainFuture\Twin360BackEnd
     [exec] INFO: Working dir: D:\Workspace\SA-SE-TwinBatch\TWIN360Agile\Branches\Development\MainFuture\Twin360BackEnd\.scannerwork
     [exec] INFO: Load project settings for component key: 'Twin360BackEnd'
     [exec] INFO: Load project settings for component key: 'Twin360BackEnd' (done) | time=175ms
     [exec] INFO: Load quality profiles
     [exec] INFO: Load quality profiles (done) | time=67ms
     [exec] INFO: Load active rules
     [exec] INFO: Load active rules (done) | time=2099ms
     [exec] WARN: SCM provider autodetection failed. Please use "sonar.scm.provider" to define SCM of your project, or disable the SCM Sensor in the project settings.
     [exec] INFO: Indexing files...
     [exec] INFO: Project configuration:
     [exec] INFO:   Excluded sources for duplication: df/**
     [exec] INFO: 1568 files indexed
     [exec] INFO: Quality profile for oe: Sonar way (Twin360)
     [exec] INFO: Quality profile for oedb: Sonar way (extended)
     [exec] INFO: Quality profile for xml: Sonar way
     [exec] INFO: ------------- Run sensors on module Twin360BackEnd
     [exec] INFO: Load metrics repository
     [exec] INFO: Load metrics repository (done) | time=204ms
     [exec] INFO: Sensor CSS Rules [cssfamily]
     [exec] INFO: No CSS, PHP, HTML or VueJS files are found in the project. CSS analysis is skipped.
     [exec] INFO: Sensor CSS Rules [cssfamily] (done) | time=4ms
     [exec] INFO: Sensor JaCoCo XML Report Importer [jacoco]
     [exec] INFO: 'sonar.coverage.jacoco.xmlReportPaths' is not defined. Using default locations: target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml,build/reports/jacoco/test/jacocoTestReport.xml
     [exec] INFO: No report imported, no coverage information will be imported by JaCoCo XML Report Importer
     [exec] INFO: Sensor JaCoCo XML Report Importer [jacoco] (done) | time=12ms
     [exec] INFO: Sensor C# Project Type Information [csharp]
     [exec] INFO: Sensor C# Project Type Information [csharp] (done) | time=5ms
     [exec] INFO: Sensor C# Properties [csharp]
     [exec] INFO: Sensor C# Properties [csharp] (done) | time=4ms
     [exec] INFO: Sensor JavaXmlSensor [java]
     [exec] INFO: 1 source file to be analyzed
     [exec] INFO: Load project repositories
     [exec] INFO: Load project repositories (done) | time=98ms
     [exec] INFO: 1/1 source file has been analyzed
     [exec] INFO: Sensor JavaXmlSensor [java] (done) | time=472ms
     [exec] INFO: Sensor OpenEdgeCodeColorizer [openedge]
     [exec] INFO: OpenEdge plugin version: 2.14.8-9dff4222
     [exec] INFO: Loading OpenEdge settings for server ID '61CE5E40-AX9F18SstBCNrSkcl_mA'
     [exec] INFO: DLC directory 'D:\TWIN360\TWINSoftware\DLC' will be added to all PROPATH
     [exec] INFO: Using PROPATH : src
     [exec] INFO: XML XREF filter activated
     [exec] INFO: Using schema : df/twin360.df
     [exec] INFO: 1242 RCode read in 2047 ms - 625 classes - 5054 methods - 870 properties
     [exec] INFO: Looking for submodule #1
     [exec] INFO:   No pattern found - Leaving...
     [exec] INFO: Sensor OpenEdgeCodeColorizer [openedge] (done) | time=9505ms
     [exec] INFO: Sensor OpenEdgeDBColorizer [openedge]
     [exec] INFO: Sensor OpenEdgeDBColorizer [openedge] (done) | time=550ms
     [exec] INFO: Sensor OpenEdgeSensor [openedge]
     [exec] INFO: Sensor OpenEdgeSensor [openedge] (done) | time=979ms
     [exec] INFO: Sensor OpenEdgeDBSensor [openedge]
     [exec] INFO: Analyzing df/twin360.df
     [exec] INFO: Sensor OpenEdgeDBSensor [openedge] (done) | time=272ms
     [exec] INFO: Sensor OpenEdgeWarningsSensor [openedge]
     [exec] INFO: Found warning on non-existing file ..\src\Twin\IO\In\Deal\Twin360ApiStpClient.cls
     [exec] INFO: Found warning on non-existing file ..\src\Twin\StaticTool\RateDaysLibrary.cls
     [exec] INFO: 1563 warning files imported
     [exec] INFO: Sensor OpenEdgeWarningsSensor [openedge] (done) | time=125ms
     [exec] INFO: Sensor OpenEdgeProparseSensor [openedge]
     [exec] ERROR: Syntax error -- src/Twin/IO/In/CorporateAction/SubscriptionRightCorporateActionCreator.cls:32:35 -- mismatched input 'SubscriptionRightCorporateActionCreator' expecting LEFTPAREN
     [exec] ERROR: Error during code parsing for src/Twin/IO/In/CorporateAction/SubscriptionRightCorporateActionCreator.cls at position src/Twin/IO/In/CorporateAction/SubscriptionRightCorporateActionCreator.cls:32:35
     [exec] org.antlr.v4.runtime.InputMismatchException: null
     [exec] 	at org.antlr.v4.runtime.DefaultErrorStrategy.recoverInline(DefaultErrorStrategy.java:483)
     [exec] 	at org.antlr.v4.runtime.Parser.match(Parser.java:206)
     [exec] 	at org.prorefactor.proparse.antlr4.Proparse.functionParams(Proparse.java:39907)
     [exec] 	at org.prorefactor.proparse.antlr4.Proparse.constructorStatement(Proparse.java:21144)
     [exec] 	at org.prorefactor.proparse.antlr4.Proparse.inclassStatement(Proparse.java:3978)
     [exec] 	at org.prorefactor.proparse.antlr4.Proparse.classBlockOrStatement(Proparse.java:1238)
     [exec] 	at org.prorefactor.proparse.antlr4.Proparse.classCodeBlock(Proparse.java:1157)
     [exec] 	at org.prorefactor.proparse.antlr4.Proparse.classStatement(Proparse.java:16043)
     [exec] 	at org.prorefactor.proparse.antlr4.Proparse.statement(Proparse.java:2729)
     [exec] 	at org.prorefactor.proparse.antlr4.Proparse.blockOrStatement(Proparse.java:1094)
     [exec] 	at org.prorefactor.proparse.antlr4.Proparse.program(Proparse.java:924)
     [exec] 	at org.prorefactor.treeparser.ParseUnit.parse(ParseUnit.java:334)
     [exec] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.parseMainFile(OpenEdgeProparseSensor.java:307)
     [exec] 	at org.sonar.plugins.openedge.sensor.OpenEdgeProparseSensor.execute(OpenEdgeProparseSensor.java:176)
     [exec] 	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
     [exec] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
     [exec] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
     [exec] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
     [exec] 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
     [exec] 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
     [exec] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
     [exec] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
     [exec] 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:392)
     [exec] 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:388)
     [exec] 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:357)
     [exec] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
     [exec] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
     [exec] 	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:150)
     [exec] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
     [exec] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
     [exec] 	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
     [exec] 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
     [exec] 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
     [exec] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
     [exec] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
     [exec] 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
     [exec] 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
     [exec] 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
     [exec] 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
     [exec] 	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
     [exec] 	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
     [exec] 	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
     [exec] 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

_Originally posted by @Tranborg in https://github.com/Riverside-Software/sonar-openedge/discussions/977_

**Comment by gquerret** [comment]
Confirmed. `PACKAGE-PROTECTED` is accepted in methods, events, properties, variables, but not in constructors...
Will be fixed.

**Comment by gquerret** [comment]
Added `package-private` and `pakcage-protected` in grammar.

**Comment by Tranborg** [comment]
Nice work, and very fast! Now I need to learn how to install this, if it is possible already.

/A Github newbee.

**Comment by gquerret** [comment]
Though there are development snapshots available at https://ci.rssw.eu/job/sonar-openedge/, it is not recommended to do that as these versions can be broken at any time, and compatibility with the rules package can also be broken.
Best idea is to wait for the released versions on https://github.com/Riverside-Software/sonar-openedge/releases
